import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '20260126',
    nutshell: '견고한 경제 지표와 기술주 선별 장세 속 혼조',
    description: '견고한 경제 지표가 경기 연착륙 기대감을 높였지만, 연준의 금리 인하 지연 우려와 맞물리며 시장은 혼조세를 보였습니다. AI 테마 내에서는 경쟁 심화로 종목별 차별화가 뚜렷해지는 양상입니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '예상치를 웃돈 내구재 주문 실적에 힘입어 대형주 중심의 지수는 상승했으나, 중소형주는 하락하며 차별화된 흐름을 보였습니다. 기술주 내에서도 종목별 등락이 엇갈렸습니다.',
    indices: [
      { name: 'S&P 500', value: 5026.35, change: 25.01, changePercent: 0.50 },
      { name: 'NASDAQ', value: 16065.11, change: 68.78, changePercent: 0.43 },
      { name: 'DOW', value: 39127.15, change: 248.86, changePercent: 0.64 },
      { name: 'Russell 2000', value: 1993.00, change: -7.00, changePercent: -0.35 },
    ],
    commodities: [
      { name: '10-Yr Bond', value: 4.21, change: -0.01, changePercent: -0.24 },
      { name: 'WTI Crude', value: 74.55, change: -0.52, changePercent: -0.69 },
    ],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
      { ticker: 'TVC:RUT' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 6,
    icon: 'bank',
    title: '강력한 경제 vs 신중한 연준',
    subtitle: '지표와 정책의 줄다리기',
    description: '예상보다 훨씬 강력한 내구재 주문 실적이 경기 연착륙 기대감을 키웠지만, 동시에 연준이 금리 인하를 서두를 필요가 없다는 근거가 되면서 시장의 복잡한 심리를 반영했습니다.',
    bullets: [
      '내구재 주문, 예상치(1.1%)를 크게 웃도는 5.3% 증가',
      '강력한 경제 지표에도 국채 금리는 소폭 하락',
      '시장은 연준의 3월 금리 인하 가능성을 낮게 평가',
      '다가오는 FOMC에서 파월 의장의 발언에 모든 관심 집중',
    ],
    theme: 'gold',
  },
  {
    id: 3,
    type: 'stats',
    turnId: 7,
    title: '예상을 뛰어넘은 경제 체력',
    description: '기업의 설비 투자 동향을 보여주는 핵심 자본재 주문을 포함한 내구재 주문 지표가 시장 예상치를 크게 상회하며 미국 경제의 견고함을 증명했습니다.',
    stats: [
      { label: '내구재 주문 (전월비)', value: '+5.3%', subtext: '예상치(1.1%) 크게 상회', trend: 'up' },
      { label: '핵심 자본재 주문', value: '+0.7%', subtext: '예상치의 2배 이상', trend: 'up' },
      { label: '미 10년물 국채금리', value: '4.21%', subtext: '강한 지표에도 소폭 하락', trend: 'down' },
    ],
    note: '강력한 경제 지표가 경기 연착륙 기대감을 높였으나, 연준의 금리 인하 시점을 늦출 수 있다는 우려도 공존합니다.',
    theme: 'gold',
    charts: [{ ticker: 'TVC:US10Y' }],
  },
  {
    id: 4,
    type: 'comparison',
    turnId: 11,
    title: '금리 전망 변화에 따른 업종별 명암',
    description: '금리 인하 기대감이 후퇴하면서, 견고한 경제 상황에 수혜를 입는 경기민감주와 고금리 환경에 부담을 느끼는 금리민감주 간의 희비가 엇갈렸습니다.',
    items: [
      {
        label: '경기민감주 (산업재 등)',
        value: '유리',
        description: '강력한 경제 지표와 설비 투자 증가 기대감에 긍정적',
        highlight: true,
      },
      {
        label: '금리민감주 (유틸리티, 부동산 등)',
        value: '불리',
        description: '금리 인하 기대감 후퇴로 고금리 장기화 부담',
        highlight: false,
      },
    ],
    charts: [{ ticker: 'XLI' }, { ticker: 'XLU' }],
  },
  {
    id: 5,
    type: 'headline',
    turnId: 14,
    icon: 'cpu',
    title: 'AI 옥석 가리기 본격화',
    subtitle: '기대에서 실적으로, 경쟁은 심화',
    description: 'AI 테마가 시장을 이끄는 가운데, 투자자들은 막연한 기대감을 넘어 실제 성과와 치열한 경쟁 구도를 냉정하게 평가하기 시작했습니다. 이는 기술주 내에서도 종목별 차별화로 나타나고 있습니다.',
    bullets: [
      '인텔(INTC), 부진한 전망에 주가 하락 지속',
      '마이크로소프트(MSFT), 자체 AI 칩 공개로 엔비디아(NVDA)에 도전',
      '빅테크 간 막대한 투자 비용과 경쟁 구도 부각',
      '이번 주 빅테크 실적 발표가 향후 방향성 결정',
    ],
    theme: 'blue',
  },
  {
    id: 6,
    type: 'comparison',
    turnId: 15,
    title: 'AI 반도체 섹터 내 희비 교차',
    description: '같은 기술 섹터 내에서도 개별 기업의 전략과 실적 전망에 따라 주가 흐름이 뚜렷하게 갈렸습니다. 이는 투자자들이 AI 관련주를 더욱 까다롭게 선별하고 있음을 보여줍니다.',
    items: [
      {
        label: 'Microsoft (MSFT)',
        value: '+0.92%',
        description: '자체 개발 2세대 AI 칩 \'마이아 200\' 공개',
        highlight: true,
      },
      {
        label: 'Intel (INTC)',
        value: '-5.73%',
        description: '지난주 실망스러운 가이던스 여파 지속',
        highlight: false,
      },
    ],
    charts: [{ ticker: 'MSFT' }, { ticker: 'INTC' }],
  },
  {
    id: 7,
    type: 'headline',
    turnId: 17,
    title: '거대 기술 기업의 반란',
    subtitle: 'MSFT, 자체 AI 칩으로 NVDA에 도전',
    description: '마이크로소프트가 자체 AI 칩을 공개하며 엔비디아에 대한 의존도를 줄이고 자체 생태계를 강화하려는 움직임을 본격화했습니다. 이는 장기적인 AI 반도체 시장의 경쟁 구도 변화를 예고합니다.',
    bullets: [
      'MSFT의 \'마이아 200\' 칩: 비용 절감 및 애저(Azure) 서비스 최적화',
      '아마존(Trainium), 구글(TPU)과 같은 자체 칩 개발 흐름 가속화',
      '엔비디아의 CUDA 소프트웨어 생태계에도 직접적인 도전 시작',
      '최대 고객사가 잠재적 경쟁자로 변모하는 구도',
    ],
    theme: 'blue',
    charts: [{ ticker: 'MSFT' }, { ticker: 'NVDA' }, { ticker: 'AMZN' }],
  },
  {
    id: 8,
    type: 'stats',
    turnId: 19,
    title: 'AI 과잉 투자 우려 부상',
    description: 'AI 분야의 천문학적인 자본 지출이 과연 합당한 수익으로 이어질지에 대한 시장의 경계심이 커지고 있습니다. 투자자들은 향후 빅테크 실적 발표에서 투자의 효율성을 집중적으로 점검할 것입니다.',
    stats: [
      { label: '투자자 관심사', value: '자본 지출(CAPEX)', subtext: '빅테크 실적 발표 시 핵심 지표', trend: 'neutral' },
      { label: 'AI 스타트업 현금 소진율', value: '역대 최고 수준', subtext: '수익화에 대한 의문 제기', trend: 'up' },
      { label: '시장 평가 기준', value: '수익성', subtext: '기대감에서 실적으로 전환', trend: 'neutral' },
    ],
    note: '투자자들은 AI 투자의 효율성과 수익화 전략을 면밀히 검토하기 시작했습니다.',
    theme: 'blue',
  },
  {
    id: 9,
    type: 'ticker-intro',
    turnId: 21,
    ticker: 'META',
    companyName: 'Meta Platforms',
    currentPrice: 398.50,
    dayChange: 4.25,
    dayChangePercent: 1.08,
    description: '실적 발표를 앞두고 주가는 1% 넘게 상승했으나, 회사는 플랫폼 중독성 관련 소송이라는 중대한 사법 리스크에 직면해 있어 주가와 현실 간의 괴리가 관찰됩니다.',
    charts: [{ ticker: 'META' }],
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 24,
    ticker: 'META',
    title: '핵심 리스크: 청소년 중독 소송',
    description: '이번 소송은 향후 유사 소송의 판례가 될 수 있는 \'벨웨더 재판\'으로, 패소 시 메타의 핵심 알고리즘 변경을 강제할 수 있어 비즈니스 모델에 구조적인 손상을 입힐 수 있습니다.',
    points: [
      '플랫폼 중독성 설계 관련 중대 재판 직면',
      '단순 벌금을 넘어 비즈니스 모델 자체의 지속 가능성 문제',
      '패소 시, 사용자 참여 극대화 알고리즘 변경 강제 가능성',
      '수익 창출 능력에 구조적 손상을 입힐 수 있는 위협으로 평가됨',
    ],
    outlook: 'Significant Legal Risk',
    outlookColor: 'rose',
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 26,
    ticker: 'META',
    title: '기회 요인: 미래 성장 서사',
    description: '일각에서는 소송 압박이 오히려 AI 기술 진화를 촉진하고, 메타버스 사업과 같은 독립적인 성장 동력이 규제 리스크를 상쇄할 것이라는 긍정적인 시각도 존재합니다.',
    points: [
      '소송 압박이 AI 기술 진화와 새로운 비즈니스 모델 구축을 촉진할 것이라는 기대',
      '리얼리티 랩스가 이끄는 메타버스 사업은 독립적인 성장 동력으로 부각',
      '시장은 단기적인 법적 리스크보다 미래 성장 가능성에 베팅하는 경향',
    ],
    outlook: 'Future Growth Narrative',
    outlookColor: 'purple',
  },
  {
    id: 12,
    type: 'ticker-analysis',
    turnId: 28,
    ticker: 'META',
    title: '종합 분석: 리스크와 기회의 줄다리기',
    description: '메타버스 등 미래 사업은 현재 광고 사업의 막대한 현금흐름에 의존합니다. 소송 리스크가 현재의 핵심 수익 모델을 직접 겨냥하고 있다는 점에서, 리스크 관리가 필요한 시점으로 보입니다.',
    points: [
      '미래 사업(메타버스)은 현재 광고 사업의 현금흐름에 전적으로 의존',
      '소송 리스크는 현재의 핵심 수익 모델을 직접 겨냥',
      '성장 스토리는 아직 실현되지 않은 미래의 가능성',
      '시장이 현재의 위험을 외면하는 경향이 있어, 주의가 요구되는 상황',
    ],
    outlook: 'Risk vs. Reward',
    outlookColor: 'amber',
  },
  {
    id: 13,
    type: 'events',
    turnId: 31,
    title: '이번 주 핵심 이벤트: FOMC',
    description: '올해 첫 FOMC 회의가 예정되어 있어 시장의 모든 관심이 집중될 전망입니다. 금리 결정 자체보다 향후 금리 인하 시점에 대한 연준의 입장을 확인하는 것이 중요합니다.',
    events: [
      {
        date: '2026-01-28',
        label: 'FOMC 금리 결정 및 기자회견',
        description: '금리 동결이 유력. 파월 의장의 향후 금리 경로에 대한 발언이 최대 관심사.',
      },
    ],
  },
  {
    id: 14,
    type: 'events',
    turnId: 34,
    title: '주요 경제 지표 및 이벤트',
    description: 'FOMC 외에도 미국 소비 심리와 국채 시장의 수요를 확인할 수 있는 주요 지표 발표와 이벤트가 예정되어 있어 시장 변동성에 영향을 줄 수 있습니다.',
    events: [
      {
        date: '2026-01-27',
        label: 'CB 소비자신뢰지수',
        description: '미국 가계의 소비 심리를 파악할 수 있는 중요 지표.',
      },
      {
        date: '2026-01-27',
        label: '미 5년물 국채 입찰',
        description: '국채 수요를 통해 시장 금리 변동성을 예측.',
      },
      {
        date: '2026-01-29',
        label: '미 7년물 국채 입찰',
        description: '장기물 국채 입찰 결과는 성장주 투자 심리에 영향.',
      },
    ],
  },
  {
    id: 15,
    type: 'closing',
    turnId: 35,
    headline: '연준의 입을 주목하는 시장',
    tagline: '금리 경로와 AI 수익성, 두 가지 질문에 답을 찾을 한 주',
    description: '다음 주는 연준의 통화정책 방향성을 확인하고, 빅테크 실적을 통해 AI 투자의 현실적인 성과를 가늠해 볼 수 있는 중요한 분기점이 될 전망입니다.',
  },
];