import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-04-11',
    nutshell: '소비심리 악화 속 AI 기술주 중심의 차별화 장세',
    description: '사상 최저치로 떨어진 소비심리와 지정학적 불확실성이 시장을 압박하는 가운데, 인공지능(AI) 관련 기술주에 대한 기대감은 꺾이지 않으며 지수별 혼조세를 보였습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '주요 지수 혼조세 마감',
    description: '소비심리 악화와 지정학적 리스크가 시장 전반을 압박했지만, 기술주 중심의 나스닥 지수는 AI 관련주 강세에 힘입어 유일하게 상승 마감했습니다.',
    indices: [
      { name: 'S&P 500', value: 6816.89, change: -7.77, changePercent: -0.11 },
      { name: 'NASDAQ', value: 22902.89, change: 80.47, changePercent: 0.35 },
      { name: 'DOW', value: 47916.57, change: -269.23, changePercent: -0.56 },
      { name: 'Russell 2000', value: 2630.59, change: -5.72, changePercent: -0.22 },
    ],
    commodities: [
      { name: 'WTI Crude', value: 95.51, change: -2.36, changePercent: -2.41 },
      { name: 'Gold Futures', value: 4772.80, change: -19.40, changePercent: -0.40 },
      { name: 'Dollar Index', value: 98.67, change: -0.15, changePercent: -0.15 },
    ],
    charts: [
      { ticker: 'DJ:DJI' },
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'TVC:RUT' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 6,
    icon: 'ship',
    title: '지정학적 리스크: 호르무즈 해협',
    subtitle: '에너지 가격 불안과 공급망 우려 증폭',
    description: '미국과 이란의 임시 휴전에도 불구하고 호르무즈 해협의 불확실성은 해소되지 않고 있습니다. 이란의 사실상 통행 통제로 유가는 높은 수준을 유지하고 있으며, 변동성 지수(VIX) 역시 높은 경계감을 보여주고 있습니다.',
    bullets: [
      '임시 휴전에도 통행량 급감 (하루 100척 → 한 자릿수)',
      '이란, 통행량 하루 15척 제한 위협',
      '국제 유가 높은 수준 유지 (WTI $95, 브렌트 $94)',
      '변동성 지수(VIX) 19선, 높은 경계감 지속',
    ],
    theme: 'red',
    charts: [
      { ticker: 'NYMEX:CL' },
      { ticker: 'TVC:VIX' },
    ],
  },
  {
    id: 3,
    type: 'stats',
    turnId: 9,
    title: '이란의 해협 통제와 경제적 압박',
    description: '이란은 해협 통제권을 이용해 새로운 수익원을 창출하고 있으며, 이는 글로벌 에너지 공급망에 직접적인 비용을 부과하여 인플레이션 압력을 가중시키고 있습니다.',
    stats: [
      { label: '통행세 요구', value: '배럴당 $1', subtext: '암호화폐로 지불 요구', trend: 'up' },
      { label: '골드만삭스 유가 전망', value: '평균 $100', subtext: '4분기, 휴전 결렬 시', trend: 'up' },
      { label: '美 원유 시추공 수', value: '545개', subtext: '전주 대비 3개 감소', trend: 'down' },
    ],
    note: '미국 내 원유 생산이 지정학적 리스크에 대응할 만큼 빠르게 늘지 않고 있다는 점도 부담입니다.',
    theme: 'red',
  },
  {
    id: 4,
    type: 'headline',
    turnId: 11,
    title: '방산주, 이례적 약세',
    subtitle: '시장은 전면전 확산 가능성을 낮게 평가',
    description: '통상적인 예상과 달리, 지정학적 긴장 고조에도 불구하고 대표 방산주들은 하락했습니다. 이는 시장이 현재 상황을 통제 가능한 국지적 긴장 상태로 해석하고 있음을 시사합니다.',
    bullets: [
      '록히드 마틴(LMT): -0.9% 하락',
      'RTX 코퍼레이션(RTX): -0.6% 이상 하락',
      '배경: 휴전 협상 진행으로 투기적 수요 제한',
      '실질적 위험: 선박 국적 허위 기재 사례 보고',
    ],
    theme: 'amber',
    charts: [
      { ticker: 'NYSE:LMT' },
      { ticker: 'NYSE:RTX' },
    ],
  },
  {
    id: 5,
    type: 'headline',
    turnId: 14,
    icon: 'user-minus',
    title: '소비심리 사상 최저치 경신',
    subtitle: '인플레이션과 지정학적 리스크가 경제 전망 압박',
    description: '4월 미시간대 소비심리지수 예비치가 사상 최저치를 경신하며 시장에 큰 충격을 주었습니다. 소비자들은 이란과의 갈등과 그로 인한 물가 상승을 가장 큰 위협으로 꼽았습니다.',
    bullets: [
      '4월 미시간 소비심리지수: 47.6 (예상 52.3, 전월 53.3)',
      '주요 원인: 이란과의 갈등, 물가 상승 우려',
      '시장 반응: S&P 500 -0.11%, 필수소비재 섹터 -1% 이상 하락',
      '안전자산 선호: 10년물 국채금리 4.3% 상회',
    ],
    theme: 'red',
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'AMEX:XLP' },
    ],
  },
  {
    id: 6,
    type: 'stats',
    turnId: 17,
    title: '소비 위축, 필수소비재까지 타격',
    description: '인플레이션이 장기화되면서 소비자들이 식료품이나 생필품 같은 필수 항목에서조차 지출을 줄이려는 움직임을 보이고 있습니다. 이는 관련 기업들의 실적 둔화 우려로 이어지고 있습니다.',
    stats: [
      { label: '필수소비재(XLP) 하락률', value: '-1.29%', subtext: '시장 대비 부진', trend: 'down' },
      { label: '임의소비재(XLY) 대비', value: '더 큰 하락폭', subtext: '필수 항목 지출 축소 신호', trend: 'down' },
      { label: '향후 1년 기대 인플레이션', value: '상승', subtext: '미시간대 조사 결과', trend: 'up' },
    ],
    note: '소비자들이 앞으로도 고물가가 계속될 것으로 보고 지갑을 닫고 있음을 시사합니다.',
    theme: 'red',
    charts: [
      { ticker: 'AMEX:XLP' },
      { ticker: 'AMEX:XLY' },
    ],
  },
  {
    id: 7,
    type: 'headline',
    turnId: 19,
    icon: 'cpu',
    title: 'AI 기술주, 나홀로 강세',
    subtitle: '구조적 성장 기대감이 거시 악재 압도',
    description: '경기 둔화 우려가 커질수록 투자자들은 경제 사이클의 영향을 덜 받으면서 구조적 성장이 가능한 AI 분야로 몰리고 있습니다. AI가 단순한 테마를 넘어 산업 패러다임을 바꾸고 있다는 인식이 확산되고 있습니다.',
    bullets: [
      '엔비디아(NVDA): +2.5% 이상 상승하며 나스닥 견인',
      '성장 동력: 경기 사이클 영향 덜 받는 구조적 성장성',
      '장기 투자 근거: 빅테크, AI 데이터센터 전력 위해 원자력 투자',
      '시장 심리: 소비 위축 우려 속 유일한 돌파구로 부상',
    ],
    theme: 'blue',
    charts: [
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'NASDAQ:NVDA' },
    ],
  },
  {
    id: 8,
    type: 'comparison',
    turnId: 23,
    title: '엇갈린 시장: 소비 위축 vs AI 기대감',
    description: '오늘 시장은 소비심리 악화라는 거시적 악재와 AI라는 구조적 성장 스토리가 충돌하며 극심한 차별화 장세를 보였습니다.',
    items: [
      {
        label: '하락 압력 요인',
        value: '경기 민감/소비주',
        description: '소비심리 사상 최저, 지정학적 리스크, 유가 불안, CPI 쇼크',
        highlight: false,
      },
      {
        label: '상승 동력 요인',
        value: 'AI 기술주',
        description: '구조적 성장 기대, 빅테크 중심 자금 쏠림, 차별화 장세',
        highlight: true,
      },
      {
        label: '시장 지수',
        value: '혼조세',
        description: '다우/S&P 500 하락, 나스닥 상승',
        highlight: false,
      },
    ],
  },
  {
    id: 9,
    type: 'headline',
    turnId: 25,
    title: '메타(META), 차세대 AI 모델 기대감',
    subtitle: '오픈소스 \'라마 3\' 출시 임박',
    description: '메타가 곧 출시할 차세대 거대 언어 모델 \'라마 3\'에 대한 기대감이 주가를 끌어올렸습니다. 이는 오픈AI와 구글에 필적할 대항마가 될 것이라는 분석이 지배적입니다.',
    bullets: [
      '\'라마 3\': GPT-4, 제미나이의 강력한 대항마로 부상',
      '전략: 오픈소스 공개로 개발자 생태계 장악',
      '장기 목표: 광고 및 메타버스 플랫폼 사용자 유입',
      '주가: 빅테크 혼조세 속 견조한 상승세 기록',
    ],
    theme: 'blue',
    charts: [
      { ticker: 'NASDAQ:META' },
    ],
  },
  {
    id: 10,
    type: 'headline',
    turnId: 27,
    title: '반도체 섹터, AI 랠리 주도',
    subtitle: '데이터센터 수요 폭발, 가장 확실한 수혜주로 부상',
    description: 'AI 모델의 연산 능력을 좌우하는 GPU 수요가 폭발적으로 증가하면서, 엔비디아를 필두로 한 반도체 섹터는 AI 테마의 가장 확실한 수혜주로 다시 한번 입증되었습니다.',
    bullets: [
      'GPU 수요 폭증으로 엔비디아 등 실적 전망 상향',
      '클라우드 기업들의 반도체 주문, TSMC 등 파운드리 실적에 긍정적',
      '美 칩스법 보조금 지급 본격화 기대감',
      '필라델피아 반도체 지수(SOX), 시장 약세에도 강한 흐름',
    ],
    theme: 'blue',
    charts: [
      { ticker: 'NASDAQ:SOX' },
      { ticker: 'NYSE:TSM' },
    ],
  },
  {
    id: 11,
    type: 'ticker-intro',
    turnId: 28,
    ticker: 'MRVL',
    companyName: 'Marvell Technology, Inc.',
    currentPrice: 128.49,
    dayChange: 8.56,
    dayChangePercent: 7.14,
    description: 'AI 데이터센터의 핵심 인프라 공급자로 부상하며, 어려운 시장 환경 속에서 7%가 넘는 인상적인 급등세를 기록했습니다.',
    charts: [
      { ticker: 'NASDAQ:MRVL' },
    ],
  },
  {
    id: 12,
    type: 'ticker-analysis',
    turnId: 31,
    ticker: 'MRVL',
    title: '성장과 리스크의 공존: 고객 집중도',
    description: '마벨의 사업 구조는 소수의 핵심 고객에게 매출이 극단적으로 집중되어 있어, 이는 높은 성장 잠재력과 심각한 사업 리스크를 동시에 의미하는 양날의 검과 같습니다.',
    points: [
      '**양날의 검:** 상위 10개 고객이 전체 매출의 82% 차지.',
      '**긍정적 해석:** 최대 클라우드 기업들과의 깊은 기술 파트너십.',
      '**부정적 해석:** 핵심 고객 이탈 시 회사 전체가 흔들리는 구조적 취약점.',
      '**워런트 계약:** 고객 이탈 방지를 위해 지분까지 제공, 가격 할인 성격 내포.',
    ],
    outlook: '고객 집중도는 높은 성장 잠재력과 심각한 사업 리스크를 동시에 의미합니다.',
    outlookColor: 'amber',
  },
  {
    id: 13,
    type: 'ticker-analysis',
    turnId: 35,
    ticker: 'MRVL',
    title: '투자 관점: 기대감 선반영',
    description: '현재 주가는 AI에 대한 기대감을 상당 부분 선반영하고 있어, 기업이 스스로 인정한 명백한 위험 요인들에 대한 안전마진이 부족한 상태로 판단됩니다.',
    points: [
      '**주가 수준:** AI 기대감을 상당 부분 선반영하여 안전마진 부족.',
      '**급등 배경:** 펀더멘털 개선보다 AI 성장 서사에 대한 시장 낙관론이 극대화된 결과.',
      '**핵심 리스크:** 소수 고객 의존도, 고객사 자체 칩 개발 위협, 대만 생산 집중.',
      '**결론:** 기업이 인정한 명백한 위험 요소들이 존재.',
    ],
    outlook: '현재 주가는 잠재적 보상보다 내재된 위험이 더 클 수 있는 국면으로, 신중한 접근이 요구됩니다.',
    outlookColor: 'rose',
  },
  {
    id: 14,
    type: 'events',
    turnId: 39,
    title: '향후 주목할 경제 지표',
    description: '이번 주 물가 지표 발표 이후, 시장의 관심은 소비자의 심리와 실제 소비 여력을 확인할 수 있는 지표들로 이동할 것입니다.',
    events: [
      {
        date: '2026-04-10',
        label: '미시간대 소비자심리지수',
        description: '특히 \'기대 인플레이션\' 항목이 금리 경로에 대한 단서 제공.',
      },
      {
        date: '2026-04-15',
        label: '연준 베이지북',
        description: '통계 너머의 현장 경제 동향 파악.',
      },
      {
        date: '2026-04-21',
        label: '소매판매 지표',
        description: '고금리 환경 속 실제 소비 여력 확인.',
      },
    ],
  },
  {
    id: 15,
    type: 'closing',
    turnId: 43,
    headline: '금리 인하 기대감 후퇴, 변동성 장세 대비',
    tagline: '시장의 서사가 바뀌었다: 펀더멘털에 집중할 때',
    description: '연초의 금리 인하 횟수 논의에서 \'인하 가능 여부\'에 대한 의문으로 시장의 초점이 이동했습니다. 곧 시작될 1분기 어닝 시즌이 높은 비용 환경을 이겨내는 기업을 가려내는 중요한 옥석 가리기의 장이 될 것입니다.',
  },
];