import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-02-02',
    nutshell: '예상 뛰어넘은 제조업 지표에 경기 연착륙 기대감 확산',
    description: '견조한 1월 제조업 지표가 경기 침체 우려를 완화하며 시장 전반에 긍정적인 영향을 미쳤습니다. 하지만 기업 실적에 따라 주가가 극명하게 엇갈리는 차별화 장세가 나타났습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '미국 1월 제조업 구매관리자지수(PMI)가 예상을 크게 상회하며 3년 만에 가장 빠른 확장세를 보이자, 경기 연착륙 기대감이 커지며 3대 지수 모두 상승 마감했습니다.',
    indices: [
      { name: 'S&P 500', value: 5024.31, change: 26.98, changePercent: 0.54 },
      { name: 'NASDAQ', value: 15947.74, change: 88.75, changePercent: 0.56 },
      { name: 'DOW', value: 38559.84, change: 400.92, changePercent: 1.05 },
    ],
    commodities: [],
    charts: [
      { ticker: 'DJ:DJI', title: '다우존스' },
      { ticker: 'SP:SPX', title: 'S&P 500' },
      { ticker: 'NASDAQ:IXIC', title: '나스닥' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 7,
    icon: 'trending-up',
    title: '견조한 제조업 지표',
    subtitle: '경기 연착륙 기대감에 불을 지피다',
    description: '공급관리협회(ISM)의 1월 제조업 PMI가 시장 예상치를 크게 웃돌며 3년여 만에 가장 강력한 확장세를 기록했습니다. 이는 경기 침체 우려를 완화하고 투자 심리를 크게 개선시키는 요인으로 작용했습니다.',
    bullets: [
      '1월 ISM 제조업 PMI, 3년 만에 최고치 기록',
      '경기 침체 우려 완화 및 연착륙 시나리오 강화',
      '미 10년물 국채 금리 4.28%까지 상승',
      '산업재(XLI), 소재(XLB) 등 경기민감주 동반 강세',
    ],
    theme: 'blue',
    charts: [
      { ticker: 'XLI', title: '산업재 ETF' },
      { ticker: 'XLB', title: '소재 ETF' },
    ],
  },
  {
    id: 3,
    type: 'stats',
    turnId: 9,
    title: 'ISM 제조업 PMI 세부 지표 분석',
    description: '신규 주문과 고용 등 세부 항목이 긍정적인 모습을 보였으나, 지불 가격 지수 상승은 인플레이션 우려를 일부 자극했습니다.',
    stats: [
      { label: '신규 주문 지수', value: '큰 폭 개선', subtext: '향후 수요 기대감 증대', trend: 'up' },
      { label: '고용 지수', value: '확장 국면 유지', subtext: '견고한 노동시장 재확인', trend: 'up' },
      { label: '지불 가격 지수', value: '예상 상회', subtext: '인플레이션 압력 우려', trend: 'down' },
    ],
    note: '경제 성장과 물가 안정 사이의 균형점을 찾아가는 과정이 시장의 주요 관전 포인트가 될 전망입니다.',
    theme: 'blue',
  },
  {
    id: 4,
    type: 'headline',
    turnId: 11,
    icon: 'git-compare',
    title: '엇갈린 기업 실적',
    subtitle: '거시 훈풍 속 뚜렷해진 종목별 차별화',
    description: '경기 연착륙 기대감이라는 우호적인 환경 속에서도, 투자자들은 개별 기업의 실적과 미래 성장 동력을 엄격한 잣대로 평가했습니다. 실적 내용에 따라 주가 반응이 극명하게 엇갈렸습니다.',
    bullets: [
      '팔란티어: AI 수요 증명하며 시간 외 거래에서 급등',
      '디즈니: 호실적에도 CEO 승계 불확실성으로 급락',
      'NXP: 핵심 사업부 성장 둔화 우려에 하락',
    ],
    theme: 'purple',
    charts: [
      { ticker: 'PLTR', title: '팔란티어' },
      { ticker: 'DIS', title: '월트 디즈니' },
      { ticker: 'NXPI', title: 'NXP 세미컨덕터스' },
    ],
  },
  {
    id: 5,
    type: 'comparison',
    turnId: 15,
    title: '실적 발표 후 명암이 갈린 기업들',
    description: '비슷하게 시장 예상을 상회하는 실적을 발표했음에도, 미래 전망과 내부 리스크 요인에 따라 시장의 평가는 크게 달랐습니다.',
    items: [
      {
        label: 'Palantir (PLTR)',
        value: '주가 급등 (+6% 시간 외)',
        description: 'AI 플랫폼에 대한 폭발적 수요를 실적으로 증명하며 강력한 성장성에 대한 기대를 높였습니다.',
        highlight: true,
      },
      {
        label: 'Walt Disney (DIS)',
        value: '주가 급락 (-7%)',
        description: '호실적에도 불구하고 CEO 후계자 문제 등 미래 경영 불확실성이 부각되며 투자 심리가 위축되었습니다.',
        highlight: false,
      },
    ],
  },
  {
    id: 6,
    type: 'ticker-intro',
    turnId: 20,
    ticker: 'PLTR',
    companyName: 'Palantir Technologies',
    currentPrice: 24.50,
    dayChange: -0.55,
    dayChangePercent: -2.19,
    description: '예상을 뛰어넘는 분기 실적 발표 후 시간 외 거래에서 급등했으나, 정규장에서는 차익 실현 매물 등으로 하락 마감하며 전형적인 \'뉴스에 파는\' 패턴을 보였습니다.',
    charts: [{ ticker: 'PLTR' }],
  },
  {
    id: 7,
    type: 'ticker-analysis',
    turnId: 21,
    ticker: 'PLTR',
    title: '핵심 투자 포인트: AI 운영체제로서의 잠재력',
    description: '팔란티어는 단순 소프트웨어 기업을 넘어, 정부와 기업을 위한 AI 운영체제로 자리매김하고 있습니다. 특히 상업 부문의 폭발적인 성장은 AI 플랫폼의 강력한 경쟁력을 보여줍니다.',
    points: [
      '4분기 매출 전년 대비 70% 급증, 시장 기대치 압도',
      '미국 상업 부문 매출 100% 이상 성장하며 성장 가속화',
      '정부와 민간 양쪽에서 AI 플랫폼에 대한 강력한 수요 확인',
      '국방/정보 분야에서 축적된 데이터 통합 및 보안 기술력 보유',
    ],
    outlook: 'AI Momentum',
    outlookColor: 'purple',
  },
  {
    id: 8,
    type: 'ticker-analysis',
    turnId: 23,
    ticker: 'PLTR',
    title: '주요 리스크 및 고려사항',
    description: '매력적인 성장 서사 이면에는 높은 밸류에이션 부담과 이익의 질, 구조적 리스크 등 신중하게 평가해야 할 요인들이 존재합니다.',
    points: [
      '높은 밸류에이션: 향후 완벽한 성장을 가정한 주가 수준이라는 평가',
      '이익의 질: 영업현금흐름의 상당 부분이 주식 기준 보상(SBC)에서 발생하여 주주가치 희석 우려',
      '정부 계약의 불안정성: 계약 조기 종료 가능성을 포함하는 \'편의 해지\' 조항 존재',
      '평판 리스크: 감시 기술 관련 논란이 상업 부문 고객 확보에 걸림돌이 될 가능성',
    ],
    outlook: 'High Valuation',
    outlookColor: 'amber',
  },
  {
    id: 9,
    type: 'events',
    turnId: 31,
    title: '다음 주 주요 경제 이벤트',
    description: '다음 주에는 서비스업 PMI와 소비자물가지수(CPI) 발표가 예정되어 있어, 시장의 인플레이션 경로와 연준의 정책 방향에 대한 단서를 제공할 것입니다.',
    events: [
      {
        date: '2026-02-04',
        label: 'ISM 서비스업 PMI',
        description: '미국 경제의 3분의 2를 차지하는 서비스업 경기를 판단할 핵심 지표입니다. 특히 \'가격 지불 지수\'가 인플레이션 향방을 가늠할 단서가 될 것입니다.',
      },
      {
        date: '2026-02-11',
        label: '1월 소비자물가지수 (CPI)',
        description: '최근 임금 상승세와 맞물려, 인플레이션 둔화 추세가 지속되는지 여부를 확인할 수 있는 가장 중요한 지표입니다.',
      },
    ],
  },
  {
    id: 10,
    type: 'closing',
    turnId: 36,
    headline: '강한 경제 속 옥석 가리기 장세',
    tagline: '거시 지표와 개별 기업 펀더멘털을 함께 봐야 할 때',
    description: '견조한 제조업 지표가 경기 연착륙 기대감을 높였지만, 시장의 관심은 개별 기업의 미래 성장성과 내재된 리스크로 이동하고 있습니다. 다가오는 물가 지표가 시장의 다음 방향을 결정할 주요 변수가 될 전망입니다.',
  },
];