import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-02-10',
    nutshell: '소비 둔화 신호 속 엇갈린 실적에 차별화 장세',
    description: '오늘 미국 증시는 소매 판매 부진과 기업들의 엇갈린 실적 전망이 맞물리며 혼조세로 마감했습니다. 다우 지수는 소폭 상승했으나, 기술주 중심의 나스닥은 하락하며 업종별 차별화가 뚜렷하게 나타났습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '소비 심리 위축 우려와 개별 기업의 미래 전망에 대한 민감도가 높아지면서 주요 지수가 엇갈린 흐름을 보였습니다. 다우는 사상 최고치를 경신했으나 나스닥은 하락 마감했습니다.',
    indices: [
      { name: 'S&P 500', value: 5009.85, change: -16.58, changePercent: -0.33 },
      { name: 'NASDAQ', value: 15864.31, change: -94.19, changePercent: -0.59 },
      { name: 'DOW', value: 38935.76, change: 38.94, changePercent: 0.10 },
    ],
    commodities: [
      { name: '10년물 국채금리', value: 4.15, change: -0.02, changePercent: -0.48 },
    ],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 7,
    icon: 'trending-down',
    title: '미래 전망에 엇갈린 기술주',
    subtitle: '실적보다 가이던스가 주가를 결정하다',
    description: '국채 금리가 안정세를 보였음에도 불구하고, 일부 기업의 실망스러운 미래 전망이 기술주 전반의 투자 심리를 위축시켰습니다. 이는 거시 지표보다 개별 기업의 성장성에 대한 우려가 더 크게 작용했음을 시사합니다.',
    bullets: [
      '나스닥 지수 0.59% 하락, 다우 지수 0.1% 상승',
      '기술 섹터 ETF(XLK) 0.56% 하락하며 약세 확인',
      '엔비디아(-0.79%), 알파벳(-1.77%) 등 대형 기술주 동반 하락',
      '안정된 국채 금리에도 불구하고 투자 심리 개선 실패',
    ],
    theme: 'blue',
    charts: [
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
      { ticker: 'XLK' },
      { ticker: 'TVC:US10Y' },
    ],
  },
  {
    id: 3,
    type: 'stats',
    turnId: 9,
    title: '코카콜라(KO): 양호한 실적, 보수적 전망',
    description: '4분기 매출은 시장 예상을 웃돌았으나, 올해 성장률 가이던스를 보수적으로 제시하면서 주가에 부담으로 작용했습니다. 좋은 성적표에도 미래에 대한 자신감 부족이 주가를 끌어내린 사례입니다.',
    stats: [
      { label: '4분기 유기적 매출', value: '+5%', subtext: '시장 예상치 상회', trend: 'up' },
      { label: '2026년 매출 성장률 전망', value: '4~5%', subtext: '컨센서스(5%) 하회', trend: 'down' },
      { label: '주가 등락률', value: '-1.49%', subtext: '가이던스 실망감 반영', trend: 'down' },
    ],
    note: '특히 일부 해외 시장에서의 압박을 언급한 점이 투자 심리를 위축시켰습니다.',
    theme: 'red',
    charts: [{ ticker: 'KO' }],
  },
  {
    id: 4,
    type: 'stats',
    turnId: 11,
    title: '리프트(LYFT): 실적 쇼크와 시간 외 폭락',
    description: '장 마감 후 발표된 실적에서 시장 기대치를 크게 밑도는 전망을 제시하며 투자자들에게 큰 충격을 안겼습니다. 경쟁사 우버와 비교되며 성장성에 대한 의구심이 증폭되었습니다.',
    stats: [
      { label: '1분기 이익 전망', value: '기대치 하회', subtext: '혹한기 폭풍 영향', trend: 'down' },
      { label: '2025년 실적 전망', value: '영업 손실', subtext: '시장 기대(흑자)와 상반', trend: 'down' },
      { label: '시간 외 주가', value: '-14% 이상', subtext: '실망 매물 출회', trend: 'down' },
    ],
    note: '성장 궤도에 대한 의구심이 주가에 얼마나 가혹하게 반응하는지를 보여준 사례입니다.',
    theme: 'red',
    charts: [{ ticker: 'LYFT' }, { ticker: 'UBER' }],
  },
  {
    id: 5,
    type: 'ticker-intro',
    turnId: 14,
    ticker: 'CRM',
    companyName: 'Salesforce',
    currentPrice: 198.23,
    dayChange: 1.52,
    dayChangePercent: 0.77,
    description: '세일즈포스는 장 초반 경쟁사의 호실적에 힘입어 급등했으나, 상승분을 대부분 반납하며 마감했습니다. 이는 AI에 대한 기대감과 기업 고유의 리스크 사이에서 투자 심리가 팽팽함을 보여줍니다.',
    charts: [{ ticker: 'CRM' }],
  },
  {
    id: 6,
    type: 'ticker-analysis',
    turnId: 17,
    ticker: 'CRM',
    title: '핵심 기회: AI 플랫폼으로의 진화',
    points: [
      '새로운 AI 에이전트 \'에이전트포스\'를 통한 서비스 혁신',
      '기존 구독 모델에서 AI 가치 기반의 \'소비 기반\' 가격 모델로 전환',
      '수십 년간 축적한 방대한 고객 데이터를 활용한 \'데이터 클라우드\'의 경쟁 우위',
    ],
    description: '단순 CRM 소프트웨어를 넘어 엔터프라이즈 AI 플랫폼으로 진화하려는 전략이 성공할 경우, 기업 가치를 재평가할 수 있는 핵심 성장 동력으로 관찰됩니다.',
    outlook: 'AI Momentum',
    outlookColor: 'purple',
  },
  {
    id: 7,
    type: 'ticker-analysis',
    turnId: 19,
    ticker: 'CRM',
    title: '주요 리스크: 경쟁, 신사업, 그리고 재무',
    points: [
      '경쟁 심화: 프레시웍스 등 AI 네이티브 경쟁사들의 시장 점유율 잠식',
      '신사업 불확실성: 회사가 직접 공시(10-Q)를 통해 인정한 가격 책정의 어려움',
      '재무 부담: 인포매티카 인수 관련 부채 조달이 재무 건전성에 미칠 영향',
    ],
    description: '화려한 AI 비전 이면에 경쟁 심화, 신사업의 실행 리스크, 재무 부담이라는 세 가지 그림자가 존재하며, 이들이 서로 맞물려 수익성에 영향을 줄 가능성이 있습니다.',
    outlook: 'Execution Risk',
    outlookColor: 'amber',
  },
  {
    id: 8,
    type: 'comparison',
    turnId: 21,
    title: '세일즈포스(CRM) 종합 분석',
    description: '현재 주가는 미래 AI 성공 가능성을 반영하고 있으나, 그 과정에서 발생할 수 있는 비용과 재무적 위험은 충분히 고려되지 않았을 수 있다는 분석이 제기됩니다.',
    items: [
      {
        label: '기회 요인',
        value: 'AI 플랫폼 전환',
        description: '에이전트포스, 소비 기반 모델, 데이터 클라우드를 통한 성장 잠재력',
        highlight: true,
      },
      {
        label: '위험 요인',
        value: '수익성 압박',
        description: '경쟁 대응을 위한 비용 증가와 인수 관련 부채가 현금흐름을 감소시킬 수 있다는 우려',
        highlight: false,
      },
    ],
  },
  {
    id: 9,
    type: 'events',
    turnId: 23,
    title: '이번 주 시장의 향방을 결정할 이벤트',
    description: '이번 주는 연준의 다음 행보를 가늠할 핵심 데이터인 고용과 물가 지표 발표가 예정되어 있어, 시장의 변동성이 확대될 수 있습니다.',
    events: [
      {
        date: '내일 (2/11)',
        label: '고용보고서 (비농업 신규 고용)',
        description: '예상치: 7만 명. 노동시장 강도 확인.',
      },
      {
        date: '내일 (2/11)',
        label: '10년물 국채 입찰',
        description: '장기 금리 방향성 예측 단서.',
      },
      {
        date: '목요일 (2/12)',
        label: '30년물 국채 입찰',
        description: '장기 시장 금리 전망 참고.',
      },
      {
        date: '금요일 (2/13)',
        label: '소비자물가지수 (근원 CPI)',
        description: '예상치: 전월 대비 +0.3%. 인플레이션 둔화 여부 확인.',
      },
    ],
  },
  {
    id: 10,
    type: 'closing',
    turnId: 29,
    headline: '데이터를 확인하고 대응하는 지혜',
    tagline: '고용과 물가, 두 지표가 시장의 모든 것을 설명하는 한 주',
    description: '섣부른 예측에 기반한 투자보다는, 발표되는 경제 데이터를 꼼꼼히 확인하고 그에 따른 시장의 반응을 차분히 지켜보면서 대응 전략을 세우는 것이 중요합니다.',
  },
];