import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-02-04',
    nutshell: '엇갈린 기업 실적에 나스닥 하락, 다우 상승',
    description: '오늘 시장은 개별 기업들의 4분기 실적과 향후 전망에 따라 지수별 방향이 크게 엇갈렸습니다. 기술주는 부진했지만, 헬스케어와 가치주가 강세를 보이며 다우 지수는 상승 마감했습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '기업들의 엇갈린 4분기 실적 발표가 시장을 지배했습니다. 다우 지수는 상승했으나, 기술주 중심의 나스닥은 향후 성장성에 대한 우려로 큰 폭으로 하락했습니다.',
    indices: [
      { name: 'DOW', value: 49501, change: 247.5, changePercent: 0.50 },
      { name: 'NASDAQ', value: 22904, change: -343.56, changePercent: -1.50 },
      { name: 'S&P 500', value: 6800, change: -34.00, changePercent: -0.50 },
    ],
    commodities: [],
    charts: [
      { ticker: 'DJ:DJI' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'SP:SPX' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 5,
    icon: 'arrows-left-right',
    title: '오늘의 핵심 테마',
    subtitle: '기술주 vs 가치주, 엇갈린 명암',
    description: '시장은 철저히 두 개로 나뉘었습니다. 미래 성장성에 대한 기대와 우려가 교차하며 기술주와 전통 가치주 사이에 자금 이동이 뚜렷하게 나타났습니다.',
    bullets: [
      '엇갈린 실적 전망에 따른 기술주와 가치주의 명암',
      '헬스케어·산업재 강세가 이끈 다우 지수 단독 상승',
    ],
  },
  {
    id: 3,
    type: 'comparison',
    turnId: 7,
    title: '업종별 극명한 온도차: 기술주 vs 가치주',
    description: '기술주 섹터는 미래 성장성에 대한 우려로 하락한 반면, 견조한 실물 경제 지표에 힘입어 헬스케어와 산업재 섹터는 상승하며 극명한 대조를 보였습니다.',
    items: [
      {
        label: '기술주 섹터 (XLK)',
        value: '하락 마감',
        description: '미래 전망 우려, 금리 상승 부담 작용',
        highlight: false,
      },
      {
        label: '헬스케어(XLV) / 산업재(XLI)',
        value: '상승 마감',
        description: '견조한 실적과 경제 지표 기반 강세',
        highlight: true,
      },
    ],
    charts: [
      { ticker: 'XLK' },
      { ticker: 'XLV' },
      { ticker: 'XLI' },
    ],
  },
  {
    id: 4,
    type: 'headline',
    turnId: 9,
    title: 'AMD: 기대가 컸던 만큼 실망도 컸다',
    subtitle: '실적 호조에도 가이던스 우려에 17%대 급락',
    description: 'AMD는 4분기 호실적에도 불구하고, 시장의 높은 기대치에 미치지 못하는 1분기 매출 전망을 제시하며 주가가 급락했습니다. 이는 AI 관련주 전반의 투자 심리를 위축시켰습니다.',
    theme: 'red',
    charts: [
      { ticker: 'AMD' },
      { ticker: 'NVDA' },
    ],
  },
  {
    id: 5,
    type: 'headline',
    turnId: 11,
    title: 'Eli Lilly: 기대를 뛰어넘는 실적과 전망',
    subtitle: '강력한 실적과 가이던스로 10% 이상 급등',
    description: '일라이 릴리는 비만 치료제 수요에 힘입어 시장 예상을 뛰어넘는 실적과 연간 전망을 발표했습니다. 이는 헬스케어 섹터 강세와 다우 지수 상승을 이끌었습니다.',
    theme: 'green',
    charts: [
      { ticker: 'LLY' },
      { ticker: 'XLV' },
    ],
  },
  {
    id: 6,
    type: 'stats',
    turnId: 15,
    title: '엇갈린 경제 지표, 시장의 방향성은?',
    description: '부진한 민간 고용 지표와 견조한 서비스업 지표가 동시에 발표되며 시장에 혼재된 신호를 보냈습니다. 투자자들은 거시 경제보다 개별 기업의 펀더멘털에 더욱 집중했습니다.',
    stats: [
      { label: 'ADP 민간 고용', value: '예상 하회', subtext: '경기 둔화 우려', trend: 'down' },
      { label: 'ISM 서비스업 PMI', value: '예상 상회', subtext: '견조한 경제 확인', trend: 'up' },
      { label: '10년물 국채 금리', value: '소폭 상승', subtext: '성장주에 부담', trend: 'neutral' },
    ],
    charts: [
      { ticker: 'TVC:US10Y' },
    ],
  },
  {
    id: 7,
    type: 'ticker-intro',
    turnId: 22,
    ticker: 'AMD',
    companyName: 'Advanced Micro Devices, Inc.',
    currentPrice: 165.8,
    dayChange: -34.2,
    dayChangePercent: -17.1,
    description: 'AMD는 4분기 실적이 예상을 상회했음에도 불구하고, 향후 매출 전망에 대한 우려가 부각되며 주가가 큰 폭으로 하락했습니다.',
    charts: [
      { ticker: 'AMD' },
    ],
  },
  {
    id: 8,
    type: 'ticker-analysis',
    turnId: 23,
    ticker: 'AMD',
    title: '숫자로 본 실적: 무엇이 문제였나?',
    points: [
      '2025년 연간 매출 34% 증가',
      '핵심 동력인 데이터센터 부문 매출 32% 성장',
      '2026년 1분기 매출 전망치도 월가 평균 예상 상회',
    ],
    description: '실적 지표 자체는 훌륭했으나, 그동안 주가를 끌어올렸던 시장의 엄청난 기대감에는 미치지 못했다는 실망감이 주가 하락의 주요 원인으로 분석됩니다.',
    outlook: 'Expectation vs. Reality',
    outlookColor: 'amber',
  },
  {
    id: 9,
    type: 'ticker-analysis',
    turnId: 25,
    ticker: 'AMD',
    title: '수면 위로 드러난 구조적 리스크',
    points: [
      '공급망 리스크: 최첨단 칩 생산을 대만 TSMC 한 곳에 전적으로 의존',
      '중국 시장 의존도: 전체 매출의 22.4%가 중국에서 발생하며, 미-중 규제 리스크에 노출',
      '지정학적 불확실성: 대만 해협 긴장 고조 시 생산 차질 가능성',
    ],
    description: '실적 발표를 계기로 그동안 잠재되어 있던 공급망 및 지정학적 리스크가 부각되면서 투자자들의 우려가 커진 것으로 관찰됩니다.',
    outlook: 'Geopolitical Risks',
    outlookColor: 'rose',
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 27,
    ticker: 'AMD',
    title: '리스크를 상쇄할 기회: OpenAI 파트너십',
    points: [
      'OpenAI와의 대규모 GPU 공급 파트너십 체결',
      '엔비디아가 독점하던 AI 가속기 시장에서의 기술력 입증',
      '향후 수년간 수십억 달러 규모의 안정적인 매출원 확보 가능성',
      'AI PC라는 새로운 시장 선점을 통한 추가 성장 동력',
    ],
    description: '리스크 요인에도 불구하고, OpenAI와의 전략적 파트너십은 AMD가 AI 시장의 핵심 플레이어로 자리매김할 수 있는 중요한 기회 요인으로 평가됩니다.',
    outlook: 'AI Momentum',
    outlookColor: 'purple',
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 29,
    ticker: 'AMD',
    title: '핵심 관전 포인트',
    points: [
      '긍정적 관점: 강력한 펀더멘털과 OpenAI 계약을 바탕으로 현재의 주가 하락이 기회가 될 수 있다는 시각이 존재합니다.',
      '부정적 관점: TSMC 및 중국 관련 리스크는 통제 불가능한 외부 변수로, 기업 안정성을 위협할 수 있다는 우려가 제기됩니다.',
    ],
    description: '향후 주가 방향은 거대한 성장 서사가 지정학적 리스크를 압도할 수 있을지에 대한 시장의 판단에 따라 결정될 것으로 관측됩니다.',
    outlook: 'High Volatility',
    outlookColor: 'blue',
    charts: [
      { ticker: 'AMD' },
    ],
  },
  {
    id: 12,
    type: 'events',
    turnId: 33,
    title: '이번 주 주목할 경제 지표',
    description: '내일 발표될 고용 관련 지표들은 연준의 정책 향방을 가늠할 중요한 단서를 제공할 것입니다.',
    events: [
      {
        date: '2026-02-05',
        label: '주간 신규 실업수당 청구건수',
        description: '예상: 21.2만 건. 고용 시장의 견고함 측정.',
      },
      {
        date: '2026-02-05',
        label: 'JOLTS (구인·이직 보고서)',
        description: '예상: 720만 건. 노동 수요 강도를 보여주는 선행 지표.',
      },
    ],
  },
  {
    id: 13,
    type: 'events',
    turnId: 35,
    title: '다음 주 시장의 분수령: 고용과 물가',
    description: '시장의 모든 관심이 다음 주 발표될 1월 고용보고서와 소비자물가지수(CPI)에 집중되고 있습니다.',
    events: [
      {
        date: '2026-02-11',
        label: '1월 고용보고서 (비농업)',
        description: '예상: 6.8만 명 증가. 고용 시장 안정성 확인.',
      },
      {
        date: '2026-02-13',
        label: '1월 소비자물가지수 (CPI)',
        description: '예상: 전월 대비 0.1% 상승. 인플레이션 둔화세 지속 여부.',
      },
    ],
  },
  {
    id: 14,
    type: 'closing',
    turnId: 37,
    headline: '데이터 의존적 장세, 변동성 대비 필요',
    tagline: '단기적 변동성보다 데이터의 큰 흐름을 읽는 지혜가 필요한 시점',
    description: '다음 주 주요 지표 발표 전까지 시장은 방향성 탐색을 계속할 것으로 보입니다. 섣부른 판단보다는 차분하게 시장 반응을 확인하며 대응하는 전략이 유효해 보입니다.',
  },
];