import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-04-07',
    nutshell: '이란 휴전 기대감에 지정학적 우려 완화',
    description:
      '중동의 지정학적 긴장감이 최고조에 달했음에도 불구하고, 시장은 막판 외교적 노력에 대한 기대감으로 상승 마감했습니다. 오늘 브리핑에서는 시장의 아슬아슬한 낙관론과 월가의 경고, 그리고 AppLovin(APP)에 대한 심층 분석을 다룹니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description:
      '이란과의 협상 마감 시한을 앞두고 휴전 기대감이 부상하며 주요 지수가 상승했습니다. 지정학적 우려 속 달러와 금 등 안전자산도 강세를 보였습니다.',
    indices: [
      { name: 'S&P 500', value: 6611.83, change: 29.14, changePercent: 0.44 },
      { name: 'NASDAQ', value: 21996.34, change: 117.16, changePercent: 0.54 },
      { name: 'DOW', value: 46669.88, change: 165.21, changePercent: 0.36 },
      { name: 'Russell 2000', value: 2540.64, change: 10.60, changePercent: 0.42 },
    ],
    commodities: [
      { name: 'WTI Crude', value: 112.76, change: 1.22, changePercent: 1.09 },
      { name: 'Gold Futures', value: 4677.90, change: 26.40, changePercent: 0.57 },
      { name: 'Dollar Index', value: 99.99, change: -0.04, changePercent: -0.04 },
      { name: '10-Yr Yield', value: 4.35, change: 0.03, changePercent: 0.69 },
    ],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
      { ticker: 'TVC:RUT' },
      { ticker: 'NYMEX:CL1!' },
      { ticker: 'COMEX:GC1!' },
      { ticker: 'TVC:DXY' },
      { ticker: 'TVC:US10Y' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 3,
    icon: 'alert-triangle',
    title: '월가의 경고: 제이미 다이먼의 서한',
    subtitle: '시장의 낙관론 이면에 숨겨진 리스크',
    description:
      '시장의 안도 랠리와는 별개로, 제이피모건 체이스의 제이미 다이먼 CEO는 연례 주주서한을 통해 강력한 경고 메시지를 보냈습니다.',
    bullets: [
      '이란 전쟁 장기화 시 심각한 유가 충격 가능성',
      '고질적인 인플레이션 고착화 우려 제기',
      '시장의 예상보다 더 높은 금리로 이어질 수 있다고 분석',
      '미국 10년물 국채금리 소폭 상승하며 우려 일부 반영',
    ],
    theme: 'amber',
    charts: [{ ticker: 'NYSE:JPM' }, { ticker: 'TVC:US10Y' }],
  },
  {
    id: 3,
    type: 'headline',
    turnId: 7,
    icon: 'trending-up',
    title: '아슬아슬한 낙관론',
    subtitle: '휴전 기대감에 3대 지수 동반 상승',
    description:
      '트럼프 행정부의 이란 최후통첩 시한이 임박했음에도, 시장은 전면전을 피할 수 있을 것이라는 희망에 베팅하며 강세를 보였습니다.',
    bullets: [
      '파키스탄 등 중재국의 막후 협상 소식에 안도감 확산',
      '위험자산 선호 심리 회복되며 3대 지수 일제히 상승',
      'WTI 유가는 장중 $115 돌파 후 $112선으로 안정',
      '에너지 섹터(XLE)는 유가 급등에 힘입어 강세 마감',
    ],
    theme: 'green',
    charts: [{ ticker: 'SP:SPX' }, { ticker: 'AMEX:XLE' }],
  },
  {
    id: 4,
    type: 'stats',
    turnId: 9,
    title: '전면전을 막기 위한 막판 외교',
    description:
      '최후통첩 시한을 앞두고 복수의 외신을 통해 중재국들의 적극적인 외교적 노력이 전해지며 투자 심리를 되살렸습니다.',
    stats: [
      { label: '중재 주도국', value: '파키스탄', subtext: '미국-이란 양측에 계획안 전달' },
      { label: '협력 국가', value: '이집트, 터키', subtext: '중동 국가들의 외교적 해결 노력' },
      { label: '핵심 제안', value: '45일 임시 휴전', subtext: '추가 협상을 위한 시간 확보 목적' },
    ],
    note: '이란은 항구적인 전쟁 종식을 원한다고 밝혀 여전히 입장 차는 존재합니다.',
  },
  {
    id: 5,
    type: 'headline',
    turnId: 11,
    icon: 'ship',
    title: '숨겨진 위험: 호르무즈 해협 봉쇄',
    subtitle: '이란의 강력한 압박 카드, 유가 충격 촉발',
    description:
      '시장의 낙관론 이면에는 이란의 호르무즈 해협 봉쇄라는 가장 큰 위험 요인이 자리 잡고 있습니다. 이는 협상 결렬 시 시장을 다시 흔들 수 있는 뇌관입니다.',
    bullets: [
      '전 세계 원유 해상 수송량의 약 20%가 통과하는 핵심 길목',
      '이란의 통행 봉쇄 조치에 국제 유가 장중 $115 돌파',
      'JPM 경고: 장기화 시 美 휘발유 가격 갤런당 $5 초과 가능',
      '인플레이션 압력으로 이어져 경제 전반에 큰 부담',
    ],
    theme: 'red',
    charts: [{ ticker: 'NYMEX:CL1!' }],
  },
  {
    id: 6,
    type: 'comparison',
    turnId: 13,
    title: '시장의 기대 vs 월가의 경고',
    description:
      '시장은 휴전 가능성에 베팅하며 안도 랠리를 보였지만, 제이피모건의 제이미 다이먼은 정반대의 어두운 시나리오를 제시하며 시장의 이면에 도사린 리스크를 상기시켰습니다.',
    items: [
      {
        label: '시장의 시각',
        value: '안도 랠리',
        description: '외교적 해법 도출 및 휴전 타결 기대. 지정학적 리스크 완화에 베팅.',
        highlight: false,
      },
      {
        label: '제이미 다이먼의 경고',
        value: '스태그플레이션',
        description: '전쟁 장기화 시 유가/원자재 충격, 고질적 인플레이션, 더 높은 금리 가능성 경고.',
        highlight: true,
      },
      {
        label: '혼재된 신호',
        value: '주가↑, 채권금리↑',
        description: '주식시장은 낙관론을, 채권/원자재 시장은 잠재된 리스크를 반영.',
        highlight: false,
      },
    ],
  },
  {
    id: 7,
    type: 'stats',
    turnId: 15,
    title: '다이먼의 경고: 구체적 수치',
    description:
      '제이미 다이먼은 연례 주주서한에서 현재 시장이 너무 낙관적인 시나리오에만 치우쳐 있다며, 구체적인 수치를 통해 잠재적 위험의 크기를 경고했습니다.',
    stats: [
      { label: '잠재적 금리', value: '8% 이상', subtext: '시장 예상(2~3%)과 큰 괴리', trend: 'up' },
      { label: '최악의 유가 시나리오', value: '$150/bbl', subtext: '이란과의 전쟁 장기화 시', trend: 'up' },
      { label: '양적 긴축(QT) 규모', value: '연간 $1조', subtext: '예측 불가능한 파급 효과', trend: 'down' },
    ],
    note: '그의 경고 이후 10년물 국채금리는 소폭 상승하며 시장의 불안감을 자극했습니다.',
    theme: 'red',
    charts: [{ ticker: 'TVC:US10Y' }, { ticker: 'TVC:VIX' }],
  },
  {
    id: 8,
    type: 'headline',
    turnId: 19,
    icon: 'shield-alert',
    title: '지정학적 리스크, 그 너머',
    subtitle: '다이먼이 지적한 금융 시스템의 잠재적 위험',
    description:
      '다이먼의 경고는 이란 사태에만 국한되지 않았습니다. 그는 현재 금융 시스템이 직면한 다양한 구조적 위험 요소를 지적하며 더 큰 그림을 볼 것을 주문했습니다.',
    bullets: [
      '인공지능(AI)이 가져올 고용 시장의 구조적 변화',
      '규제받지 않는 사모 신용(Private Credit) 시장의 급성장',
      '막대한 정부 재정 지출과 팬데믹 저축 효과 소멸',
      '양적 긴축(QT)의 예측 불가능한 파급 효과',
    ],
    theme: 'purple',
  },
  {
    id: 9,
    type: 'ticker-intro',
    turnId: 20,
    ticker: 'APP',
    companyName: 'AppLovin',
    currentPrice: 412.68,
    dayChange: 26.31,
    dayChangePercent: 6.81,
    description:
      '특별한 개별 뉴스 없이 5% 이상 급등 마감했습니다. 시장은 앱러빈을 단순 광고 기술 기업이 아닌, AI 플랫폼 기업으로 재평가하는 모습입니다.',
    charts: [{ ticker: 'NASDAQ:APP' }],
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 21,
    ticker: 'APP',
    title: '성장 동력: AI 플랫폼 기업으로의 재평가',
    points: [
      '2025년 연간 매출 전년 대비 약 70% 증가',
      '영업활동 현금흐름 89% 급증 ($39.7억)',
      'AI 엔진 \'액손 2.0\'이 설치당 순매출(ARPIN) 72% 향상',
      '폭발적인 성장을 실적으로 증명하며 기술적 해자 부각',
    ],
    outlook: 'AI 기반의 강력한 펀더멘털',
    outlookColor: 'emerald',
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 23,
    ticker: 'APP',
    title: '핵심 리스크: 통제 불가능한 플랫폼 종속성',
    points: [
      '사업 모델이 전적으로 애플(iOS)과 구글(Android) 플랫폼에 의존',
      '플랫폼의 개인정보보호 정책 변경 시 AI 타겟팅 효율성 무력화 가능',
      '사업의 존립을 위협하는 구조적 취약점 (10-K 보고서 명시)',
      '신사업(CTV, 이커머스) 다각화는 아직 내러티브 단계, 재무적 기여도 미미',
    ],
    outlook: '구조적 취약점이 모든 성과를 위협',
    outlookColor: 'rose',
  },
  {
    id: 12,
    type: 'ticker-analysis',
    turnId: 27,
    ticker: 'APP',
    title: '기타 잠재적 위험 요인',
    points: [
      '증권 집단 소송: 현재 진행 중인 소송으로, 잠재적 손실 범위 추정 불가에 따른 우발 부채 가능성 존재.',
      '과거 M&A 이력: 과거 인수한 \'앱스(Apps)\' 사업부 관련 $1.88억의 영업권 손상차손 인식 이력.',
      '자본 배분 결정: 과거의 자본 배분 결정이 항상 성공적이지 않았음을 시사.',
    ],
    description: '화려한 성장 지표 이면에 숨겨진 재무적, 법적 리스크를 점검할 필요가 있습니다.',
    outlook: '성장 서사에 가려진 리스크 점검 필요',
    outlookColor: 'amber',
  },
  {
    id: 13,
    type: 'headline',
    turnId: 31,
    icon: 'dollar-sign',
    title: '강한 고용, 매파적 연준',
    subtitle: '금리 인하 기대감 위축, 시장 숨 고르기',
    description:
      '예상보다 강력한 고용 지표와 연준 인사의 매파적 발언이 맞물리며, 경제가 너무 강한 것이 오히려 금리 인하의 발목을 잡는 딜레마가 연출되었습니다.',
    bullets: [
      '3월 비농업 고용, 시장 예상치를 크게 상회하며 경제 견조함 증명',
      '견조한 경제가 인플레이션 둔화 지연 우려로 연결',
      '닐 카시카리 연은 총재, "금리 인하 불필요할 수도" 강경 발언',
      '시장의 관심은 다시 연준의 금리 경로와 물가 데이터로 집중',
    ],
    theme: 'blue',
  },
  {
    id: 14,
    type: 'events',
    turnId: 33,
    title: '이번 주 주목할 경제 지표',
    description:
      '다음 주는 연준의 금리 정책 향방을 결정할 중요한 인플레이션 데이터가 연이어 발표되어 시장의 단기 방향성을 결정할 분수령이 될 전망입니다.',
    events: [
      {
        date: '4/10 (수)',
        label: '3월 소비자물가지수 (CPI)',
        description: '6월 금리 인하 기대감의 향방을 결정할 핵심 지표',
      },
      {
        date: '4/11 (목)',
        label: '3월 생산자물가지수 (PPI)',
        description: '소비자 물가의 선행 지표로 인플레이션 압력 판단 단서',
      },
      {
        date: '4/11 (목)',
        label: '3월 FOMC 의사록 공개',
        description: '금리 경로에 대한 연준 위원들의 내부 논의 확인',
      },
    ],
  },
  {
    id: 15,
    type: 'closing',
    turnId: 36,
    headline: '인플레이션 데이터가 결정할 시장의 향방',
    tagline: '4월 7일 장마감 브리핑',
    description:
      '이란 관련 지정학적 리스크와 제이미 다이먼의 경고가 공존하는 가운데, 시장의 시선은 다음 주 발표될 CPI와 PPI 데이터에 집중되고 있습니다. 감사합니다.',
  },
];