import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-04-21',
    nutshell: '지정학적 리스크 부각에 따른 유가 급등과 시장 혼조',
    description: '중동의 지정학적 리스크가 유가를 끌어올리며 시장에 혼조세를 가져왔습니다. 유가 급등 속에서 에너지 섹터는 강세를 보인 반면 기술주는 약세를 보이는 등 뚜렷한 차별화 장세가 나타났습니다. 오늘 브리핑에서는 시장의 주요 동향과 함께 보스턴 사이언티픽(BSX)을 심층 분석합니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '지정학적 리스크 부각에 따른 유가 급등으로 주요 지수가 혼조세를 보였습니다. 대형주와 기술주는 하락했으나, 에너지주가 강세를 보인 중소형주 지수는 상승 마감했습니다.',
    indices: [
      { name: 'S&P 500', value: 7109.14, change: -16.92, changePercent: -0.24 },
      { name: 'NASDAQ', value: 24404.39, change: -64.09, changePercent: -0.26 },
      { name: 'Dow Jones', value: 49442.56, change: -4.87, changePercent: -0.01 },
      { name: 'Russell 2000', value: 2792.96, change: 16.06, changePercent: 0.58 },
    ],
    commodities: [
      { name: 'WTI Crude', value: 85.89, change: 2.04, changePercent: 2.43 },
      { name: 'Dollar Index', value: 98.05, change: -0.05, changePercent: -0.05 },
      { name: 'Gold Futures', value: 4841.00, change: -16.60, changePercent: -0.34 },
    ],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
      { ticker: 'TVC:RUT' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 3,
    icon: 'alert-triangle',
    title: '중동 지정학적 리스크 부상',
    subtitle: '미-이란 갈등 고조와 유가 급등',
    description: '주말 사이 미국이 이란 선박을 나포했다는 소식이 전해지면서 호르무즈 해협을 둘러싼 긴장이 고조, 유가를 끌어올리며 시장 전반에 영향을 미쳤습니다.',
    bullets: [
      '미 해군, 이란 선박 나포 소식에 긴장감 고조',
      '이란, 세계 원유 수송 길목 호르무즈 해협 통제 맞대응',
      '유가 급등이 인플레이션 우려를 자극하며 기술주에 부담',
      '에너지 기업은 유가 상승 수혜를 입으며 중소형주 지수 상승 견인',
    ],
    theme: 'amber',
  },
  {
    id: 3,
    type: 'stats',
    turnId: 7,
    title: '리스크 부각에 따른 시장 지표 변화',
    description: '호르무즈 해협을 둘러싼 긴장감은 원유 시장을 중심으로 주요 금융 지표의 변동성을 키웠습니다.',
    stats: [
      { label: 'WTI 유가 (장중)', value: '+6% 이상', subtext: '배럴당 $89 돌파', trend: 'up' },
      { label: '브렌트유', value: '$97선 위협', subtext: '공급 차질 우려 반영', trend: 'up' },
      { label: 'VIX 지수', value: '19 후반', subtext: '시장 불안감 증대', trend: 'up' },
      { label: '10년물 국채금리', value: '4.25% 수준', subtext: '복잡한 시장 심리 반영', trend: 'neutral' },
    ],
    theme: 'amber',
    charts: [
      { ticker: 'CL=F', title: 'WTI Crude Oil' },
      { ticker: 'BZ=F', title: 'Brent Crude Oil' },
      { ticker: 'TVC:VIX', title: 'Volatility Index' },
      { ticker: 'TVC:US10Y', title: 'US 10-Year Yield' },
    ],
  },
  {
    id: 4,
    type: 'headline',
    turnId: 9,
    icon: 'ship',
    title: '호르무즈 해협의 중요성',
    subtitle: '글로벌 원유 공급의 핵심 길목',
    description: '호르무즈 해협은 전 세계 원유 및 LNG 수송의 전략적 요충지로, 이곳의 지정학적 리스크는 글로벌 에너지 시장과 경제 전반에 직접적인 영향을 미칩니다.',
    bullets: [
      '전 세계 해상 원유 수송량의 약 20% 통과',
      '액화천연가스(LNG) 수송량의 1/3 담당',
      '해협 봉쇄 시 막대한 공급 차질 및 유가 폭등 가능성',
      '에너지 섹터(XLE) 강세로 S&P 500 지수 하락폭 일부 제한',
    ],
    theme: 'blue',
    charts: [
      { ticker: 'XLE', title: 'Energy Select Sector SPDR Fund' },
      { ticker: 'XOM', title: 'Exxon Mobil Corp' },
    ],
  },
  {
    id: 5,
    type: 'stats',
    turnId: 11,
    title: '견조한 소비와 인플레이션 딜레마',
    description: '유가 급등 상황에서 발표된 견조한 소매판매 지표는 경제 펀더멘털에 대한 긍정적 신호인 동시에 인플레이션 압력을 높이는 요인으로 작용했습니다.',
    stats: [
      { label: '3월 소매판매', value: '증가세', subtext: '견조한 소비 여력 시사', trend: 'up' },
      { label: '경제 펀더멘털', value: '강세', subtext: '긍정적 신호로 해석 가능', trend: 'up' },
      { label: '인플레이션 압력', value: '증폭', subtext: '유가 상승과 맞물려 우려 심화', trend: 'up' },
      { label: '연준의 고민', value: '가중', subtext: '견조한 소비 + 공급 충격 동시 직면', trend: 'neutral' },
    ],
    note: '크리스토퍼 월러 연준 이사는 통화정책에 대한 직접적인 발언은 아꼈습니다.',
    theme: 'gold',
  },
  {
    id: 6,
    type: 'comparison',
    turnId: 15,
    title: '유가 급등에 따른 섹터별 희비',
    description: '중동발 유가 쇼크라는 단일 변수에 대해 시장은 수혜 업종과 피해주를 극명하게 나누는 차별화 장세를 보였습니다.',
    items: [
      {
        label: '에너지 (XLE)',
        value: '상승',
        description: '유가 상승의 직접적 수혜, 러셀 2000 지수 상승 견인',
        highlight: true,
      },
      {
        label: '기술주 (XLK)',
        value: '하락',
        description: '인플레이션 및 금리 우려로 밸류에이션 부담 가중',
        highlight: false,
      },
      {
        label: '유틸리티 (XLU)',
        value: '하락',
        description: '대표적인 금리 민감 업종으로 0.8% 이상 하락',
        highlight: false,
      },
    ],
    charts: [
      { ticker: 'XLE', title: 'Energy Sector' },
      { ticker: 'XLK', title: 'Technology Sector' },
      { ticker: 'XLU', title: 'Utilities Sector' },
    ],
  },
  {
    id: 7,
    type: 'headline',
    turnId: 19,
    icon: 'compass',
    title: '향후 시장 전망 및 주요 관전 포인트',
    subtitle: '중동 리스크와 경제 지표에 쏠린 시선',
    description: '단기적으로 시장의 모든 시선은 중동의 지정학적 리스크와 핵심 경제 지표에 집중될 것입니다. 이 두 가지 변수가 향후 유가와 시장의 방향성을 결정할 전망입니다.',
    bullets: [
      '중동 휴전 시한 만료가 단기 변동성의 최대 분수령',
      '2차 평화 회담 성사 여부가 유가 향방 결정',
      '소매판매 등 경제 지표를 통해 소비 건전성 및 인플레 압력 확인',
      '핵심 지표들은 연준의 향후 정책 결정에 중요한 단서 제공',
    ],
    theme: 'blue',
  },
  {
    id: 8,
    type: 'ticker-intro',
    turnId: 20,
    ticker: 'BSX',
    companyName: 'Boston Scientific',
    currentPrice: 60.99,
    dayChange: -3.24,
    dayChangePercent: -5.04,
    description: '보스턴 사이언티픽은 장 초반의 상승세를 지키지 못하고 5% 넘게 하락하며 60달러 선에서 마감, 하루 종일 약세를 보였습니다.',
    charts: [{ ticker: 'BSX' }],
  },
  {
    id: 9,
    type: 'ticker-analysis',
    turnId: 21,
    ticker: 'BSX',
    title: '성장 잠재력: 혁신 기술의 동력',
    points: [
      '전기생리학 부문 FARAPULSE 시스템의 폭발적 성장',
      '해당 시스템 매출, 전년 대비 74.6% 증가',
      '강력한 혁신 기술의 가치와 성장성에 대한 시장 기대감 존재',
      '성장 잠재력과 재무 리스크가 극명하게 충돌하는 상황',
    ],
    description: '보스턴 사이언티픽은 FARAPULSE 시스템과 같은 혁신 기술을 바탕으로 강력한 성장 동력을 보여주고 있습니다.',
    outlook: '높은 성장 기대감 이면에 재무적 리스크가 공존하고 있습니다.',
    outlookColor: 'amber',
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 23,
    ticker: 'BSX',
    title: '재무 리스크: 공격적 M&A의 그림자',
    points: [
      '145억 달러 규모 페넘브라 인수 추진에 따른 재무 부담',
      '인수 후 총 부채 약 224억 달러까지 급증 예상',
      '영업권(Goodwill) 300억 달러 육박 (총자산의 50% 이상)',
      '인수 시너지 실패 시 대규모 영업권 상각으로 주주가치 훼손 위험',
    ],
    description: '시장은 회사의 공격적인 인수합병 전략에서 비롯된 재무적 부담 증가를 우려하고 있습니다.',
    outlook: '과도한 재무 레버리지가 잠재적 위험 요인으로 부각되고 있습니다.',
    outlookColor: 'rose',
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 25,
    ticker: 'BSX',
    title: '구조적 취약점: IP 소송 리스크',
    points: [
      '지적재산권(IP) 소송에 대한 \'완전 자가보험\' 정책',
      '패소 시 보험사 보호 없이 막대한 배상금을 직접 부담해야 함',
      '최근 텍사스 대학과의 소송에서 4,200만 달러 배심원 평결 사례 발생',
      '예측 불가능한 단 한 번의 대규모 패소가 현금흐름에 치명타 가능',
    ],
    description: '회사의 독특한 \'완전 자가보험\' 정책은 예측 불가능한 법적 리스크를 야기하며 투자 심리를 위축시키고 있습니다.',
    outlook: '현금흐름을 위협할 수 있는 구조적 리스크가 현실화될 수 있다는 우려가 존재합니다.',
    outlookColor: 'rose',
  },
  {
    id: 12,
    type: 'headline',
    turnId: 27,
    title: '보스턴 사이언티픽 종합 평가',
    subtitle: '기대에서 공포로, 리스크 부각',
    description: '오늘 주가 급락은 시장의 관점이 보스턴 사이언티픽의 성장 기대감에서 재무 및 소송 리스크에 대한 우려로 급격히 전환되었음을 보여줍니다.',
    bullets: [
      '시장의 관점: \'성장 기대\' → \'부채/소송 공포\'로 전환',
      '혁신 기술의 가치 vs 재무적 레버리지 및 법적 리스크',
      '현재 주가, 복합 리스크를 충분히 반영하지 못했다는 평가 제기',
      '가시적인 리스크 관리가 필요한 시점이라는 인식 확산',
    ],
    theme: 'amber',
    charts: [{ ticker: 'BSX' }],
  },
  {
    id: 13,
    type: 'events',
    turnId: 31,
    title: '이번 주 주요 경제 지표',
    description: '이번 주 목요일에 발표될 S&P 글로벌 PMI 예비치는 제조업과 서비스업 경기를 가장 빠르게 예측해볼 수 있는 선행 지표로 시장의 주목을 받고 있습니다.',
    events: [
      { date: '2026-04-23', label: 'S&P 글로벌 제조업 PMI (예비치)', description: '시장 예상 52.5, 경기 확장 및 인플레 압력 동시 확인' },
      { date: '2026-04-23', label: 'S&P 글로벌 서비스업 PMI (예비치)', description: '미국 경제의 대부분을 차지하는 서비스업 경기 동향 파악' },
      { date: '2026-04-23', label: 'S&P 글로벌 종합 PMI (예비치)', description: '제조업과 서비스업을 종합하여 경제 전반의 활동 측정' },
    ],
  },
  {
    id: 14,
    type: 'events',
    turnId: 33,
    title: '다음 주 빅 이벤트: FOMC & PCE',
    description: '다음 주는 4월의 하이라이트로, FOMC 금리 결정과 PCE 물가 지표 발표가 예정되어 있어 향후 시장 방향을 결정지을 가장 중요한 변수가 될 것입니다.',
    events: [
      { date: '2026-04-29', label: 'FOMC 금리 결정', description: '금리 동결 예상, 성명서 및 기자회견 내용에 관심 집중' },
      { date: '2026-04-30', label: '개인소비지출(PCE) 가격지수', description: '연준이 가장 중요하게 여기는 핵심 물가 지표' },
    ],
  },
  {
    id: 15,
    type: 'closing',
    turnId: 35,
    headline: '관망세 속 변동성 확대 주의',
    tagline: '경제 지표를 확인하며 신중한 접근이 필요한 시점',
    description: '금리 인상 정점 기대감과 경기 침체 우려가 공존하는 줄다리기 장세입니다. 특히 다음 주 FOMC와 PCE 발표 전까지 변동성이 커질 수 있으므로, 보수적인 관점에서 시장에 접근하는 지혜가 필요합니다.',
  },
];