import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-02-06',
    nutshell: '기업 호실적과 소비 심리 개선에 힘입은 전방위적 랠리',
    description: '아마존의 대규모 투자 계획 발표로 인한 초기 우려에도 불구하고, 시장 전반에 걸친 견조한 기업 실적과 예상치를 상회한 소비 심리 지표가 투자 심리를 끌어올리며 3대 지수 모두 강한 상승세로 마감했습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '기업들의 광범위한 실적 호조와 긍정적인 경제 지표에 힘입어 3대 지수 모두 2% 내외의 강한 상승률을 기록하며 전방위적인 랠리를 보였습니다.',
    indices: [
      { name: 'S&P 500', value: 7035.12, change: 136.59, changePercent: 1.97 },
      { name: 'NASDAQ', value: 24155.80, change: 516.57, changePercent: 2.18 },
      { name: 'DOW', value: 50210.44, change: 1215.11, changePercent: 2.47 },
    ],
    commodities: [
      { name: 'WTI Crude', value: 81.15, change: 3.25, changePercent: 4.17 },
      { name: '10-Yr Yield', value: 4.20, change: 0.00, changePercent: 0.00 },
    ],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 6,
    icon: 'trending-up',
    title: '견조한 기업 실적',
    subtitle: '빅테크 우려를 잠재운 광범위한 랠리',
    description: '아마존의 주가 하락에도 불구하고, 기술, 산업재, 헬스케어 등 다양한 섹터에서 발표된 긍정적인 기업 실적이 시장의 저변이 탄탄하다는 것을 증명하며 투자 심리를 견인했습니다.',
    bullets: [
      'S&P 500 1.97%, 다우존스 2.47% 급등',
      '공포지수(VIX) 18% 급락하며 투자 심리 안정',
      '포티넷(FTNT), 로블록스(RBLX) 등 호실적 발표로 급등',
      '캐터필러(CAT), 일라이 릴리(LLY) 등 비기술주도 랠리 동참',
    ],
    theme: 'green',
  },
  {
    id: 3,
    type: 'stats',
    turnId: 7,
    title: '시장의 자신감 회복 신호',
    description: '주요 시장 지표들이 일제히 긍정적인 방향으로 움직이며 위험자산 선호 심리가 크게 개선되었습니다.',
    stats: [
      { label: 'VIX 지수', value: '-18.3%', subtext: '투자 심리 급격히 안정', trend: 'down' },
      { label: 'S&P 500', value: '+1.97%', subtext: '광범위한 상승세', trend: 'up' },
      { label: 'WTI 유가', value: '+4.17%', subtext: '경제 수요 회복 기대', trend: 'up' },
      { label: '10년물 국채금리', value: '4.2%', subtext: '안정세 유지', trend: 'neutral' },
    ],
    theme: 'green',
    charts: [
      { ticker: 'TVC:VIX' },
      { ticker: 'TVC:US10Y' },
    ],
  },
  {
    id: 4,
    type: 'headline',
    turnId: 9,
    title: '랠리의 확산: 기술주를 넘어서',
    subtitle: '산업재, 헬스케어 섹터의 동반 강세',
    description: '이번 랠리는 특정 기술주에 국한되지 않고 경제의 근간을 이루는 여러 섹터로 확산되며 시장의 체력이 전반적으로 강하다는 것을 보여주었습니다.',
    bullets: [
      '캐터필러(CAT): 예상을 뛰어넘는 실적으로 주가 7% 이상 급등',
      '일라이 릴리(LLY): 견조한 실적을 바탕으로 3.6% 이상 상승',
      '미국 경제가 소수 빅테크에 의존하지 않는다는 확신 증대',
    ],
    theme: 'green',
    charts: [
      { ticker: 'CAT', title: 'Caterpillar Inc.' },
      { ticker: 'LLY', title: 'Eli Lilly and Company' },
    ],
  },
  {
    id: 5,
    type: 'headline',
    turnId: 14,
    icon: 'users',
    title: '강력한 소비 심리',
    subtitle: '경제 연착륙 기대감 증폭',
    description: '예상치를 크게 웃돈 미시간대 소비자심리지수는 미국 경제의 3분의 2를 차지하는 소비가 견고함을 증명하며 경제 연착륙 시나리오에 대한 신뢰를 높였습니다.',
    bullets: [
      '2월 소비자심리지수 57.3 기록 (예상 53.0, 전월 56.4)',
      '견고한 소비가 기업 이익 전망을 뒷받침하며 주식 시장에 긍정적 환경 제공',
      '연준의 금리 인하가 늦춰지더라도 경제가 충격을 흡수할 수 있다는 자신감 확산',
    ],
    theme: 'blue',
  },
  {
    id: 6,
    type: 'stats',
    turnId: 15,
    title: '미시간 소비자심리지수 서프라이즈',
    description: '2월 소비자심리지수 예비치가 시장 예상과 전월 수치를 모두 크게 상회하며, 인플레이션 압박 속에서도 소비자들이 긍정적인 경기 전망을 유지하고 있음을 보여주었습니다.',
    stats: [
      { label: '발표치', value: '57.3', subtext: '2월 예비치', trend: 'up' },
      { label: '예상치', value: '53.0', subtext: '시장 컨센서스', trend: 'neutral' },
      { label: '이전치', value: '56.4', subtext: '1월 확정치', trend: 'neutral' },
    ],
    note: '견고한 소비는 경제 연착륙 시나리오의 핵심 근거로 작용합니다.',
    theme: 'blue',
  },
  {
    id: 7,
    type: 'stats',
    turnId: 17,
    title: '소비자 자신감의 원천: 견고한 경제 지표',
    description: '최근 발표된 고용 및 서비스업 관련 지표들이 미국 경제의 펀더멘털이 튼튼하다는 점을 뒷받침하며 소비자들의 자신감으로 이어지고 있습니다.',
    stats: [
      { label: 'JOLTS 구인 건수', value: '강세', subtext: '팬데믹 이전 수준 상회', trend: 'up' },
      { label: '신규 실업수당 청구', value: '낮음', subtext: '역사적으로 낮은 수준 유지', trend: 'up' },
      { label: 'ISM 서비스업 PMI', value: '확장', subtext: '경제의 허리 튼튼', trend: 'up' },
    ],
    theme: 'blue',
  },
  {
    id: 8,
    type: 'headline',
    turnId: 19,
    title: '연준의 신중론',
    subtitle: '강한 경제가 금리 인하 시점을 늦출까?',
    description: '강력한 경제 지표는 연준이 금리 인하를 서두를 필요가 없다는 근거로 작용할 수 있습니다. 시장은 연준의 신중한 태도를 가격에 반영하기 시작했습니다.',
    bullets: [
      '제퍼슨 연준 부의장, 금리 인하 기준이 높아졌음을 시사',
      '섣부른 금리 인하가 인플레이션을 재자극할 수 있다는 경계심 유지',
      '단기 정책금리에 민감한 2년물 국채 금리 소폭 상승',
    ],
    theme: 'gold',
    charts: [{ ticker: 'TVC:US02Y' }],
  },
  {
    id: 9,
    type: 'ticker-intro',
    turnId: 22,
    ticker: 'AMZN',
    companyName: 'Amazon.com, Inc.',
    currentPrice: 198.45,
    dayChange: -11.55,
    dayChangePercent: -5.50,
    description: '견조한 4분기 실적에도 불구하고, 2,000억 달러에 달하는 대규모 자본 지출 계획이 단기 수익성 악화 우려를 낳으며 주가가 큰 폭으로 하락했습니다.',
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 23,
    ticker: 'AMZN',
    title: '단기적 리스크: 전례 없는 투자 규모',
    points: [
      '2026년 한 해 2,000억 달러의 자본 지출(Capex) 계획 발표',
      '단기적인 잉여현금흐름(FCF)이 큰 폭의 마이너스로 전환될 수 있다는 우려 제기',
      'AI 군비 경쟁이 자본수익률을 저해하는 \'승자의 저주\'가 될 수 있다는 시장의 공포',
    ],
    description: '시장은 아마존의 전례 없는 투자 규모가 단기적인 재무 건전성에 미칠 부담에 주목하며 극도의 경계심을 보이고 있습니다.',
    outlook: 'Margin Pressure',
    outlookColor: 'amber',
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 25,
    ticker: 'AMZN',
    title: '장기적 기회: AWS 성장 가속화',
    points: [
      'AWS 매출 성장률이 19%에서 20%로 다시 가속화되고 있는 점이 확인됨',
      '이번 투자는 불확실성에 대한 베팅이 아닌, 폭발하는 AI 수요에 대응하기 위한 필연적 확장으로 분석',
      '과거 AWS 초기 투자와 같이, 현재의 투자가 미래 이익의 핵심 동력이 될 수 있다는 기대 존재',
    ],
    description: '시장의 단기적 공포와 달리, 이번 투자는 이미 검증된 AWS의 성장세에 대응하기 위한 전략적 확장이라는 긍정적 해석이 가능합니다.',
    outlook: 'Growth Catalyst',
    outlookColor: 'emerald',
  },
  {
    id: 12,
    type: 'ticker-analysis',
    turnId: 27,
    ticker: 'AMZN',
    title: '핵심 경쟁력: 독자적인 AI 생태계',
    points: [
      '자체 설계 AI 칩(트레이니엄, 그래비톤)을 통해 비용 우위와 높은 마진 확보 가능',
      '개발자 플랫폼 베드락(Bedrock)을 통해 강력한 고객 락인(Lock-in) 효과 창출',
      '단순 인프라 경쟁을 넘어 하드웨어와 소프트웨어를 아우르는 수직 계열화로 기술적 해자(Moat) 구축',
    ],
    description: '아마존의 투자는 단순한 규모의 경쟁을 넘어, 자체 칩과 플랫폼을 기반으로 한 독자적인 생태계를 구축하여 질적인 차별화를 추구하고 있습니다.',
    outlook: 'Deep Tech Moat',
    outlookColor: 'purple',
  },
  {
    id: 13,
    type: 'ticker-analysis',
    turnId: 29,
    ticker: 'AMZN',
    title: '종합 분석: 단기 비용 vs. 장기 비전',
    points: [
      '단기적 재무 압박과 시장의 공포는 실재하는 리스크로, 향후 주가 변동성 확대가 예상됨',
      '시장의 공포가 AWS 성장 가속화와 자체 생태계 구축이라는 장기적 잠재력을 과도하게 할인하고 있다는 분석 제기',
      '현재 주가는 단기적 비용 우려를 반영하고 있으나, 장기적으로는 AI 시대의 핵심 인프라 자산 가치를 따라갈 가능성이 있다는 관점 존재',
    ],
    description: '현재 아마존은 단기적인 재무 리스크와 AI 시대 인프라를 선점하려는 장기적 비전이 충돌하는 모습을 보이고 있습니다. 리스크 관리와 함께 장기적 관점에서의 접근이 필요한 시점으로 관찰됩니다.',
    outlook: 'Strategic Crossroads',
    outlookColor: 'blue',
  },
  {
    id: 14,
    type: 'events',
    turnId: 33,
    title: '향후 주요 이벤트',
    description: '시장은 앞으로 발표될 주요 경제 지표와 연준의 의사록을 통해 향후 통화정책 방향에 대한 힌트를 찾으려 할 것입니다.',
    events: [
      {
        date: '2026-02-13',
        label: '소비자물가지수 (CPI) 발표',
        description: '연준의 금리 인하 시점 결정을 위한 가장 중요한 지표. 인플레이션 둔화세 지속 여부가 관건입니다.',
      },
      {
        date: '2026-02-18',
        label: 'FOMC 의사록 공개',
        description: '지난 회의에서의 금리 인하 조건 및 경제 전망에 대한 위원들의 상세한 논의를 파악할 수 있습니다.',
      },
    ],
  },
  {
    id: 15,
    type: 'closing',
    turnId: 37,
    headline: '데이터에 따라 움직이는 시장',
    tagline: '인플레이션과 고용의 큰 흐름을 주시해야 할 때',
    description: '당분간 시장은 주요 경제 지표 발표에 따라 변동성이 커질 수 있습니다. 단기적 반응보다는 인플레이션과 고용 시장의 추세를 관찰하며 신중하게 대응하는 전략이 유효한 시점입니다.',
  },
];