import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-03-04',
    nutshell: '중동 지정학적 리스크와 유가 급등에 따른 인플레이션 우려 부각',
    description: '3월 4일 장마감 브리핑입니다. 중동의 지정학적 리스크가 유가 급등을 촉발하며 시장 전반에 인플레이션 우려를 확산시켰습니다. 3대 지수 모두 하락 마감했습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '3대 지수는 중동 리스크와 유가 급등에 따른 인플레이션 우려로 모두 하락했습니다. WTI 유가는 4% 넘게 급등했고, 10년물 국채금리 또한 상승하며 시장에 부담을 주었습니다. 지정학적 불안감에 안전자산인 달러와 금 가격은 상승했습니다.',
    indices: [
      { name: 'S&P 500', value: 6816.63, change: -64.99, changePercent: -0.94 },
      { name: 'NASDAQ', value: 22516.69, change: -232.17, changePercent: -1.02 },
      { name: 'DOW', value: 48501.27, change: -403.51, changePercent: -0.83 },
      { name: 'Russell 2000', value: 2608.36, change: -47.58, changePercent: -1.79 },
    ],
    commodities: [
      { name: 'WTI Crude (CL=F)', value: 74.92, change: 3.69, changePercent: 5.18 },
      { name: '10-Yr Yield', value: 4.251, change: 0.052, changePercent: 1.24 },
      { name: 'Dollar Index', value: 99.07, change: 0.69, changePercent: 0.70 },
      { name: 'Gold Futures', value: 5100.80, change: -193.60, changePercent: -3.66 },
    ],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
      { ticker: 'TVC:RUT' },
      { ticker: 'TVC:US10Y' },
      { ticker: 'CL=F' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 6,
    icon: 'alert-triangle',
    title: '시장을 짓누른 두 가지 악재',
    subtitle: '유가 급등 & 고금리 장기화 우려',
    description: '이란과의 군사 충돌로 인한 유가 급등과 예상보다 강한 서비스업 지표가 맞물리면서, 시장은 인플레이션과 그에 따른 연준의 고금리 장기화 가능성을 동시에 우려하기 시작했습니다.',
    bullets: [
      '이란 군사 충돌 격화, 호르무즈 해협 운송 마비 우려',
      'WTI 유가 4% 이상 급등, 인플레이션 압력 가중',
      'ISM 서비스업 PMI 예상 상회, 견조한 경제 확인',
      '\'강한 경제 + 유가 쇼크\' 조합, 연준 고금리 유지 명분 강화',
    ],
    theme: 'red',
  },
  {
    id: 3,
    type: 'headline',
    turnId: 9,
    icon: 'ship',
    title: '호르무즈 해협 봉쇄',
    subtitle: '실질적 공급망 마비, 유가 폭등 촉발',
    description: '이란 혁명수비대가 전 세계 원유 수송량의 약 20%가 통과하는 호르무즈 해협의 폐쇄를 선언하고 유조선 피격 영상까지 공개되면서, 유가가 폭등하고 증시는 급락했습니다.',
    bullets: [
      '이란, 전 세계 원유 20% 통과하는 호르무즈 해협 폐쇄 선언',
      '유조선 피격 영상 공개로 해상 운송 사실상 중단',
      'WTI 장중 9% 폭등, 브렌트유 83달러 근접',
      '안전자산 국채마저 매도세, 10년물 금리 이례적 상승',
    ],
    theme: 'red',
    charts: [
      { ticker: 'CL=F', title: 'WTI Crude Oil' },
      { ticker: 'BZ=F', title: 'Brent Crude Oil' },
    ],
  },
  {
    id: 4,
    type: 'stats',
    turnId: 10,
    title: '유가 충격에 대한 시장 반응',
    description: '시장은 단순한 위험회피를 넘어 유가 급등이 가져올 인플레이션 압력과 그에 따른 연준의 긴축 장기화 가능성을 동시에 가격에 반영하기 시작했습니다.',
    stats: [
      { label: 'WTI 유가 (장중)', value: '+9% 이상', subtext: '배럴당 76달러 위협', trend: 'up' },
      { label: '10년물 국채금리', value: '상승', subtext: '이례적 매도세', trend: 'up' },
      { label: 'S&P 500', value: '약 -1%', subtext: '증시 동반 하락', trend: 'down' },
    ],
    note: '안전자산인 국채 가격이 하락(금리 상승)한 것은 시장의 우려가 단순 위험회피를 넘어섰음을 시사합니다.',
    theme: 'red',
  },
  {
    id: 5,
    type: 'headline',
    turnId: 11,
    icon: 'briefcase',
    title: '나쁜 소식 같은 좋은 소식',
    subtitle: '견조한 서비스업 지표, 오히려 금리인하 기대감 후퇴',
    description: '예상보다 강하게 나온 ISM 서비스업 PMI는 유가 급등으로 인플레이션 경계심이 높아진 상황에서, 연준이 고금리를 더 오래 유지할 명분이 될 수 있다는 해석으로 이어졌습니다.',
    bullets: [
      '3월 ISM 서비스업 PMI, 시장 예상치 상회',
      '미국 경제 2/3 차지하는 서비스업의 강력한 확장세 증명',
      '유가 급등 상황 속, 연준의 고금리 장기화 명분으로 해석',
      '기술주 중심 성장주에 큰 부담으로 작용',
    ],
    theme: 'blue',
    charts: [{ ticker: 'NASDAQ:IXIC', title: 'NASDAQ Composite' }],
  },
  {
    id: 6,
    type: 'comparison',
    turnId: 12,
    title: '인플레이션을 압박하는 양대 요인',
    description: '공급망 불안과 강력한 경제라는 두 가지 요소가 모두 고금리 장기화라는 하나의 결론으로 모이면서 시장의 하방 압력을 키웠습니다.',
    items: [
      {
        label: '공급 측면',
        value: '유가 급등',
        description: '중동 지정학적 리스크로 인한 실질적 공급망 충격',
        highlight: true,
      },
      {
        label: '수요 측면',
        value: '강한 경제',
        description: 'ISM 서비스업 PMI 호조로 확인된 견조한 수요 압력',
        highlight: true,
      },
      {
        label: '시장 결론',
        value: '고금리 장기화',
        description: '두 요인 모두 연준의 긴축 유지 가능성을 높여 시장에 부담',
        highlight: false,
      },
    ],
  },
  {
    id: 7,
    type: 'ticker-intro',
    turnId: 14,
    ticker: 'LMT',
    companyName: 'Lockheed Martin',
    currentPrice: 667.82,
    dayChange: -8.88,
    dayChangePercent: -1.31,
    description: '지정학적 리스크와 맞물려 가장 극적인 움직임을 보였습니다. 장 초반 사상 최고가를 경신하는가 싶더니 이내 급락하며 2% 넘게 하락 마감했습니다.',
    charts: [{ ticker: 'LMT', title: 'Lockheed Martin' }],
  },
  {
    id: 8,
    type: 'ticker-analysis',
    turnId: 15,
    ticker: 'LMT',
    title: "단기 고점 신호? '블로우-오프 탑' 패턴",
    description: '오늘 주가 움직임은 지정학적 뉴스에 대한 단기적 열광과 펀더멘털 위험에 대한 냉정한 평가가 충돌한 결과로 해석됩니다.',
    points: [
      '개장 직후: 이란 분쟁 격화 소식에 투자 심리 \'탐욕\' 단계 진입, 주가 사상 최고치 경신',
      '장중 급락: 연차보고서에 담긴 근본적 위험 요소를 기반으로 한 차익 실현 매물 출회',
      '두 시각의 충돌: 헤드라인 뉴스에 반응하는 군중 심리와 펀더멘털 기반의 투자자 시각 충돌',
      '결론: 하루의 주가 움직임은 단기 과열과 내재된 리스크의 동시 반영',
    ],
    outlook: '단기 변동성 확대 및 고점 형성 가능성에 대한 경계가 필요합니다.',
    outlookColor: 'amber',
  },
  {
    id: 9,
    type: 'stats',
    turnId: 17,
    ticker: 'LMT',
    title: "핵심 사업부 '항공'의 수익성 붕괴",
    description: '2025년 연차보고서에 따르면, 회사 전체 매출의 약 40%를 차지하는 항공 부문의 영업이익률이 심각하게 악화되었습니다.',
    stats: [
      { label: '항공 부문 매출 비중', value: '약 40%', subtext: '회사 전체 매출', trend: 'neutral' },
      { label: '영업이익률', value: '8.8% → 6.9%', subtext: '1년 만에 급락', trend: 'down' },
      { label: '주요 원인', value: '$9.5억 손실', subtext: '특정 고정가격 계약', trend: 'down' },
    ],
    note: "회사가 직접 '향후 추가적인 중대 손실 가능성'을 경고하며 펀더멘털 우려를 키웠습니다.",
    theme: 'purple',
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 19,
    ticker: 'LMT',
    title: '구조적 리스크: 성장 동력의 이면',
    description: '미사일 사업부의 성장은 긍정적이지만, 고정가격 계약 리스크는 특정 부서가 아닌 사업 모델 자체에 내재된 전사적 문제로 보입니다.',
    points: [
      '성장 사업부의 한계: 미사일 사업부(MFC)의 14% 매출 성장은 항공 부문의 이익률 붕괴를 메우기엔 역부족',
      '전사적 문제: 고정가격 계약 리스크는 항공 부문만의 문제가 아니며, 과거 MFC에서도 수십억 달러 손실 전례 존재',
      '사업 모델의 내재된 위험: 특정 부서의 실수가 아닌, 사업 모델 자체에 내재된 구조적 위험으로 판단',
      '수주잔고의 착시: 막대한 수주잔고가 질적 위험을 가리는 착시 효과를 일으킬 수 있음',
    ],
    outlook: '수주잔고의 양적 규모보다 질적 위험에 대한 면밀한 분석이 요구되는 시점입니다.',
    outlookColor: 'rose',
  },
  {
    id: 11,
    type: 'headline',
    turnId: 21,
    ticker: 'LMT',
    title: '수주잔고, 해자인가 시한폭탄인가',
    subtitle: '$1,936억 수주잔고의 양면성',
    description: '막대한 수주잔고는 미래 안정성을 보장하는 해자일 수도 있지만, 반복되는 손실은 수익성 없는 계약으로 가득 찬 시한폭탄일 수 있다는 우려를 낳습니다.',
    bullets: [
      '긍정적 측면: 미래 안정성을 보장하는 강력한 경제적 해자',
      '부정적 측면: 수익성 없는 계약으로 가득 찬 시한폭탄일 가능성',
      '근본적 문제: 복잡한 프로그램의 비용 예측 및 통제 능력에 대한 의문 제기',
      '시장 반응: 지정학적 호재에 열광 후, 재무제표의 구조적 위험을 깨닫고 급격히 냉각',
    ],
    theme: 'purple',
    charts: [{ ticker: 'LMT', title: 'Lockheed Martin' }],
  },
  {
    id: 12,
    type: 'events',
    turnId: 23,
    title: '이번 주 주목할 경제 이벤트',
    description: '시장의 모든 시선은 연준의 금리 인하 시점을 가늠할 핵심 데이터인 고용 지표에 집중되고 있습니다. 이번 주는 \'고용 데이터 주간\'입니다.',
    events: [
      {
        date: '3월 4일',
        label: '연준 베이지북 공개',
        description: '지역 연준들의 최근 경제 상황 평가 확인',
      },
      {
        date: '3월 5일',
        label: '챌린저 감원 보고서',
        description: '기업들의 감원 추세 확인',
      },
      {
        date: '3월 6일',
        label: '2월 비농업 고용보고서',
        description: '신규 고용, 실업률, 임금 상승률 등 핵심 데이터 발표',
      },
    ],
  },
  {
    id: 13,
    type: 'stats',
    turnId: 25,
    title: '2월 고용보고서 시장 전망치',
    description: '시장은 고용 시장이 이전보다 크게 둔화될 것으로 예상하고 있습니다. 너무 뜨겁지도, 너무 차갑지도 않은 \'골디락스\' 데이터가 나올지 주목됩니다.',
    stats: [
      { label: '비농업 신규 고용', value: '6만 명', subtext: '이전 13만 명에서 크게 둔화 예상', trend: 'down' },
      { label: '실업률', value: '4.3%', subtext: '이전과 동일할 것으로 전망', trend: 'neutral' },
      { label: '시간당 평균 임금 (MOM)', value: '+0.3%', subtext: '이전보다 소폭 둔화 예상', trend: 'down' },
    ],
    note: '시장은 고용 시장이 급격한 침체 없이 완만하게 둔화되는 신호를 확인하고 싶어합니다.',
    theme: 'gold',
  },
  {
    id: 14,
    type: 'comparison',
    turnId: 27,
    title: '고용보고서 시나리오별 시장 반응',
    description: '시장은 현재 매우 미묘한 줄타기를 하고 있습니다. 결과에 따라 시장의 변동성이 커질 수 있다는 점을 염두에 두어야 합니다.',
    items: [
      {
        label: '예상보다 강할 경우 (Hot)',
        value: '시장 부담',
        description: '연준 금리 인하 기대감 후퇴, 긴축 우려 부각',
      },
      {
        label: '예상에 부합할 경우 (Goldilocks)',
        value: '시장 안도',
        description: '완만한 둔화 확인, 연착륙 기대감 유지',
        highlight: true,
      },
      {
        label: '예상보다 약할 경우 (Cold)',
        value: '경기 침체 우려',
        description: '금리 인하 기대감은 커지나, 펀더멘털 우려 부각',
      },
    ],
  },
  {
    id: 15,
    type: 'closing',
    turnId: 29,
    headline: '변동성 속 거시적 흐름을 읽어야 할 때',
    tagline: '이번 주 고용보고서가 향후 시장의 분기점이 될 것입니다.',
    description: '단기적인 변동성에 흔들리기보다는 거시적인 흐름을 읽으려는 노력이 필요한 시점입니다. 고용보고서가 그 흐름을 판단하는 중요한 단서를 제공할 것입니다.',
  },
];