import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-03-06',
    nutshell: '유가 급등 충격과 고용지표 경계감 속 기술주 선방',
    description:
      '중동 지정학적 리스크로 인한 유가 급등이 시장을 강타하고, 2월 고용 보고서 발표를 앞둔 경계감이 투자 심리를 짓눌렀습니다. 이런 악재 속에서도 AI 관련 기술주는 상대적으로 선방하며 차별화된 흐름을 보였습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description:
      '중동 리스크로 인한 유가 폭등이 인플레이션 우려를 자극하며 시장 전반을 끌어내렸습니다. 다우 지수가 큰 폭으로 하락한 반면, 기술주 중심의 나스닥은 상대적으로 낙폭이 제한되었습니다.',
    indices: [
      { name: 'DOW', value: 47954.74, change: -784.67, changePercent: -1.61 },
      { name: 'S&P 500', value: 6830.71, change: -38.79, changePercent: -0.56 },
      { name: 'NASDAQ', value: 22748.99, change: -58.49, changePercent: -0.26 },
      { name: 'Russell 2000', value: 2585.57, change: -50.44, changePercent: -1.91 },
    ],
    commodities: [
      { name: 'WTI Crude', value: 78.87, change: 4.21, changePercent: 5.64 },
      { name: 'Gold Futures', value: 5093.30, change: -26.90, changePercent: -0.53 },
      { name: '10-Yr Yield', value: 4.14, change: 0.06, changePercent: 1.47 },
      { name: 'Dollar Index', value: 99.05, change: 0.28, changePercent: 0.28 },
    ],
    charts: [
      { ticker: 'DJ:DJI' },
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'TVC:RUT' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 6,
    icon: 'flame',
    title: '유가 급등, 시장을 덮치다',
    subtitle: '중동 지정학적 리스크 현실화',
    bullets: [
      '미-이란 군사 충돌 격화, 호르무즈 해협 봉쇄 우려 부상',
      'WTI 유가 하루 만에 5.6% 폭등, 배럴당 $78 돌파',
      '변동성지수(VIX) 12% 급등하며 위험 회피 심리 극대화',
      '10년물 국채금리 상승, 금리 인하 기대감 후퇴',
    ],
    theme: 'red',
  },
  {
    id: 3,
    type: 'stats',
    turnId: 7,
    title: '유가 급등의 시장 파급 효과',
    description:
      '유가 발 인플레이션 공포가 주식, 채권 등 자산시장 전반에 영향을 미쳤습니다. 안전자산 선호 심리에도 불구하고 국채금리는 오히려 상승했습니다.',
    stats: [
      { label: 'WTI 유가 (CL=F)', value: '+5.64%', subtext: '배럴당 $78 후반 마감', trend: 'up' },
      { label: 'VIX 지수 (^VIX)', value: '+12.1%', subtext: '공포 심리 확산', trend: 'up' },
      { label: '10년물 국채금리 (^TNX)', value: '+6bp', subtext: '인플레이션 우려 반영', trend: 'up' },
    ],
    charts: [{ ticker: 'CL=F' }, { ticker: 'TVC:VIX' }, { ticker: 'TVC:US10Y' }],
  },
  {
    id: 4,
    type: 'comparison',
    turnId: 9,
    title: '유가 충격 속 엇갈린 업종 명암',
    description:
      '유가라는 단일 변수가 시장 전체를 짓누르는 가운데, 비용 구조에 따라 업종별 희비가 극명하게 갈렸습니다.',
    items: [
      {
        label: '에너지 (XOM, CVX)',
        value: '상승',
        description: '유가 급등의 직접적인 수혜 (엑슨모빌 +2%)',
        highlight: true,
      },
      {
        label: '항공 (JETS ETF)',
        value: '급락',
        description: '연료 비용 부담 직격탄 (ETF -4.5%)',
        highlight: false,
      },
      {
        label: '제조/소매',
        value: '하락',
        description: '생산, 운송 등 공급망 비용 증가 압박',
        highlight: false,
      },
    ],
    charts: [{ ticker: 'NYSE:XOM' }, { ticker: 'NYSE:JETS' }],
  },
  {
    id: 5,
    type: 'headline',
    turnId: 14,
    icon: 'briefcase',
    title: '고용 보고서, 시장의 향방을 가른다',
    subtitle: '모든 시선은 내일 아침으로',
    bullets: [
      '유가발 인플레이션 압력과 연준 금리 경로의 힘겨루기',
      '견조한 고용 + 끈질긴 인플레이션 = 연준 매파 스탠스 우려',
      '10년물 국채금리 4.14%대, 달러 인덱스 강세 전환',
      '불확실성 속 다우 지수, 연중 상승분 모두 반납',
    ],
    theme: 'amber',
  },
  {
    id: 6,
    type: 'stats',
    turnId: 19,
    title: '2월 비농업 고용 보고서 전망 (월가 컨센서스)',
    description:
      '시장은 1월의 서프라이즈 이후 고용 증가세가 크게 둔화될 것으로 예상하고 있으나, 파업 및 날씨 등 해석에 주의가 필요한 변수들이 존재합니다.',
    stats: [
      { label: '신규 고용 전망', value: '5.5만 개', subtext: '1월(13만) 대비 큰 폭 둔화 예상' },
      { label: '실업률 전망', value: '4.3%', subtext: '이전과 동일 수준 유지 예상' },
      { label: '변수: 파업', value: '약 3.1만 명', subtext: '일시적 고용 감소 착시 효과' },
      { label: '변수: 날씨', value: '겨울 폭풍', subtext: '건설/레저 채용 위축 가능성' },
    ],
  },
  {
    id: 7,
    type: 'comparison',
    turnId: 21,
    title: '고용 보고서 시나리오별 시장 반응',
    description:
      '고용 보고서 결과에 따라 시장은 상반된 반응을 보일 수 있으며, 두 시나리오 모두 단기 변동성을 확대시킬 수 있습니다.',
    items: [
      {
        label: '예상보다 뜨거운 고용',
        value: '긴축 우려',
        description: '금리 인하 기대 후퇴, 국채 금리 급등, 주식 시장 조정 압력 가중',
        highlight: false,
      },
      {
        label: '예상보다 부진한 고용',
        value: '경기 둔화 우려',
        description: '금리 인하 기대감 부상 가능성, 단 기업 이익 전망 불안감 동반',
        highlight: false,
      },
    ],
    charts: [{ ticker: 'DJ:DJI' }],
  },
  {
    id: 8,
    type: 'headline',
    turnId: 22,
    icon: 'cpu',
    title: '기술주, 시장의 방파제 역할',
    subtitle: '거시 악재 속 \'퀄리티로의 도피\' 현상',
    bullets: [
      '다우(-1.61%), 러셀 2000(-1.9%) 등 경기민감주 급락',
      '나스닥 지수, 불과 0.26% 하락에 그치며 선방',
      'AI 등 구조적 성장 스토리를 가진 기술주로 자금 집중',
      '거시 경제 충격에서 상대적으로 자유롭다는 인식 확산',
    ],
    theme: 'blue',
    charts: [{ ticker: 'DJ:DJI' }, { ticker: 'NASDAQ:IXIC' }],
  },
  {
    id: 9,
    type: 'stats',
    turnId: 23,
    title: '주요 지수 성과 비교',
    description:
      '경기 민감주 비중이 높은 다우와 중소형주 중심의 러셀 2000 지수가 큰 타격을 받은 반면, 기술주 중심의 나스닥은 하방 경직성을 보였습니다.',
    stats: [
      { label: '나스닥', value: '-0.26%', trend: 'neutral' },
      { label: 'S&P 500', value: '-0.56%', trend: 'down' },
      { label: '다우존스', value: '-1.61%', trend: 'down' },
      { label: '러셀 2000', value: '-1.90%', trend: 'down' },
    ],
    charts: [{ ticker: 'NASDAQ:IXIC' }, { ticker: 'TVC:RUT' }],
  },
  {
    id: 10,
    type: 'ticker-intro',
    turnId: 30,
    ticker: 'ORCL',
    companyName: 'Oracle',
    currentPrice: 154.79,
    dayChange: 2.42,
    dayChangePercent: 1.59,
    description:
      '대규모 감원이라는 악재성 뉴스에도 불구하고 1.5% 넘게 상승 마감했습니다. 시장은 이를 AI 사업 확장을 위한 불가피한 과정으로 해석하며 미래 성장성에 베팅했습니다.',
    charts: [{ ticker: 'NYSE:ORCL' }],
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 31,
    ticker: 'ORCL',
    title: '성장 스토리: 시장의 기대',
    points: [
      '기록적인 수주잔고($5,233억)가 미래 매출을 담보',
      '레거시 사업 정리, AI 인프라에 모든 자원 집중',
      'AI 사업 확장을 위한 과감한 전략적 전환으로 평가',
      '성장 기대감이 단기 재무 압박에 대한 우려를 압도',
    ],
    outlook: '시장 낙관론',
    outlookColor: 'emerald',
  },
  {
    id: 12,
    type: 'ticker-analysis',
    turnId: 33,
    ticker: 'ORCL',
    title: '재무 리스크: 숨겨진 경고 신호',
    points: [
      'AI 인프라 구축에 막대한 자본 지출 (6개월간 $205억)',
      '잉여현금흐름 급격히 악화 (연간 +95억 → -132억 달러)',
      '총 부채 $1,080억 돌파, 외부 자금 조달 의존도 심화',
      '최근 감원은 현금 부족 해결을 위한 고육지책일 가능성',
    ],
    outlook: '펀더멘털 취약성',
    outlookColor: 'rose',
  },
  {
    id: 13,
    type: 'ticker-analysis',
    turnId: 35,
    ticker: 'ORCL',
    title: '수주잔고의 함정: 기대와 현실의 괴리',
    points: [
      '수주잔고의 90%는 2~5년 이상 초장기 계약',
      '향후 12개월 내 매출로 인식될 금액은 10%에 불과',
      '거대한 계약 규모가 단기 현금흐름 문제 해결 불가',
      '클라우드 사업부 마진율 하락 (63% → 59%)',
    ],
    outlook: '신중한 접근 필요',
    outlookColor: 'amber',
  },
  {
    id: 14,
    type: 'events',
    turnId: 41,
    title: '주요 경제 이벤트 캘린더',
    description:
      '다음 주 발표될 주요 경제 지표들이 연준의 금리 인하 경로를 가늠할 핵심 변수가 될 전망입니다.',
    events: [
      {
        date: '3월 11일',
        label: '소비자물가지수 (CPI)',
        description: '인플레이션 둔화 추세 확인 여부가 최대 관심사',
      },
      {
        date: '3월 13일',
        label: '구인·이직 보고서 (JOLTS)',
        description: '노동 시장 수요와 임금 상승 압력 가늠자',
      },
    ],
  },
  {
    id: 15,
    type: 'headline',
    turnId: 44,
    icon: 'calendar-days',
    title: '시장의 시선, 데이터로',
    subtitle: '파월 증언 이후 데이터 의존 장세 돌입',
    bullets: [
      '파월 의장, 금리 인하 가능성 시사했으나 신중론 유지',
      '강력한 비둘기파적 신호 부재에 투자자 관망세 전환',
      '시장의 관심은 이제 핵심 경제 지표로 이동',
      '개별 기업 이슈보다 거시 지표가 시장 방향성 결정할 것',
    ],
    theme: 'purple',
  },
  {
    id: 16,
    type: 'closing',
    turnId: 45,
    headline: '데이터를 확인하며 신중하게',
    tagline: '거시 경제 지표에 따른 변동성 장세 대비',
    description:
      '연준이 금리 인하의 전제 조건으로 더 많은 데이터를 원한다고 밝힌 만큼, 앞으로 발표될 CPI나 JOLTS 같은 핵심 지표의 결과가 시장의 단기적인 분위기를 좌우할 가능성이 높습니다. 신중한 접근이 필요한 시점입니다.',
  },
];