import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-01-22',
    nutshell: '관세 위협 완화와 견조한 경제 지표가 광범위한 시장 랠리를 이끌었고, 기술주가 상승을 주도했습니다.',
    description: '트럼프 전 대통령의 관세 계획 철회 소식과 예상보다 좋은 경제 지표가 투자 심리를 회복시키며 시장 전반의 상승을 이끌었습니다. 특히 AI에 대한 낙관론이 지속되며 기술주가 강세를 보였습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '지정학적 우려가 해소되면서 투자 심리가 회복되어 모든 주요 지수가 상승 마감했습니다. 기술주 중심의 나스닥이 0.91% 오르며 상승을 주도했습니다.',
    indices: [
      { name: 'S&P 500', value: 6913.00, change: 37.83, changePercent: 0.55 },
      { name: 'NASDAQ', value: 23436.00, change: 211.80, changePercent: 0.91 },
      { name: 'DOW', value: 48450.21, change: 303.35, changePercent: 0.63 },
    ],
    commodities: [],
    charts: [
      { ticker: 'SP:SPX', title: 'S&P 500' },
      { ticker: 'NASDAQ:IXIC', title: 'NASDAQ Composite' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 7,
    icon: 'trending-up',
    title: '관세 위협 완화',
    subtitle: '지정학적 불확실성 해소, 안도 랠리 촉발',
    description: '트럼프 전 대통령이 그린란드 문제와 관련해 유럽 동맹국에 부과하려던 관세 계획을 철회했다는 소식이 전해지자, 시장을 짓누르던 무역 전쟁의 공포가 완화되며 투자 심리가 빠르게 회복되었습니다.',
    bullets: [
      '트럼프 전 대통령, 유럽 8개국 대상 10% 관세 계획 철회',
      '무역 긴장 완화로 시장 전반에 걸친 안도 랠리 발생',
      '다우 +0.63%, S&P 500 +0.55%, 나스닥 +0.91% 동반 상승',
    ],
    theme: 'green',
    charts: [
      { ticker: 'DJ:DJI', title: 'Dow Jones' },
      { ticker: 'SP:SPX', title: 'S&P 500' },
      { ticker: 'NASDAQ:IXIC', title: 'NASDAQ Composite' },
    ],
  },
  {
    id: 3,
    type: 'stats',
    turnId: 11,
    title: '견조한 경제 펀더멘털',
    description: '관세 우려 완화와 더불어 긍정적인 경제 지표가 발표되면서 시장의 상승폭을 키웠습니다. 이는 미국 경제의 연착륙 기대감을 더욱 높였습니다.',
    stats: [
      { label: '4분기 GDP 성장률 (최종)', value: '4.4%', subtext: '예상치(4.3%) 상회', trend: 'up' },
      { label: '주간 신규 실업수당 청구', value: '20만 건', subtext: '예상치 하회', trend: 'up' },
    ],
    note: '무역 리스크 해소와 튼튼한 경제라는 두 가지 호재가 맞물려 투자자들의 위험 선호 심리를 자극했습니다.',
    theme: 'green',
  },
  {
    id: 4,
    type: 'headline',
    turnId: 15,
    icon: 'cpu',
    title: '기술주 랠리 지속',
    subtitle: 'AI 인프라 투자 낙관론 확산',
    description: '다보스 포럼에서 AI 성장을 위한 대규모 인프라 구축 필요성이 강조되면서, AI 관련주에 대한 장기적인 투자 심리가 계속해서 시장을 자극하고 있습니다.',
    bullets: [
      '다보스 포럼: AI 성장을 위한 역사상 가장 큰 인프라 구축 필요성 강조',
      '알리바바, AI 칩 설계 부문 \'티헤드(T-Head)\' IPO 준비 소식',
      '인텔 실적 발표, AI PC 및 데이터센터 기대감 집중',
    ],
    theme: 'blue',
  },
  {
    id: 5,
    type: 'headline',
    turnId: 19,
    title: '반도체 섹터 동향',
    subtitle: '인텔 실적 발표에 쏠린 시장의 눈',
    description: '인텔의 실적 발표를 앞두고 월스트리트의 기대감이 커졌습니다. 데이터센터 수요 회복과 AI PC용 신형 칩에 대한 낙관론이 주가에 선반영된 가운데, 경쟁사인 엔비디아와 AMD 역시 강세를 보였습니다.',
    theme: 'blue',
    charts: [
      { ticker: 'INTC', title: 'Intel' },
      { ticker: 'NVDA', title: 'NVIDIA' },
      { ticker: 'AMD', title: 'AMD' },
    ],
  },
  {
    id: 6,
    type: 'ticker-intro',
    turnId: 22,
    ticker: 'INTC',
    companyName: 'Intel Corporation',
    currentPrice: 45.06,
    dayChange: 0.06,
    dayChangePercent: 0.13,
    description: '장 마감 후 실적을 발표한 인텔은 시장의 기대와 우려가 교차하는 가운데, 기술주 랠리의 향방을 가늠할 중요한 시험대에 올랐습니다.',
    charts: [{ ticker: 'INTC' }],
  },
  {
    id: 7,
    type: 'ticker-analysis',
    turnId: 23,
    ticker: 'INTC',
    title: '실적 발표: 충격적인 1분기 가이던스',
    points: [
      '4분기 매출은 시장 예상 상회',
      '1분기 조정 주당순이익(EPS) 가이던스를 \'사실상 0\'으로 제시',
      '시장의 기대치를 크게 밑도는 전망에 시간 외 주가 급락',
      '인텔의 턴어라운드 스토리에 대한 심각한 의구심 촉발',
    ],
    description: '매출 호조라는 긍정적 소식에도 불구하고, 충격적인 수준의 다음 분기 이익 전망은 인텔의 미래에 대한 모든 낙관론을 압도했습니다.',
  },
  {
    id: 8,
    type: 'ticker-analysis',
    turnId: 25,
    ticker: 'INTC',
    title: '핵심 리스크: 파운드리 전략의 불확실성',
    points: [
      '자체 보고서(10-K)에서 파운드리 사업의 높은 리스크를 스스로 인정',
      '아직 의미 있는 외부 대형 고객을 확보하지 못한 상태',
      '막대한 자본 지출과 부채 부담 속에서 수익성 악화 현실화',
      '18A 공정 기술 등 장기적 희망보다 당장의 수익성 붕괴가 부각',
    ],
    description: '인텔의 미래 성장 동력으로 꼽히는 파운드리 사업이 구체적인 성과를 내지 못하면서 구조적 취약점에 대한 우려가 커지고 있습니다.',
  },
  {
    id: 9,
    type: 'ticker-analysis',
    turnId: 29,
    ticker: 'INTC',
    title: '투자 의견: 보유 (HOLD)',
    action: 'HOLD',
    points: [
      '매도 고려: 턴어라운드의 구체적 증거 부족, 파운드리 전략 불확실성',
      '보유 근거: 주가 급락으로 단기적인 최악의 시나리오가 상당 부분 반영',
      '결론: 공격적인 매매보다는 성과를 확인하는 \'관망\' 자세 필요',
    ],
    description: '현재 주가는 최악의 시나리오를 일부 반영했으나, 펀더멘털 개선의 명확한 신호가 없어 신규 매수는 시기상조라는 분석입니다. 파운드리 전략의 성공을 입증할 증거가 나오기 전까지 관망이 필요합니다.',
  },
  {
    id: 10,
    type: 'events',
    turnId: 33,
    title: '향후 주요 경제 일정',
    description: 'S&P 500 지수가 사상 최고치를 경신한 가운데, 시장의 관심은 연준의 통화정책 향방을 가늠할 수 있는 주요 경제 지표 발표에 집중되고 있습니다.',
    events: [
      {
        date: '금주 금요일 (1/23)',
        label: 'S&P 글로벌 PMI 속보치',
        description: '제조업 및 서비스업 경기를 가장 먼저 엿볼 수 있는 선행지표',
      },
      {
        date: '다음 주 수요일 (1/28)',
        label: 'FOMC 금리 결정 및 기자회견',
        description: '금리 동결이 예상되며, 파월 의장의 금리 인하 시점 관련 발언에 주목',
      },
    ],
  },
  {
    id: 11,
    type: 'closing',
    turnId: 38,
    headline: '거시 호재 속 개별 기업 리스크 부각',
    tagline: '랠리 지속의 열쇠는 펀더멘털',
    description: '오늘은 무역 긴장 완화와 견조한 경제 지표 덕분에 시장이 전반적으로 상승했지만, 장 마감 후 발표된 인텔의 실망스러운 가이던스는 기술주 랠리의 지속성에 대한 질문을 던졌습니다. 향후 FOMC 등 거시 경제 지표를 주시하며 시장 방향성을 확인해야 할 시점입니다.',
  },
];