import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-01-24',
    nutshell: '인텔 충격에 다우 하락, 견조한 경제지표에 나스닥은 상승',
    description: '인텔의 부진한 실적 전망이 다우 지수를 끌어내렸지만, 긍정적인 경제 지표가 나스닥의 상승을 이끌며 시장이 혼조세로 마감했습니다. 오늘 브리핑에서는 시장의 주요 동향과 함께 TSMC에 대한 심층 분석을 다룹니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '인텔의 주가 급락으로 다우 지수는 하락했지만, 견조한 경제 지표에 힘입어 나스닥과 S&P 500 지수는 상승하며 지수별로 엇갈린 모습을 보였습니다.',
    indices: [
      { name: 'S&P 500', value: 0, change: 0, changePercent: 0.03 },
      { name: 'NASDAQ', value: 0, change: 0, changePercent: 0.28 },
      { name: 'DOW', value: 0, change: 0, changePercent: -0.58 },
    ],
    commodities: [],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 3,
    icon: 'cpu',
    title: '인텔 쇼크, 다우 지수 하락 주도',
    subtitle: '예상 하회 실적 전망에 주가 17% 급락',
    description: '반도체 기업 인텔이 시장 예상치를 크게 밑도는 1분기 실적 전망을 내놓으면서 주가가 17% 넘게 폭락, 다우 지수 하락의 주요 원인이 되었습니다. 하지만 함께 발표된 경제 지표는 긍정적으로 나오며 시장의 추가 하락을 막았습니다.',
    bullets: [
      '인텔, 시장 예상치 크게 밑도는 1분기 실적 전망 발표',
      '주가 17% 이상 폭락하며 다우 지수 하락 견인',
      '서비스업 PMI, 소비자심리지수는 긍정적',
      '견조한 경제지표가 나스닥 상승을 이끌며 추가 하락 방어',
    ],
    theme: 'red',
    charts: [
      { ticker: 'INTC', title: 'Intel Corp.' },
    ],
  },
  {
    id: 3,
    type: 'ticker-intro',
    turnId: 6,
    ticker: 'TSM',
    companyName: 'TSMC',
    currentPrice: 0,
    dayChange: 0,
    dayChangePercent: 0,
    description: '최근 특별한 소식 없이도 주가가 꾸준히 오르는 모습을 보인 TSMC, 그 배경에는 AI 시대의 핵심 인프라라는 강력한 내러티브가 자리 잡고 있습니다.',
    charts: [
      { ticker: 'TSM' },
    ],
  },
  {
    id: 4,
    type: 'ticker-analysis',
    turnId: 7,
    ticker: 'TSM',
    title: '강점: AI 혁명의 유일한 인프라',
    points: [
      '애플, 엔비디아 등 빅테크의 최첨단 AI 칩 사실상 독점 생산',
      '2025년 양산 예정인 2나노 공정 기술로 경쟁사와의 격차 확대 기대',
      '시장은 TSMC를 AI 혁명을 가능하게 하는 대체 불가능한 핵심 기업으로 평가',
    ],
    description: 'TSMC의 가장 큰 강점은 AI 칩 생산의 독점적 지위입니다. 최첨단 공정 기술을 바탕으로 AI 시대의 성장을 이끄는 핵심 인프라 기업으로 평가받고 있습니다.',
  },
  {
    id: 5,
    type: 'ticker-analysis',
    turnId: 9,
    ticker: 'TSM',
    title: '약점: 지정학적 리스크 딜레마',
    points: [
      '대만을 둘러싼 지정학적 리스크가 투자의 가장 큰 우려점',
      '긍정론: 세계 기술 패권의 핵심 \'실리콘 방패\' 역할',
      '비관론: 분쟁 발생 시 \'실리콘 인질\'로 전락, 자본의 영구 손실 가능성',
      '기업의 존립 자체를 위협하는 최악의 시나리오 상존',
    ],
    description: 'AI 성장 잠재력에도 불구하고, 대만을 둘러싼 지정학적 리스크는 TSMC의 실존적 위협입니다. 이는 주가가 회복 불가능한 수준으로 폭락할 수 있는 치명적인 약점입니다.',
  },
  {
    id: 6,
    type: 'comparison',
    turnId: 11,
    title: '해외 공장 건설: 기회인가, 비용인가?',
    description: '미국, 일본 등 해외 공장 건설은 지정학적 리스크를 분산하려는 시도지만, 이에 대한 평가는 엇갈립니다.',
    items: [
      {
        label: '긍정론',
        value: '새로운 성장 전략',
        description: '각국 정부 보조금과 공급망 안정화를 통해 고객에게 \'안심 프리미엄\'을 붙여 판매 가능',
        highlight: false,
      },
      {
        label: '비판론',
        value: '수익성 악화 우려',
        description: '대만보다 높은 운영 비용으로 전체 이익률 하락, 핵심 기술은 여전히 대만에 있어 근본적 위험 해소 한계',
        highlight: true,
      },
    ],
  },
  {
    id: 7,
    type: 'ticker-analysis',
    turnId: 13,
    ticker: 'TSM',
    title: '최종 투자 판단: 매도 (SELL)',
    points: [
      'AI 혁명이라는 거대한 성장 기회는 분명 매력적',
      '하지만 자본의 영구적 손실로 이어질 수 있는 지정학적 리스크가 너무 치명적',
      '현재 주가는 \'블랙 스완\' 리스크에 대한 충분한 안전마진을 제공하지 못함',
    ],
    action: 'SELL',
    description: '결론적으로 잠재적 이익보다 리스크 관리에 더 무게를 두는 것이 합리적이라는 판단 하에 \'매도\' 의견이 높은 신뢰도로 제시되었습니다.',
  },
  {
    id: 8,
    type: 'headline',
    turnId: 14,
    title: '시장 마무리: 혼조세 속 S&P 500 최고치',
    subtitle: '지수별 방향성 엇갈리며 마감',
    description: 'S&P 500 지수는 사상 최고치를 경신했지만, 다우와 나스닥의 방향이 엇갈리며 혼조세로 장을 마감했습니다. 장 초반의 상승세를 일부 기술주들이 반납하면서 지수별로 다른 흐름을 보였습니다.',
  },
  {
    id: 9,
    type: 'events',
    turnId: 17,
    title: '주요 경제 일정',
    description: '향후 시장 방향을 결정할 주요 경제 지표 발표와 연준 회의에 주목해야 합니다.',
    events: [
      {
        date: '내일',
        label: '4분기 GDP 성장률 및 PCE 물가지수',
        description: '미국 경제 성장세와 연준이 주시하는 인플레이션 현주소를 파악할 수 있습니다.',
      },
      {
        date: '금주 발표',
        label: 'S&P 글로벌 종합 PMI',
        description: '기업들의 경기 전망을 보여주는 지표로, 향후 경제 활동을 가늠해 볼 수 있습니다.',
      },
      {
        date: '다음 주',
        label: '연방공개시장위원회 (FOMC)',
        description: '금리 동결이 예상되나, 파월 의장의 발언에서 향후 금리 인하 힌트를 찾으려는 시도가 이어질 것입니다.',
      },
    ],
  },
  {
    id: 10,
    type: 'closing',
    turnId: 22,
    headline: '개별 종목 악재와 거시 지표의 힘겨루기',
    tagline: '다음 주 FOMC를 향한 시장의 시선',
    description: '인텔의 실적 충격이 시장을 압박했지만, 견조한 경제 지표가 방어막이 되었습니다. 투자자들의 관심은 이제 다음 주 FOMC 회의와 파월 의장의 발언에 집중될 것입니다.',
  },
];