import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-03-12',
    nutshell: '오라클 호실적과 유가 급등 속 시장 혼조',
    description: '오라클의 AI 기대감이 기술주를 견인했지만, 지정학적 리스크로 인한 유가 급등이 시장 전반을 압박하며 주요 지수가 엇갈린 하루였습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '주요 지수 및 원자재 동향',
    description: '기술주 중심의 나스닥은 소폭 상승했으나, 다우와 S&P 500은 유가 급등 부담에 하락했습니다. 지정학적 리스크에 유가와 금, 달러가 동반 강세를 보였습니다.',
    indices: [
      { name: 'S&P 500', value: 6775.80, change: -5.68, changePercent: -0.08 },
      { name: 'NASDAQ', value: 22716.13, change: 19.04, changePercent: 0.08 },
      { name: 'DOW', value: 47417.27, change: -289.24, changePercent: -0.61 },
      { name: 'Russell 2000', value: 2542.90, change: -5.18, changePercent: -0.20 },
    ],
    commodities: [
      { name: 'WTI Crude', value: 88.41, change: 4.96, changePercent: 5.94 },
      { name: 'Gold Futures', value: 5183.90, change: -45.80, changePercent: -0.88 },
      { name: 'Dollar Index', value: 99.25, change: 0.42, changePercent: 0.43 },
      { name: '10-Yr Yield', value: 4.20, change: 0.07, changePercent: 1.69 },
    ],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'TVC:RUT' },
      { ticker: 'NYMEX:CL' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 3,
    icon: 'zap',
    title: '엇갈린 시장: AI 기대감 vs 유가 쇼크',
    subtitle: '오라클의 호실적이 나스닥을 견인했으나, 지정학적 리스크가 시장 전반을 압박했습니다.',
    bullets: [
      '오라클: 실적 호조 및 AI 전망에 9% 이상 폭등',
      '기술주: 투자 심리 개선, 나스닥 지수 상승 견인',
      '국제 유가: 이란 관련 분쟁으로 5% 이상 급등, 인플레이션 우려 자극',
      '다우 & S&P 500: 유가 부담에 하락 마감',
    ],
    theme: 'amber',
    charts: [
      { ticker: 'ORCL', title: 'Oracle Corp.' },
      { ticker: 'NYMEX:CL', title: 'WTI Crude Oil' },
    ],
  },
  {
    id: 3,
    type: 'headline',
    turnId: 7,
    icon: 'droplet',
    title: '유가 급등, 시장을 덮치다',
    subtitle: '이란 분쟁 격화로 호르무즈 해협 긴장이 고조되며 공급망 우려가 유가를 끌어올렸습니다.',
    bullets: [
      '원인: 호르무즈 해협 인근 상선 피격',
      'WTI 유가: 6% 이상 급등, 배럴당 $88 돌파',
      '시장 영향: 인플레이션 우려, 10년물 국채 금리 4.2%대 상승',
      '섹터별 동향: 에너지 섹터(+2.4%) 유일 강세, 안전자산 달러 강세',
    ],
    theme: 'red',
    charts: [
      { ticker: 'NYMEX:CL', title: 'WTI Crude Oil' },
      { ticker: 'AMEX:XLE', title: 'Energy Sector SPDR Fund' },
    ],
  },
  {
    id: 4,
    type: 'stats',
    turnId: 9,
    title: '유가 급등의 경제적 파급 효과',
    description: '유가 상승은 운송, 제조 등 전통 산업의 비용 부담을 가중시키고 소비 심리를 위축시켜 다우와 S&P 500에 더 큰 타격을 주었습니다.',
    stats: [
      { label: '산업 비용', value: '증가', subtext: '운송, 제조, 농업 등', trend: 'up' },
      { label: '소비 여력', value: '위축', subtext: '가처분 소득 감소', trend: 'down' },
      { label: '항공주', value: '하락', subtext: '유류비 부담 증가', trend: 'down' },
      { label: '금리 인하 기대', value: '후퇴', subtext: '인플레이션 재점화 우려', trend: 'down' },
    ],
    theme: 'red',
    charts: [
      { ticker: 'AMEX:JETS', title: 'U.S. Global Jets ETF' },
      { ticker: 'TVC:US10Y', title: 'US 10-Year Treasury Yield' },
    ],
  },
  {
    id: 5,
    type: 'headline',
    turnId: 13,
    icon: 'shield',
    title: '비축유 방출, 효과는 \'제한적\'',
    subtitle: 'IEA가 사상 최대 규모의 전략 비축유 방출을 결정했지만, 유가 상승세를 꺾기에는 역부족이었습니다.',
    bullets: [
      'IEA, 4억 배럴 규모 전략 비축유 방출 합의',
      '발표 직후 유가 잠시 주춤했으나 이내 상승세 복귀',
      '시장은 이를 일시적 조치로 판단, 근본 해결책으로 보지 않음',
      '호르무즈 해협 봉쇄 장기화 시 공급 차질 우려가 더 큼',
    ],
    theme: 'gold',
  },
  {
    id: 6,
    type: 'stats',
    turnId: 15,
    title: '지표와 현실의 괴리: 2월 CPI',
    description: '시장은 예상에 부합한 과거 물가 지표보다, 유가 급등이 불러올 미래의 인플레이션이라는 그림자에 집중했습니다.',
    stats: [
      { label: '2월 CPI (YoY)', value: '2.4%', subtext: '예상치 부합', trend: 'neutral' },
      { label: 'WTI 유가 (일간)', value: '+6% >', subtext: '$88 돌파', trend: 'up' },
      { label: '10년물 국채금리', value: '4.2% >', subtext: '7bp 이상 급등', trend: 'up' },
      { label: '달러 인덱스', value: '강세', subtext: '안전자산 선호', trend: 'up' },
    ],
    note: '월가에서는 고유가 지속 시 헤드라인 인플레이션이 3%대로 복귀할 수 있다는 전망이 나옵니다.',
    theme: 'blue',
    charts: [
      { ticker: 'NYMEX:CL', title: 'WTI Crude Oil' },
      { ticker: 'TVC:DXY', title: 'U.S. Dollar Index' },
    ],
  },
  {
    id: 7,
    type: 'headline',
    turnId: 19,
    icon: 'trending-down',
    title: '스태그플레이션 우려 부상',
    subtitle: '산업의 혈액인 디젤 가격 급등이 단순 비용 증가를 넘어 경기 침체 속 물가 상승이라는 최악의 시나리오 우려를 키우고 있습니다.',
    bullets: [
      '디젤 가격 급등: 운송, 농업, 제조업 등 산업 전반의 원가 부담 가중',
      '2차 효과 발생: 상품 및 서비스 가격 인상으로 전가되어 인플레이션 자극',
      '최악의 시나리오: 소비는 위축시키면서 물가는 올리는 스태그플레이션 가능성',
      '시장, 차기 인플레이션 경로를 다시 계산하기 시작',
    ],
    theme: 'red',
  },
  {
    id: 8,
    type: 'comparison',
    turnId: 21,
    title: '연준의 딜레마: 2월 CPI vs 유가 쇼크',
    description: '연준은 긍정적인 물가 데이터와 갑작스러운 유가 충격 사이에서 곤란한 상황에 처했습니다. 금리 동결 및 관망세가 유력해졌습니다.',
    items: [
      {
        label: '2월 CPI 데이터',
        value: '긍정적 신호',
        description: '전년 대비 2.4% 상승, 예상 부합. 금리 인하 고려 가능성 시사.',
        highlight: false,
      },
      {
        label: '유가 쇼크',
        value: '강력한 경고등',
        description: '단기 인플레이션 불확실성 증대. 섣부른 정책 전환에 대한 부담 가중.',
        highlight: true,
      },
      {
        label: '예상되는 연준 스탠스',
        value: '금리 동결 및 관망',
        description: '유가 충격의 경제적 영향을 신중히 지켜볼 가능성. 긴축 기조 유지 기간에 관심 집중.',
        highlight: false,
      },
    ],
  },
  {
    id: 9,
    type: 'ticker-intro',
    turnId: 22,
    ticker: 'CEG',
    companyName: 'Constellation Energy',
    currentPrice: 300.69,
    dayChange: -16.40,
    dayChangePercent: -5.17,
    description: '콘스텔레이션 에너지는 칼파인 인수 이후 \'AI 성장 스토리\'와 \'부채 리스크\'가 충돌하며 주가가 5% 이상 급락했습니다.',
    charts: [
      { ticker: 'CEG' },
    ],
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 25,
    ticker: 'CEG',
    title: '성장론: AI 시대를 여는 전략적 확장',
    points: [
      '칼파인 인수는 AI 혁명을 뒷받침할 에너지 영토 선점 전략.',
      '원자력(기저부하)과 천연가스(유연성) 결합으로 \'24시간 무탄소 전력\' 공급 가능.',
      '빅테크 데이터센터가 요구하는 안정적 전력 공급의 유일한 대안으로 부상.',
      '2025년 회계연도 기준 $42억 이상의 강력한 영업 현금흐름으로 부채 감당 가능.',
    ],
    outlook: 'AI 인프라의 핵심 기업으로 재평가될 경우 상당한 주가 상승 잠재력 보유.',
    outlookColor: 'emerald',
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 27,
    ticker: 'CEG',
    title: '리스크론: 감당하기 힘든 재무 부담',
    points: [
      '칼파인 인수로 $126억의 신규 부채 발생.',
      '2026년 한 해에만 $96억 이상의 막대한 현금 지출 예정.',
      '신용등급 강등 시 약 $27억의 추가 담보 제공 의무 발생 (유동성 위기 우려).',
      '인플레이션 감축법(IRA) 세액공제 축소 등 규제 리스크 상존.',
    ],
    outlook: '리스크 시나리오 현실화 시 심각한 자본 손실에 직면할 수 있음.',
    outlookColor: 'rose',
  },
  {
    id: 12,
    type: 'comparison',
    turnId: 29,
    title: '콘스텔레이션 에너지: 기회와 위험의 공존',
    description: '현재 CEG는 높은 잠재 수익률과 그에 상응하는 높은 리스크를 동시에 지닌 \'고위험 고수익\' 투자처의 특성을 보입니다.',
    items: [
      {
        label: '성장 잠재력 (Bull)',
        value: 'AI 인프라 핵심',
        description: 'AI 데이터센터향 \'24시간 무탄소 전력\' 독점 공급 가능성. 장기 성장 스토리 유효.',
        highlight: false,
      },
      {
        label: '재무 리스크 (Bear)',
        value: '막대한 부채',
        description: '$126억의 인수 부채와 신용등급 강등 가능성 등 단기적 유동성 위협.',
        highlight: true,
      },
      {
        label: '투자 판단',
        value: '신중한 접근 필요',
        description: '인수 후 통합 과정, 부채 관리 능력 등 불확실성 해소 과정을 지켜볼 필요.',
        highlight: false,
      },
    ],
  },
  {
    id: 13,
    type: 'events',
    turnId: 31,
    title: '향후 시장의 시선이 향하는 곳',
    description: '시장은 인플레이션의 다음 단서를 찾기 위해 주요 경제 지표 발표와 연준의 FOMC 회의를 주목하고 있습니다.',
    events: [
      {
        date: '2026-03-18',
        label: '생산자물가지수(PPI) 발표',
        description: '기업 비용 측면의 인플레이션 압력을 보여주는 선행 지표.',
      },
      {
        date: '2026-03-18',
        label: 'FOMC 정례회의',
        description: '금리 동결이 유력하나, 경제 전망과 점도표에 모든 관심이 집중.',
      },
      {
        date: '2026-03-18',
        label: '점도표(Dot Plot) 공개',
        description: '연내 금리 인하 횟수 전망(3회 vs 2회)이 시장 방향성을 결정할 핵심 변수.',
      },
    ],
  },
  {
    id: 14,
    type: 'stats',
    turnId: 35,
    title: 'FOMC 핵심 관전 포인트: 점도표',
    description: '점도표는 연준의 정책 방향에 대한 가장 명확한 신호를 제공하며, 금리 인하 기대감의 유지 또는 후퇴를 결정할 것입니다.',
    stats: [
      { label: '금리 결정', value: '동결 유력', subtext: '시장은 이미 반영', trend: 'neutral' },
      { label: '점도표 중간값 (3회 인하)', value: '시장 안도', subtext: '기존 전망 유지 시', trend: 'up' },
      { label: '점도표 중간값 (2회 인하)', value: '시장 충격', subtext: '전망 후퇴 시', trend: 'down' },
    ],
    note: '투자자들은 점도표를 통해 연준의 인플레이션 진단과 향후 금리 경로에 대한 확신을 얻고자 할 것입니다.',
    theme: 'purple',
  },
  {
    id: 15,
    type: 'closing',
    turnId: 37,
    headline: '사상 최고치 경신, 그러나 남은 과제',
    tagline: '상승 동력과 인플레이션 우려 속 변동성 확대 가능성에 유의',
    description: '시장은 강한 모습을 보이고 있지만, 중요한 경제 지표 발표와 연준의 결정을 앞두고 있어 신중한 투자 전략이 요구되는 시점입니다.',
  },
];