import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-02-11',
    nutshell: '강한 고용지표 압박 속 실적 따라 차별화 장세',
    description: '예상을 뛰어넘는 고용 지표가 연준의 금리 인하 기대를 후퇴시키며 시장에 부담으로 작용했습니다. 이런 환경 속에서 투자자들은 개별 기업의 실적에 더욱 집중하며, AI 관련주와 실적 부진주 사이의 희비가 극명하게 엇갈리는 차별화 장세가 펼쳐졌습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '주요 지수는 강한 고용 지표 발표 이후 혼조세로 마감했습니다. 연준의 금리 인하 기대감이 후퇴하며 국채 금리가 상승했지만, 기술주 중심의 나스닥은 개별 종목 호실적에 힘입어 소폭 상승했습니다.',
    indices: [
      { name: 'S&P 500', value: 6950.35, change: -0.35, changePercent: -0.01 },
      { name: 'NASDAQ 100', value: 24069.60, change: 69.60, changePercent: 0.29 },
      { name: 'DOW', value: 49036.30, change: -63.70, changePercent: -0.13 },
    ],
    commodities: [
      { name: '10년물 국채금리', value: 4.17, change: 0.08, changePercent: 1.96 },
      { name: '달러 인덱스', value: 104.50, change: 0.45, changePercent: 0.43 },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 6,
    icon: 'briefcase',
    title: '예상 뛰어넘은 고용 보고서',
    subtitle: '연준 금리 인하 기대감 후퇴',
    description: '1월 비농업 고용지표가 시장 전망치를 모든 면에서 크게 상회하며 견조한 노동시장을 증명했습니다. 이는 연준의 조기 금리 인하 기대를 급격히 냉각시키며 국채금리 상승과 달러 강세를 유발했습니다.',
    bullets: [
      '비농업 신규 고용: 13만 명 (예상 7만 명)',
      '실업률: 4.3% (예상 4.4%)',
      '시간당 평균 임금 (YoY): +3.7% (예상 상회)',
      '10년물 국채금리 4.17% 선까지 상승',
    ],
    theme: 'red',
  },
  {
    id: 3,
    type: 'stats',
    turnId: 7,
    title: '1월 고용지표 상세',
    description: '신규 고용, 실업률, 임금 상승률 등 모든 지표가 시장의 예상을 뛰어넘는 서프라이즈를 기록하며 인플레이션에 대한 경계심을 자극했습니다.',
    stats: [
      { label: '비농업 신규 고용', value: '13만 명', subtext: '예상(7만) 약 2배', trend: 'up' },
      { label: '실업률', value: '4.3%', subtext: '예상(4.4%) 하회', trend: 'down' },
      { label: '시간당 임금 (YoY)', value: '+3.7%', subtext: '인플레이션 압력', trend: 'up' },
    ],
    note: '강력한 데이터는 연준의 조기 금리 인하 기대를 냉각시키는 요인으로 작용했습니다.',
    theme: 'red',
    charts: [
      { ticker: 'TVC:US10Y', title: '미 10년물 국채금리' },
      { ticker: 'TVC:DXY', title: '달러 인덱스' },
    ],
  },
  {
    id: 4,
    type: 'headline',
    turnId: 9,
    title: "'좋은 뉴스가 나쁜 뉴스'가 된 이유",
    subtitle: '금리 인하 지연 가능성 부각',
    description: '강력한 고용은 경제 연착륙 가능성을 높이지만, 동시에 인플레이션 압력이 지속될 수 있다는 우려를 낳습니다. 이로 인해 시장이 기대했던 연준의 조기 금리 인하 명분이 약화되었습니다.',
    bullets: [
      '인플레이션 압력 지속 우려 증폭',
      'CME 페드워치 3월 금리 인하 가능성: 20% → 8% 미만으로 급락',
      '시장, 첫 금리 인하 시점을 6월 이후로 전망',
      '국채 금리 상승으로 성장주 중심의 기술주에 부담',
    ],
    theme: 'red',
  },
  {
    id: 5,
    type: 'headline',
    turnId: 11,
    title: '고용 보고서의 이면',
    subtitle: '숨겨진 약세 신호 관찰',
    description: '보고서의 헤드라인 숫자와 달리, 세부 내용을 보면 노동 시장의 기저 체력이 생각보다 강하지 않을 수 있다는 신호도 포착되었습니다.',
    bullets: [
      '고용 증가가 헬스케어 등 일부 업종에 집중',
      '2025년 연간 고용 증가치 대폭 하향 조정 (58.4만 → 18.1만)',
      '하향 조정된 수치는 경기 침체기를 제외하면 20년간 가장 약한 성장세',
    ],
    theme: 'amber',
  },
  {
    id: 6,
    type: 'headline',
    turnId: 14,
    icon: 'git-compare',
    title: '실적에 따른 극명한 희비',
    subtitle: 'AI 모멘텀 vs 실적 부진',
    description: '거시 경제의 불확실성이 커지자 투자자들은 개별 기업의 펀더멘털로 시선을 돌렸습니다. 확실한 성장 동력을 증명한 AI 관련 기업과 실망스러운 실적을 내놓은 기업 간의 주가 차별화가 극심하게 나타났습니다.',
    bullets: [
      '거시 경제 압박 속 개별 기업 실적 주목',
      'AI 테마 기업: 강력한 성장 가이던스로 주가 급등',
      '실적 부진 기업: 어닝 쇼크 및 부진한 전망에 주가 급락',
      '종목별 옥석 가리기 장세 심화',
    ],
    theme: 'purple',
  },
  {
    id: 7,
    type: 'comparison',
    turnId: 17,
    title: '실적 발표 후 주가 반응',
    description: '인공지능 관련 기업들은 미래 성장성을 증명하며 시장의 환호를 받은 반면, 부진한 실적과 전망을 내놓은 기업들은 냉정한 평가를 받았습니다.',
    items: [
      {
        label: '버티브 (VRT)',
        value: '+24%',
        description: 'AI 수요 기반 강력한 연간 가이던스 제시',
        highlight: true,
      },
      {
        label: '클라우드플레어 (NET)',
        value: '+5%',
        description: '예상 상회 실적 및 AI 트래픽 수혜 기대',
        highlight: true,
      },
      {
        label: '리프트 (LYFT)',
        value: '-17%',
        description: '예상 밖 영업손실 및 부진한 1분기 전망',
        highlight: false,
      },
      {
        label: '마텔 (MAT)',
        value: '-25%',
        description: '연말 시즌 어닝 쇼크 및 부정적 이익 가이던스',
        highlight: false,
      },
    ],
    charts: [
      { ticker: 'VRT' },
      { ticker: 'NET' },
      { ticker: 'LYFT' },
      { ticker: 'MAT' },
    ],
  },
  {
    id: 8,
    type: 'ticker-intro',
    turnId: 22,
    ticker: 'ASML',
    companyName: 'ASML Holding N.V.',
    currentPrice: 1446.50,
    dayChange: -4.50,
    dayChangePercent: -0.31,
    description: '반도체 EUV 노광 장비 독점 기업 ASML은 장 초반 강세를 보였으나, 시장 전반의 금리 부담과 밸류에이션 논쟁 속 상승분을 반납하고 소폭 하락 마감했습니다.',
    charts: [{ ticker: 'ASML' }],
  },
  {
    id: 9,
    type: 'ticker-analysis',
    turnId: 25,
    ticker: 'ASML',
    title: '핵심 기회: AI 시대의 독점적 지위',
    points: [
      '차세대 High-NA EUV 장비 상용화로 매출 및 이익률의 폭발적 성장 가능성',
      'TSMC, 인텔 등 주요 고객사의 2나노 이하 초미세 공정 경쟁의 핵심 수혜주',
      'AI 슈퍼 사이클 도래로 반도체 경기 순환성을 뛰어넘는 구조적 성장 기대',
    ],
    outlook: 'AI Momentum',
    outlookColor: 'emerald',
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 27,
    ticker: 'ASML',
    title: '주요 리스크: 고평가와 지정학적 변수',
    points: [
      '지정학적 리스크: 미중 기술 패권 경쟁 심화에 따른 대중국 수출 통제 가능성',
      '산업 주기성: AI 붐 이후 고객사들의 설비투자 축소 시 실적 타격 우려',
      '초고평가 부담: 미래의 긍정적 시나리오를 모두 선반영하여 안전마진이 부족하다는 분석',
    ],
    outlook: 'Valuation Risk',
    outlookColor: 'amber',
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 29,
    ticker: 'ASML',
    title: '종합 분석 요약',
    description: 'ASML의 독점적 기술력이라는 희망과 고평가, 지정학적 리스크라는 현실이 충돌하고 있습니다. 현재 주가는 잠재적 위험 요소를 충분히 반영하지 않은 수준으로 관찰됩니다.',
    points: [
      '독점적 기술력과 장기 성장 잠재력은 유효',
      '현재 주가는 미래의 긍정적 시나리오를 상당 부분 반영',
      '위대한 기업도 산업 사이클의 하강 국면에서는 자유로울 수 없다는 점을 유의할 필요',
    ],
    outlook: 'High Risk, High Reward',
    outlookColor: 'blue',
    charts: [{ ticker: 'ASML' }],
  },
  {
    id: 12,
    type: 'events',
    turnId: 33,
    title: '향후 주요 경제 지표',
    description: '시장의 단기 방향성을 결정할 핵심 경제 지표 발표가 예정되어 있어 투자자들의 관심이 집중되고 있습니다.',
    events: [
      {
        date: '2월 13일 (금)',
        label: '소비자물가지수 (CPI) 발표',
        description: '연준의 금리 인하 시점 결정에 가장 중요한 변수로 작용할 전망입니다.',
      },
      {
        date: '2월 18일 (수)',
        label: 'FOMC 의사록 공개',
        description: '금리 경로에 대한 연준 위원들 간의 미묘한 시각차를 확인할 수 있습니다.',
      },
    ],
  },
  {
    id: 13,
    type: 'closing',
    turnId: 37,
    headline: '변동성 장세, 거시 경제 흐름에 주목',
    tagline: '2026년 2월 11일 장마감 브리핑',
    description: '시장은 주요 경제 지표 발표를 앞두고 중요한 갈림길에 서 있습니다. 단기적인 변동성에 일희일비하기보다, 거시 경제의 큰 흐름을 읽으려는 노력이 필요한 시점입니다. 핵심 지표 발표 전후로 변동성이 커질 수 있으므로 차분한 대응 전략이 유효해 보입니다.',
  },
];