import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-02-05',
    nutshell: '경기 둔화 우려와 기술주 불안에 따른 시장 전반의 하락',
    description: '예상보다 약한 고용 지표가 경기 침체 공포를 자극하고, AI 기술 발전이 오히려 기존 소프트웨어 기업의 수익 모델을 위협할 수 있다는 우려가 더해지며 투자 심리가 급격히 위축되었습니다. 시장의 관심이 연준의 금리 정책에서 실물 경제의 건강 상태로 옮겨가는 모습을 보였습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '주요 지수가 모두 1% 넘게 하락하는 힘든 하루였습니다. 경기 둔화 우려가 금리 인하 기대감을 압도하며 안전자산 선호 심리가 강해졌습니다.',
    indices: [
      { name: 'S&P 500', value: 6798, change: -84.68, changePercent: -1.23 },
      { name: 'NASDAQ', value: 22540, change: -362.89, changePercent: -1.59 },
    ],
    commodities: [
      { name: '10년물 국채금리', value: 4.21, change: -0.05, changePercent: -1.17 },
      { name: 'VIX', value: 21.00, change: 2.90, changePercent: 16.02 },
      { name: '금', value: 2250.30, change: -67.50, changePercent: -2.90 },
      { name: '은', value: 25.10, change: -4.78, changePercent: -16.00 },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 6,
    icon: 'trending-down',
    title: '고용 쇼크와 경기 침체 공포',
    subtitle: '나쁜 뉴스가 ‘나쁜 뉴스’로 받아들여지다',
    description: '12월 구인 건수가 2020년 이후 최저 수준으로 떨어지자, 시장의 해석이 완전히 달라졌습니다. 노동 시장 냉각을 넘어 동결 가능성까지 제기되며, 금리 인하 기대감보다 경기 침체 공포가 시장을 지배했습니다.',
    bullets: [
      '12월 구인 건수: 654만 건 (예상 720만 건 하회)',
      '신규 실업수당 청구: 23.1만 건 (예상 상회)',
      'VIX 지수 16% 이상 급등하며 21선 돌파',
      '안전자산 선호에 10년물 국채 금리 4.21%까지 하락',
    ],
    theme: 'red',
  },
  {
    id: 3,
    type: 'stats',
    turnId: 7,
    title: '주요 경제 지표 동향',
    description: '예상보다 약한 고용 관련 지표들이 연달아 발표되면서, 시장 참여자들은 본격적으로 경기 침체 위험을 가격에 반영하기 시작했습니다.',
    stats: [
      { label: 'JOLTS 구인 건수', value: '654만 건', subtext: '2020년 9월 이후 최저', trend: 'down' },
      { label: '신규 실업수당 청구', value: '23.1만 건', subtext: '예상 상회', trend: 'up' },
      { label: 'VIX 변동성 지수', value: '+16%', subtext: '공포 심리 확산', trend: 'up' },
      { label: '10년물 국채 금리', value: '4.21%', subtext: '안전자산 선호', trend: 'down' },
    ],
    theme: 'red',
    charts: [
      { ticker: 'SP:SPX', title: 'S&P 500' },
      { ticker: 'NASDAQ:IXIC', title: 'NASDAQ' },
      { ticker: 'TVC:US10Y', title: '10-Year Treasury Yield' },
      { ticker: 'TVC:VIX', title: 'VIX Index' },
    ],
  },
  {
    id: 4,
    type: 'headline',
    turnId: 9,
    title: '방어주로의 자금 이동',
    subtitle: '경기 방어적 움직임 뚜렷',
    description: '투자자들이 향후 경제 활동 위축에 대비해 포트폴리오를 조정하는 모습이 명확히 나타났습니다. 산업재와 임의 소비재 같은 경기 민감 섹터는 하락한 반면, 유틸리티와 필수 소비재 등 방어주 섹터는 선방했습니다.',
    theme: 'red',
    charts: [
      { ticker: 'XLI', title: '산업재 섹터' },
      { ticker: 'XLY', title: '임의 소비재 섹터' },
      { ticker: 'XLU', title: '유틸리티 섹터' },
      { ticker: 'XLP', title: '필수 소비재 섹터' },
    ],
  },
  {
    id: 5,
    type: 'headline',
    turnId: 14,
    icon: 'cpu',
    title: 'AI의 역습: 창조적 파괴 공포',
    subtitle: '기술 발전이 기존 소프트웨어 기업을 위협하다',
    description: '아마존과 구글의 지원을 받는 AI 기업 앤트로픽의 신규 모델 출시가 기존 소프트웨어 산업을 잠식할 것이라는 공포를 확산시키며 기술주 전반의 하락을 이끌었습니다. 이는 AI 기술의 양면성을 보여준 하루였습니다.',
    bullets: [
      '앤트로픽, 신규 AI 모델 출시로 경쟁 심화',
      '기존 소프트웨어 산업 ‘창조적 파괴’ 우려 확산',
      '팰런티어(PLTR) 주가 6.5% 이상 급락',
      '기술주 중심 XLK ETF 2% 이상 하락하며 시장 하락 주도',
    ],
    theme: 'purple',
  },
  {
    id: 6,
    type: 'stats',
    turnId: 17,
    title: '소프트웨어 기업 주가 동반 하락',
    description: '앤트로픽의 새 AI 모델이 IT 컨설팅 및 서비스형 소프트웨어(SaaS) 기업의 핵심 수익 모델을 직접적으로 위협할 수 있다는 우려가 관련 기업들의 주가를 끌어내렸습니다.',
    stats: [
      { label: 'ServiceNow (NOW)', value: '-5.7%', trend: 'down' },
      { label: 'Accenture (ACN)', value: '-3.4%', trend: 'down' },
      { label: 'Salesforce (CRM)', value: '-3.0%', trend: 'down' },
    ],
    note: '월가에서는 AI가 정교한 업무를 대체하며 ‘라이선스 모델의 종말’이 올 수 있다는 경고가 나오고 있습니다.',
    theme: 'purple',
    charts: [
      { ticker: 'NOW', title: 'ServiceNow' },
      { ticker: 'ACN', title: 'Accenture' },
      { ticker: 'CRM', title: 'Salesforce' },
    ],
  },
  {
    id: 7,
    type: 'headline',
    turnId: 19,
    title: '빅테크의 딜레마',
    subtitle: 'AI 선두주자도 피하지 못한 충격',
    description: '마이크로소프트와 구글 역시 AI 기술의 선두주자인 동시에, 기존의 거대한 소프트웨어 사업을 지켜야 하는 딜레마에 빠졌습니다. 막대한 투자 비용과 기존 사업의 잠식 위험이라는 두 가지 리스크가 부각되며 주가가 하락했습니다.',
    bullets: [
      'Microsoft (MSFT) 주가 1.8% 하락',
      'Google (GOOGL) 주가 2.2% 하락',
      '천문학적인 AI 개발 및 데이터센터 투자 비용 부담',
      '신기술이 기존 캐시카우 사업을 잠식할 수 있다는 우려',
    ],
    theme: 'purple',
    charts: [
      { ticker: 'MSFT', title: 'Microsoft' },
      { ticker: 'GOOGL', title: 'Google' },
    ],
  },
  {
    id: 8,
    type: 'headline',
    turnId: 22,
    icon: 'building',
    title: '개별 기업 악재와 비트코인 급락',
    subtitle: '시장 하락세를 부채질한 요인들',
    description: '거시 경제 불안과 기술 산업 우려에 더해, 일부 기업들의 실망스러운 전망과 비트코인 급락이 시장 전반의 위험 회피 심리를 자극하며 연쇄 반응을 일으켰습니다.',
    bullets: [
      '아마존(AMZN), 대규모 투자 계획에 주가 4.4% 하락',
      '비트코인(BTC) 급락, 관련주 마이크로스트래티지(MSTR) 17% 폭락',
      '펠로톤(PTON), 부진한 실적에 25% 이상 급락',
      '로블록스(RBLX)는 예상을 뛰어넘는 실적으로 급등하며 옥석 가리기 장세 연출',
    ],
    theme: 'blue',
  },
  {
    id: 9,
    type: 'stats',
    turnId: 25,
    title: '아마존(AMZN): 미래 투자 부담감',
    description: '견조한 4분기 실적에도 불구하고, 예상을 훨씬 뛰어넘는 2026년 투자 계획이 발표되면서 단기 수익성 악화에 대한 우려로 주가가 4.4% 이상 하락했습니다.',
    stats: [
      { label: '4분기 매출', value: '$2,133억', subtext: '예상 상회', trend: 'up' },
      { label: '2026년 투자 계획', value: '약 $2,000억', subtext: '월가 예상(1,400억) 대폭 상회', trend: 'neutral' },
      { label: '주가', value: '-4.4%', subtext: '수익성 악화 우려', trend: 'down' },
    ],
    theme: 'blue',
    charts: [{ ticker: 'AMZN', title: 'Amazon' }],
  },
  {
    id: 10,
    type: 'stats',
    turnId: 27,
    title: '비트코인 급락의 여파',
    description: '비트코인 가격이 7만 달러 아래로 떨어지자, 비트코인을 대량 보유한 마이크로스트래티지의 주가가 실적 발표와 맞물려 17% 넘게 폭락했습니다.',
    stats: [
      { label: '비트코인(BTC) 가격', value: '$67,000선 하회', trend: 'down' },
      { label: '마이크로스트래티지(MSTR) 주가', value: '-17%', trend: 'down' },
      { label: 'MSTR 4분기 영업손실', value: '$174억', subtext: 'BTC 평가가치 하락 반영', trend: 'down' },
    ],
    theme: 'blue',
    charts: [
      { ticker: 'MSTR', title: 'MicroStrategy' },
      { ticker: 'BTC-USD', title: 'Bitcoin' },
    ],
  },
  {
    id: 11,
    type: 'ticker-intro',
    turnId: 30,
    ticker: 'TSLA',
    companyName: 'Tesla, Inc.',
    currentPrice: 394.50,
    dayChange: 0.00,
    dayChangePercent: 0.00,
    description: '테슬라 주가는 장중 402달러와 387달러 사이를 오가는 극심한 변동성 끝에 보합으로 마감했습니다. 이는 회사를 둘러싼 AI 기업으로서의 기대감과 자동차 사업의 펀더멘털 악화 우려가 팽팽하게 맞서는 상황을 반영합니다.',
    charts: [{ ticker: 'TSLA', title: 'Tesla Inc.' }],
  },
  {
    id: 12,
    type: 'comparison',
    turnId: 31,
    title: '테슬라를 둘러싼 두 가지 시선',
    description: '테슬라의 현재와 미래를 보는 시각이 극명하게 엇갈리며 주가 변동성을 키우고 있습니다. 투자자들은 흔들리는 핵심 사업과 불확실한 미래 비전 사이에서 치열한 논쟁을 벌이고 있습니다.',
    items: [
      {
        label: '우려',
        value: '펀더멘털 악화',
        description: '2025년 순이익 반토막, 유럽 시장 점유율 하락 등 핵심인 자동차 사업의 기반이 흔들리고 있다는 현실적인 우려가 제기됩니다.',
        highlight: true,
      },
      {
        label: '기대',
        value: 'AI 플랫폼으로의 도약',
        description: '현재의 실적 악화는 로보택시, 옵티머스 등 미래 기술 투자를 위한 성장통이며, AI 기업으로 거듭날 것이라는 기대감이 존재합니다.',
        highlight: false,
      },
    ],
  },
  {
    id: 13,
    type: 'ticker-analysis',
    turnId: 35,
    ticker: 'TSLA',
    title: '주요 리스크 요인',
    points: [
      '**위험한 자본 배분**: 2025년 순이익(38억 달러)의 두 배가 넘는 유형자산 투자(85억 달러)로 1~2년 내 현금흐름 고갈 가능성이 제기됩니다.',
      '**심각한 법적 리스크**: 완전자율주행(FSD) 기능과 관련해 미 법무부(DOJ)와 증권거래위원회(SEC)의 조사를 받고 있으며, 이는 막대한 벌금으로 이어질 수 있는 위협입니다.',
      '**핵심 사업 경쟁 심화**: 유럽 전기차 시장에서 폭스바겐에 판매량 1위 자리를 내주는 등 경쟁 환경이 악화되고 있습니다.',
    ],
    outlook: 'High Risk',
    outlookColor: 'rose',
  },
  {
    id: 14,
    type: 'ticker-analysis',
    turnId: 37,
    ticker: 'TSLA',
    title: '종합 분석 요약',
    description: '로보택시, 옵티머스 등 AI 기반의 성장 스토리는 여전히 유효하지만, 현재로서는 가시적인 위험이 잠재적 기회보다 더 부각되는 상황으로 관찰됩니다.',
    points: [
      '성장 스토리는 회사의 선언과 미래 가능성에 기반합니다.',
      '위험 요인들은 재무제표, 공식 보고서, 시장 경쟁 등 객관적 사실에 근거하고 있습니다.',
      '핵심 사업 기반이 무너지거나 법적 책임이 현실화될 경우, 기업 가치가 영구적으로 훼손될 가능성이 제기됩니다.',
    ],
    outlook: 'Caution Required',
    outlookColor: 'amber',
  },
  {
    id: 15,
    type: 'events',
    turnId: 41,
    title: '향후 주목해야 할 주요 경제 지표',
    description: '시장의 관심은 연준의 정책 경로를 가늠할 수 있는 고용 및 물가 지표에 집중될 것입니다. 이 지표들의 결과에 따라 시장의 방향성이 좀 더 명확해질 전망입니다.',
    events: [
      { date: '2026-02-10', label: '소매 판매 (Retail Sales)', description: '소비 심리 위축 및 실질 수요 감소 여부 확인' },
      { date: '2026-02-11', label: '비농업 고용 지표 (Non-Farm Payrolls)', description: '노동 시장의 열기 지속 여부 판단' },
      { date: '2026-02-12', label: '30년물 국채 입찰 (30-year Bond Auction)', description: '장기 금리 및 시장 심리 파악' },
      { date: '2026-02-13', label: '소비자물가지수 (CPI)', description: '인플레이션 둔화 추세 지속 여부 확인' },
      { date: '2026-02-18', label: 'FOMC 의사록 공개 (FOMC Minutes)', description: '연준의 정책 경로에 대한 힌트' },
    ],
  },
  {
    id: 16,
    type: 'closing',
    turnId: 45,
    headline: '지표를 확인하며 대응할 시기',
    tagline: '2026년 2월 5일 장마감 브리핑',
    description: '시장이 연준과 힘겨루기를 하는 모습이 이어질 것으로 보입니다. 변동성이 커질 수 있는 시기인 만큼, 섣부른 예측보다는 발표되는 지표들을 차분히 확인하며 대응하는 지혜가 필요해 보입니다.',
  },
];