import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-02-09',
    nutshell: 'AI 투자 열풍 속 기술주 랠리 재점화',
    description: 'S&P 500과 나스닥 지수가 사상 최고치를 경신하며 시장의 강한 상승세를 보였습니다. 알파벳의 대규모 AI 데이터센터 투자 소식이 기술주 중심의 랠리를 이끌었습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: 'S&P 500 지수가 사상 처음으로 6900선을 돌파하고 나스닥도 신고가를 기록했습니다. 다우존스는 보합에 머물러, 상승 동력이 AI 관련 기술주에 집중되는 모습을 보였습니다.',
    indices: [
      { name: 'S&P 500', value: 6964.82, change: 32.59, changePercent: 0.47 },
      { name: 'NASDAQ', value: 23238.67, change: 207.28, changePercent: 0.90 },
      { name: 'DOW', value: 45018.00, change: 18.00, changePercent: 0.04 },
    ],
    commodities: [
      { name: 'WTI Crude', value: 64.20, change: 0.85, changePercent: 1.34 },
      { name: 'Dollar Index', value: 103.25, change: -0.25, changePercent: -0.24 },
      { name: '10Y Yield', value: 4.18, change: -0.02, changePercent: -0.48 },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 7,
    icon: 'cpu',
    title: 'AI 골드러시 현상',
    subtitle: '거대 자본, AI 인프라로 집중',
    description: '알파벳의 대규모 채권 발행 흥행과 데이터브릭스의 높은 기업가치 평가는 AI 생태계로 막대한 자금이 유입되고 있음을 보여줍니다. 이는 반도체 섹터를 비롯한 기술주 전반의 상승을 견인했습니다.',
    bullets: [
      '알파벳 $200억 채권 발행, $1000억 이상 주문 쇄도',
      '데이터브릭스, $50억 투자 유치하며 기업가치 $1340억 인정',
      '반도체 ETF (SOXX) +1.2% 이상 상승',
      '모건 스탠리, "AI가 이끄는 랠리 지속 가능" 분석',
    ],
    theme: 'gold',
  },
  {
    id: 3,
    type: 'stats',
    turnId: 9,
    title: 'AI 골드러시의 \'곡괭이와 삽\'',
    description: '투자의 초점이 단순 기대감을 넘어 데이터센터, AI 칩 등 실제 인프라 구축으로 이동하고 있습니다. AI 연산 능력 확보를 위한 기업들의 경쟁이 치열해지는 양상입니다.',
    stats: [
      { label: '퍼머스 (AI 인프라)', value: '$100억', subtext: '블랙스톤 등 자금 조달', trend: 'up' },
      { label: '엔비디아 (NVDA)', value: '+2.5%', subtext: 'AI 칩 선두주자 주가 상승', trend: 'up' },
      { label: '마벨 테크놀로지 (MRVL)', value: '+2.5%', subtext: '아마존 AI칩 제조사', trend: 'up' },
      { label: 'xAI (비상장)', value: '$34억', subtext: '칩 구매 자금 대출 추진', trend: 'neutral' },
    ],
    theme: 'gold',
  },
  {
    id: 4,
    type: 'headline',
    turnId: 11,
    title: '과열 속 옥석 가리기',
    subtitle: 'AI 테마 내 차별화 시작',
    description: 'AI에 대한 기대감이 투기적인 모습으로 나타나기도 하지만, 시장은 점차 구체적인 사업 모델과 경쟁력을 기준으로 옥석을 가리는 단계로 진입하고 있습니다.',
    bullets: [
      '\'ai.com\' 도메인, 사상 최고가 $7000만 달러에 거래',
      '일부 소프트웨어 주식, AI 위협론에 조정 경험',
      '알파벳(GOOGL), 대규모 투자에도 소송 리스크로 주가 소폭 하락',
      'AI 테마 안에서도 주가 흐름 차별화 관측',
    ],
    theme: 'gold',
    charts: [{ ticker: 'NASDAQ:GOOGL', title: 'Alphabet Inc.' }],
  },
  {
    id: 5,
    type: 'headline',
    turnId: 13,
    title: '구조적 변화에 베팅하는 시장',
    subtitle: '실질적 승자 찾기 여정의 시작',
    description: '시장은 AI가 가져올 구조적 변화에 베팅하며, AI 기술을 구현하고 확산시키는 기업들에 대한 신뢰를 보이고 있습니다. 안정적인 국채 금리는 이러한 성장주 중심의 랠리를 뒷받침했습니다.',
    bullets: [
      '마이크로소프트(MSFT) +3% 이상 상승하며 랠리 주도',
      '기술주 ETF (XLK) +1.5% 이상 상승',
      '10년물 국채 금리 안정세, 성장주 랠리에 우호적 환경 조성',
    ],
    theme: 'gold',
    charts: [
      { ticker: 'NASDAQ:MSFT', title: 'Microsoft Corp.' },
      { ticker: 'AMEX:XLK', title: 'Technology Select Sector SPDR Fund' },
      { ticker: 'TVC:US10Y', title: 'US 10-Year Treasury Yield' },
    ],
  },
  {
    id: 6,
    type: 'headline',
    turnId: 15,
    icon: 'trending-up',
    title: '소프트웨어주의 반격',
    subtitle: '\'사스포칼립스\' 우려 딛고 반등',
    description: 'AI가 기존 구독 모델을 파괴할 것이라는 우려로 약세를 보였던 소프트웨어 섹터가 강하게 반등했습니다. AI에 대한 공포가 과도했다는 인식과 함께 저가 매수세가 유입된 결과로 분석됩니다.',
    bullets: [
      '\'사스포칼립스(SaaSpocalypse)\' 우려로 최근 약세',
      '소프트웨어 ETF (IGV) +3% 이상 급등하며 분위기 반전',
      '안정된 거시 환경(달러 약세, VIX 하락) 속 저가 매수세 유입',
    ],
    theme: 'green',
    charts: [
      { ticker: 'BATS:IGV', title: 'iShares Expanded Tech-Software Sector ETF' },
      { ticker: 'TVC:VIX', title: 'Volatility Index' },
    ],
  },
  {
    id: 7,
    type: 'comparison',
    turnId: 17,
    title: 'AI: 파괴자인가, 증강 요인인가?',
    description: '시장의 관점이 AI를 기존 소프트웨어의 파괴자로 보는 공포에서, 오히려 효율성을 높이는 증강 요인으로 보는 합리적인 시각으로 전환되었습니다.',
    items: [
      {
        label: '비관론 (파괴자)',
        value: '사업 모델 대체',
        description: '신규 AI 모델이 기존 소프트웨어를 대체할 것이라는 우려',
        highlight: false,
      },
      {
        label: '낙관론 (증강 요인)',
        value: '효율성 증대',
        description: 'AI가 기존 서비스에 통합되어 가치를 높일 것이라는 분석 (바클레이즈 등)',
        highlight: true,
      },
    ],
  },
  {
    id: 8,
    type: 'stats',
    turnId: 19,
    title: '과매도 인식 속 강한 반발 매수',
    description: 'AI 위협론으로 낙폭이 컸던 종목들을 중심으로 기회주의적 매수세가 유입되며 강한 반등이 나타났습니다. 이는 단기적인 주가 하락이 과도했다는 시장의 공감대를 보여줍니다.',
    stats: [
      { label: '삼사라 (IOT)', value: '+7% 이상', trend: 'up' },
      { label: '줌인포 (ZI)', value: '+3.7%', trend: 'up' },
      { label: '빌닷컴 (BILL)', value: '+3.7%', trend: 'up' },
      { label: '디지털오션 (DOCN)', value: '+3% 가까이', trend: 'up' },
    ],
    theme: 'green',
  },
  {
    id: 9,
    type: 'headline',
    turnId: 21,
    title: '아직 끝나지 않은 힘겨루기',
    subtitle: '소프트웨어 섹터의 불확실성은 여전',
    description: '오늘의 반등에도 불구하고, 소프트웨어 ETF의 높은 내재 변동성과 공매도 비중은 미래를 둘러싼 강세론자와 약세론자의 힘겨루기가 계속될 것임을 시사합니다.',
    bullets: [
      '소프트웨어 ETF(IGV)의 내재 변동성 및 공매도 비중 여전히 높은 수준',
      '강세론 vs 약세론 힘겨루기 지속 전망',
      'AI를 성공적으로 통합하는 기업만이 시장의 신뢰를 얻을 것으로 예상',
    ],
    theme: 'green',
    charts: [{ ticker: 'BATS:IGV', title: 'iShares Expanded Tech-Software Sector ETF' }],
  },
  {
    id: 10,
    type: 'ticker-intro',
    turnId: 22,
    ticker: 'GS',
    companyName: 'Goldman Sachs',
    currentPrice: 943.61,
    dayChange: 14.58,
    dayChangePercent: 1.57,
    description: '골드만삭스가 1.57% 상승 마감하며 강한 모습을 보였습니다. 장중 한때 949달러까지 오르며 시장의 주목을 받았습니다.',
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 23,
    ticker: 'GS',
    title: '핵심 관전 포인트: 성장 잠재력 vs 재무 리스크',
    description: '골드만삭스는 금융 인프라 기술 기업으로의 변신을 꾀하고 있으나, 신사업의 막대한 손실과 법적 리스크가 공존하며 기대와 우려가 교차하는 상황입니다.',
    points: [
      '\'플랫폼 솔루션\' 신사업 부문을 통한 미래 성장 기대감',
      '신사업에서 발생하는 막대한 누적 손실 부담',
      '과거부터 이어진 여러 소송 관련 법적 리스크 상존',
    ],
    outlook: 'High Risk, High Return',
    outlookColor: 'amber',
  },
  {
    id: 12,
    type: 'ticker-analysis',
    turnId: 25,
    ticker: 'GS',
    title: '기회 요인: 금융계의 AWS를 향한 비전',
    description: '긍정적 관점에서는 플랫폼 솔루션 사업을 미래 시장 지배력을 위한 R&D 투자로 보고 있습니다. 저수익 사업을 정리하고 고수익 B2B 플랫폼에 집중하는 전략적 전환이라는 평가입니다.',
    points: [
      '플랫폼 솔루션 순수익, 2년간 60% 이상 성장하며 외형 확장',
      '소비자 금융 축소는 고수익 B2B 플랫폼 집중 전략으로 해석',
      '현재의 손실은 미래 시장 지배력 확보를 위한 과정이라는 시각 존재',
    ],
    outlook: 'Potential Transformation',
    outlookColor: 'purple',
  },
  {
    id: 13,
    type: 'ticker-analysis',
    turnId: 27,
    ticker: 'GS',
    title: '리스크 요인: 현실화된 손실과 잠재적 부채',
    description: '신중한 접근을 요구하는 부분은 플랫폼 솔루션 사업부의 막대한 누적 손실과 아직 재무제표에 완전히 반영되지 않은 추가적인 법적 손실 가능성입니다.',
    points: [
      '플랫폼 솔루션 사업부, 지난 3년간 약 $52억 누적 손실 기록',
      'SVB, 아케고스 사태 등과 연관된 소송으로 약 $17억 추가 손실 가능성',
      '재무제표에 미반영된 잠재적 위험이 현실화될 경우 주주가치 훼손 우려',
    ],
    outlook: 'Significant Headwinds',
    outlookColor: 'rose',
  },
  {
    id: 14,
    type: 'ticker-analysis',
    turnId: 29,
    ticker: 'GS',
    title: '종합 분석 요약',
    description: '골드만삭스는 전통 사업의 이익으로 성공이 불확실한 신사업의 손실을 메우는 구조입니다. 현재 주가는 입증된 위험 요소보다 미래 성공 가능성을 더 비중 있게 반영하고 있는 것으로 관측됩니다.',
    points: [
      '전통 사업 이익으로 신사업 손실을 충당하는 구조',
      '대형 은행의 기술 기업 전환 성공 선례 부족에 따른 실행 리스크',
      '현재 밸류에이션은 플랫폼 부문 손실과 우발 부채 리스크를 충분히 반영했는지 고려 필요',
    ],
    outlook: 'Valuation Caution',
    outlookColor: 'amber',
  },
  {
    id: 15,
    type: 'events',
    turnId: 35,
    title: '다음 주 주요 경제 이벤트',
    description: '사상 최고치를 경신한 시장의 다음 행보는 연준의 금리 인하 경로에 대한 단서를 제공할 물가 지표 발표에 따라 결정될 전망입니다.',
    events: [
      {
        date: '2월 13일',
        label: '1월 소비자물가지수 (CPI) 발표',
        description: '연준 금리 인하 시기의 핵심 단서',
      },
      {
        date: '2월 18일',
        label: 'FOMC 의사록 공개',
        description: '금리 인하에 대한 위원들 간의 시각차 확인',
      },
      {
        date: '2월 20일',
        label: '개인소비지출 (PCE) 가격지수 발표',
        description: '연준이 가장 중시하는 물가 지표',
      },
    ],
  },
  {
    id: 16,
    type: 'closing',
    turnId: 36,
    headline: '사상 최고치 경신, 이제 시선은 물가로',
    tagline: '2026년 2월 9일 장마감 브리핑',
    description: '견조한 기업 실적과 AI 낙관론에 힘입어 사상 최고치를 경신한 시장이 다음 주 발표될 물가 지표라는 중요한 분수령을 앞두고 있습니다.',
  },
];