import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-02-03',
    nutshell: '엇갈린 빅테크 실적에 나스닥 하락 반전',
    description: '빅테크 기업들의 4분기 실적이 극명하게 엇갈리며 기술주 중심의 나스닥 지수가 하락했습니다. AI 수혜주 팔란티어는 급등했지만, 페이팔은 부진한 전망에 폭락하며 소프트웨어 섹터 전반의 투자 심리를 위축시켰습니다. 엔비디아 또한 핵심 고객 관련 우려가 제기되며 하락 마감했습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '주요 지수는 빅테크 실적 발표 여파로 혼조세를 보였습니다. 특히 나스닥의 낙폭이 두드러졌으며, 중소형주는 상대적으로 선방하는 모습을 보였습니다.',
    indices: [
      { name: 'S&P 500', value: 5850.21, change: -49.54, changePercent: -0.84 },
      { name: 'NASDAQ', value: 17542.88, change: -254.24, changePercent: -1.43 },
      { name: 'DOW', value: 42150.62, change: -143.31, changePercent: -0.34 },
      { name: 'Russell 2000', value: 2102.50, change: 2.10, changePercent: 0.10 },
    ],
    commodities: [],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
      { ticker: 'TVC:RUT' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 7,
    icon: 'trending-up-down',
    title: '엇갈린 실적, 엇갈린 운명',
    subtitle: '팔란티어 급등 vs 페이팔 급락',
    description: '시장은 개별 기업의 실적에 따라 냉정하게 반응했습니다. AI 성장성을 증명한 팔란티어는 급등했지만, 실망스러운 전망을 내놓은 페이팔은 폭락하며 관련 섹터의 동반 하락을 이끌었습니다.',
    bullets: [
      '팔란티어(PLTR): AI 수요에 힘입어 +6.8% 급등',
      '페이팔(PYPL): 부진한 전망에 -20% 이상 폭락',
      '소프트웨어 ETF(IGV): -4.6% 하락',
      '핀테크 ETF(FINX): -6.0% 급락',
    ],
    theme: 'purple',
  },
  {
    id: 3,
    type: 'stats',
    turnId: 9,
    title: '팔란티어(PLTR): AI가 현실로',
    description: '팔란티어는 시장 예상을 뛰어넘는 폭발적인 성장세를 보이며 AI 플랫폼(AIP)의 상업적 성공 가능성을 입증했습니다.',
    stats: [
      { label: '4분기 매출', value: '$14.1억', subtext: 'YoY +70%', trend: 'up' },
      { label: '미국 상업 부문 매출', value: '+137%', subtext: 'AIP 도입 가속화', trend: 'up' },
      { label: '미국 정부 부문 매출', value: '+66%', subtext: '견고한 수요 지속', trend: 'up' },
    ],
    note: '긍정적인 연간 매출 전망까지 제시하며 AI 성장 스토리에 대한 자신감을 보였습니다.',
    theme: 'green',
    charts: [{ ticker: 'PLTR' }],
  },
  {
    id: 4,
    type: 'stats',
    turnId: 11,
    title: '페이팔(PYPL): 무너진 성장 기대감',
    description: '페이팔은 시장 기대에 크게 못 미치는 연간 수익 전망을 발표하고 CEO 교체 소식까지 더해지며 투자 심리가 급격히 악화되었습니다.',
    stats: [
      { label: '2026년 이익 전망', value: '소폭 감소~정체', subtext: '시장 기대치(+8%) 크게 하회', trend: 'down' },
      { label: '브랜드 결제 성장률', value: '1%', subtext: '전년 동기 6%에서 급감', trend: 'down' },
      { label: '리더십', value: 'CEO 교체', subtext: '경영 불확실성 증대', trend: 'down' },
    ],
    note: '핵심 사업의 성장 둔화와 리더십 교체가 맞물리며 주가가 폭락했습니다.',
    theme: 'red',
    charts: [{ ticker: 'PYPL' }],
  },
  {
    id: 5,
    type: 'comparison',
    turnId: 13,
    title: 'AI 시대의 명암: 실적으로 증명하라',
    description: '같은 기술 섹터 내에서도 실제 성과를 내는 기업과 그렇지 못한 기업의 희비가 극명하게 갈렸습니다. 시장은 더 이상 막연한 기대감이 아닌 구체적인 실적을 요구하고 있습니다.',
    items: [
      {
        label: 'Palantir (PLTR)',
        value: '+6.8%',
        description: 'AI 기술의 상업적 성공 증명, 긍정적 전망 제시',
        highlight: true,
      },
      {
        label: 'PayPal (PYPL)',
        value: '-20.4%',
        description: '성장 둔화 우려, 리더십 불확실성, 핀테크 전반 우려 확산',
        highlight: false,
      },
    ],
  },
  {
    id: 6,
    type: 'headline',
    turnId: 19,
    icon: 'alert-triangle',
    title: '페이팔 쇼크, 업계 전반으로 확산',
    subtitle: '핀테크와 소프트웨어 섹터의 동반 부진',
    description: '페이팔의 부진은 단순한 개별 기업의 문제를 넘어, 온라인 소비 둔화와 소프트웨어 산업의 구조적 위기라는 두려움을 자극하며 관련 섹터 전반의 투매를 유발했습니다.',
    bullets: [
      '광산 속 카나리아: 페이팔의 부진이 핀테크 산업 전체의 경고로 해석',
      '경쟁 심화 우려: 블록(SQ), 어펌(AFRM) 등 동종 기업 주가 동반 하락',
      'SaaSpocalypse 공포: AI가 기존 SaaS 비즈니스 모델을 위협할 수 있다는 우려 확산',
    ],
    theme: 'red',
    charts: [
      { ticker: 'FINX', title: 'Fintech ETF' },
      { ticker: 'IGV', title: 'Software ETF' },
    ],
  },
  {
    id: 7,
    type: 'ticker-intro',
    turnId: 22,
    ticker: 'NVDA',
    companyName: 'NVIDIA Corp.',
    currentPrice: 873.20,
    dayChange: -27.00,
    dayChangePercent: -3.00,
    description: 'AI 칩 선두주자 엔비디아는 핵심 고객인 OpenAI가 일부 칩 성능에 만족하지 못하고 대안을 찾고 있다는 보도가 나오면서 주가가 3% 넘게 하락했습니다.',
    charts: [{ ticker: 'NVDA' }],
  },
  {
    id: 8,
    type: 'ticker-analysis',
    turnId: 25,
    ticker: 'NVDA',
    title: '독점 체제의 균열 가능성',
    points: [
      '핵심 고객 OpenAI, 특정 \'추론\' 작업에서 칩 성능 불만 제기',
      'AI 시장의 다음 격전지인 \'추론\' 시장에서 CUDA의 영향력이 상대적으로 약할 수 있다는 분석',
      '매출의 61%가 단 4개 고객사에 집중되어 있어 고객 이탈 리스크 부각',
      '\'고객이 곧 경쟁자\'가 될 수 있는 구조적 위협 현실화 가능성',
    ],
    description: '이번 보도는 그동안 엔비디아의 아킬레스건으로 지적되던 고객 집중 리스크와 추론 시장에서의 경쟁 심화 우려를 수면 위로 끌어올렸습니다.',
  },
  {
    id: 9,
    type: 'ticker-analysis',
    turnId: 27,
    ticker: 'NVDA',
    title: '위기인가, 성장통인가?',
    points: [
      '까다로운 고객의 요구는 차세대 아키텍처 개발의 이정표 역할 가능',
      'OpenAI IPO 투자 검토는 핵심 파트너와의 생태계를 공고히 하려는 전략으로 해석 가능',
      '경쟁사는 개별 칩으로 경쟁하지만, 엔비디아는 통합 플랫폼(HW+SW+네트워킹)으로 경쟁',
      '단기적 잡음보다는 장기적인 플랫폼 경쟁력에 주목해야 한다는 시각',
    ],
    description: '반면, 이번 사건을 더 큰 시장으로 나아가기 위한 성장통으로 보는 시각도 존재합니다. 핵심 고객과의 협력을 통해 기술 로드맵을 공유하고 플랫폼 지배력을 강화할 기회라는 분석입니다.',
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 29,
    ticker: 'NVDA',
    title: '종합 분석: 불확실성 증가',
    points: [
      '장기 성장 가능성은 유효하나, 단기적 불확실성은 명백히 증가한 상황.',
      '이론으로만 존재하던 고객 집중 리스크와 경쟁 심화 위협이 현실화.',
      '매수 측의 플랫폼 논리와 매도 측의 구조적 위협 논리가 팽팽히 맞서는 국면.',
    ],
    outlook: 'Increased Competition Risk',
    outlookColor: 'amber',
    description: '향후 다른 대형 고객사들의 움직임과 차세대 제품이 추론 시장의 우려를 해소할 수 있을지 확인하며 신중한 접근이 필요한 시점으로 판단됩니다.',
  },
  {
    id: 11,
    type: 'events',
    turnId: 35,
    title: '이번 주 주목할 경제 지표',
    description: '이번 주는 고용 시장의 온도를 확인할 수 있는 핵심 지표들이 연이어 발표됩니다. 특히 금요일 발표될 고용 보고서는 연준의 향후 정책 방향에 대한 중요한 단서를 제공할 것입니다.',
    events: [
      {
        date: '2월 4일 (수)',
        label: 'ADP 민간 고용 보고서 & ISM 서비스업 PMI',
        description: '공식 고용 보고서의 사전 지표 역할',
      },
      {
        date: '2월 6일 (금)',
        label: '노동부 고용 보고서 (비농업 고용, 실업률, 시간당 임금)',
        description: '이번 주 가장 중요한 지표. 임금 상승 압력 둔화 여부가 관건',
      },
    ],
  },
  {
    id: 12,
    type: 'closing',
    turnId: 37,
    headline: '변동성 장세, 펀더멘털에 집중할 때',
    tagline: '2026년 2월 3일 장마감 브리핑',
    description: '시장은 당분간 거시 경제 지표와 개별 기업 실적에 따라 민감하게 반응할 가능성이 높습니다. 단기 변동성에 흔들리기보다, 긴 호흡으로 기업의 본질적인 성장성을 살피는 것이 중요한 시점입니다.',
  },
];