import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-04-03',
    nutshell: '이란 관련 지정학적 우려에 유가 급등, 증시는 혼조',
    description: '트럼프 대통령의 이란 관련 연설 이후 지정학적 리스크가 부각되며 국제 유가가 폭등했습니다. 시장은 인플레이션 우려와 경기 둔화 가능성 사이에서 방향성을 잃고 혼조세로 마감했습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '주요 지수는 혼조세를 보였으나, 그 이면에는 유가 급등으로 인한 인플레이션 공포가 시장을 지배했습니다. 에너지 섹터는 강세를 보인 반면 항공주 등은 큰 타격을 받았습니다.',
    indices: [
      { name: 'S&P 500', value: 6582.69, change: 7.37, changePercent: 0.11 },
      { name: 'NASDAQ', value: 21879.18, change: 38.23, changePercent: 0.18 },
      { name: 'DOW', value: 46504.67, change: -61.07, changePercent: -0.13 },
      { name: 'Russell 2000', value: 2530.04, change: 17.67, changePercent: 0.70 },
    ],
    commodities: [
      { name: 'WTI Crude', value: 111.80, change: 11.68, changePercent: 11.67 },
      { name: '10-Yr Yield', value: 4.38, change: 0.12, changePercent: 2.82 },
      { name: 'Dollar Index', value: 100.01, change: 0.36, changePercent: 0.36 },
      { name: 'Gold Futures', value: 4694.60, change: -88.60, changePercent: -1.85 },
    ],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
      { ticker: 'CL=F' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 3,
    icon: 'alert-triangle',
    title: '대통령 연설, 시장 불확실성 증폭',
    subtitle: '이란 관련 강경 발언에 지정학적 리스크 고조',
    description: '시장의 기대와 달리 트럼프 대통령이 이란에 대한 강경한 입장을 밝히고 명확한 출구 전략을 제시하지 않으면서, 중동 지역의 지정학적 리스크가 시장의 가장 큰 변수로 부상했습니다.',
    bullets: [
      '이란 분쟁 조기 해결 기대감 소멸',
      '명확한 철군 시간표 제시 부재',
      '중동 지정학적 리스크 장기화 우려',
      '유가 급등으로 인한 인플레이션 공포 자극',
    ],
    theme: 'red',
  },
  {
    id: 3,
    type: 'stats',
    turnId: 7,
    title: '유가 쇼크와 시장의 공포',
    description: '대통령 연설 이후 지정학적 리스크가 금융 시장 전반을 강타했습니다. 유가와 국채금리가 급등하고 변동성 지수가 치솟는 등 시장의 불안 심리가 뚜렷하게 나타났습니다.',
    stats: [
      { label: 'WTI 원유', value: '>$110', subtext: '장중 11% 이상 폭등', trend: 'up' },
      { label: '美 10년물 국채금리', value: '4.38%', subtext: '인플레이션 우려 반영', trend: 'up' },
      { label: 'VIX 지수', value: '>27', subtext: '시장 불안 심리 급증', trend: 'up' },
    ],
    note: '안전자산인 국채마저 매도세가 나타나며 인플레이션 공포가 위험회피 심리를 압도했습니다.',
    theme: 'red',
    charts: [
      { ticker: 'CL=F' },
      { ticker: 'TVC:US10Y' },
      { ticker: 'TVC:VIX' },
    ],
  },
  {
    id: 4,
    type: 'comparison',
    turnId: 11,
    title: '유가 급등에 엇갈린 희비',
    description: '국제 유가 급등이라는 단일 변수가 산업별 명암을 극명하게 갈랐습니다. 에너지, 방산주는 수혜를 입은 반면 항공주는 직격탄을 맞았습니다.',
    items: [
      {
        label: '수혜 업종',
        value: '상승',
        description: '엑슨모빌(XOM), 셰브론(CVX) 등 에너지 기업과 록히드마틴(LMT) 등 방산주 강세',
        highlight: true,
      },
      {
        label: '피해 업종',
        value: '하락',
        description: '아메리칸 항공(AAL), 유나이티드 항공(UAL) 등 항공주 급락. 제트유 가격 폭등으로 비용 부담 가중',
        highlight: false,
      },
    ],
  },
  {
    id: 5,
    type: 'headline',
    turnId: 13,
    icon: 'dollar-sign',
    title: '연준의 딜레마: 스태그플레이션 공포',
    subtitle: '유가발 인플레이션에 금리 인하 기대감 소멸',
    description: '유가 급등이 장기화될 수 있다는 우려가 커지면서, 연내 금리 인하를 기대하던 시장의 분위기가 급변했습니다. 연준은 물가 안정과 경기 방어라는 상반된 압력에 직면했습니다.',
    bullets: [
      '연내 두 차례 금리 인하 기대감 사실상 소멸',
      'BofA, 저성장·고물가 국면 진입 가능성 경고',
      '공급망 충격으로 인한 스태그플레이션 우려 부상',
      '시장의 관심, 경제 지표에서 지정학적 리스크로 이동',
    ],
    theme: 'amber',
  },
  {
    id: 6,
    type: 'stats',
    turnId: 15,
    title: '주요 자산 가격 반응',
    description: '이란 관련 지정학적 리스크는 주식, 채권, 원자재 등 모든 자산 시장에 연쇄 반응을 일으켰습니다. 특히 원유와 채권 금리의 급등이 두드러졌습니다.',
    stats: [
      { label: 'WTI 원유 선물', value: '>$111', subtext: '11% 이상 폭등', trend: 'up' },
      { label: '브렌트유 선물', value: '>$108', subtext: '공급 불안 심리 반영', trend: 'up' },
      { label: '美 10년물 금리', value: '4.38%', subtext: '인플레이션 헤지 매도', trend: 'up' },
    ],
    note: '에너지 섹터(XLE)는 급등한 반면, 항공 ETF(JETS)는 급락하며 극명한 대조를 보였습니다.',
    theme: 'red',
    charts: [
      { ticker: 'XLE' },
      { ticker: 'JETS' },
    ],
  },
  {
    id: 7,
    type: 'comparison',
    turnId: 17,
    title: '연준의 정책 딜레마',
    description: '유가 급등은 연준을 진퇴양난에 빠뜨렸습니다. 물가 안정을 위한 긴축과 경기 둔화를 막기 위한 완화 사이에서 정책적 선택이 극도로 어려워졌습니다.',
    items: [
      {
        label: '물가 안정 압력',
        value: '긴축 유지',
        description: '공급망 충격발 인플레이션에 대응하기 위해 긴축 기조를 유지해야 한다는 목소리',
        highlight: true,
      },
      {
        label: '경기 방어 압력',
        value: '완화 고려',
        description: '유가 상승으로 인한 경기 침체 가능성을 막기 위해 금리 인하가 필요하다는 상반된 시각',
        highlight: false,
      },
      {
        label: '시장 기대',
        value: '불확실성 증폭',
        description: '연내 금리 인하 기대감이 사라지고, 통화정책의 향방이 안갯속에 빠짐',
        highlight: false,
      },
    ],
  },
  {
    id: 8,
    type: 'headline',
    turnId: 21,
    icon: 'compass',
    title: '향후 시장 변수',
    subtitle: '중동 외교와 글로벌 공급망에 쏠린 눈',
    description: '당분간 시장은 거시 경제 지표보다 중동의 지정학적 뉴스 흐름에 따라 움직이는 변동성 장세를 이어갈 전망입니다. 여러 공급 관련 변수들을 주시해야 합니다.',
    bullets: [
      '호르무즈 해협 통행 관련 외교적 협상 결과',
      '미국의 전략비축유(SPR) 방출 여부',
      '우크라이나 공격으로 인한 러시아 원유 생산 차질',
      '시장의 외교적 해법에 대한 높은 민감도',
    ],
    theme: 'blue',
  },
  {
    id: 9,
    type: 'ticker-intro',
    turnId: 22,
    ticker: 'BMY',
    companyName: 'Bristol Myers Squibb',
    currentPrice: 59.60,
    dayChange: -2.13,
    dayChangePercent: -3.45,
    description: '브리스톨 마이어스 스큅(BMY)은 특별한 악재 없이 1% 넘게 하락했습니다. 이는 회사가 직면한 구조적인 \'특허 절벽\' 문제에 대한 시장의 우려가 반영된 것으로 풀이됩니다.',
    charts: [
      { ticker: 'BMY' },
    ],
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 23,
    ticker: 'BMY',
    title: '구조적 위기: 특허 절벽의 그림자',
    points: [
      '2028년경 주력 제품 특허 만료 예정',
      '항응고제 \'엘리퀴스\'와 면역항암제 \'옵디보\'가 핵심',
      '두 제품이 회사 전체 매출의 약 51% 차지',
      '연간 240억 달러 이상의 현금 흐름 소멸 위기',
    ],
    description: '시장은 BMY가 직면한 명백하고 거대한 미래의 리스크를 주가에 선반영하기 시작했습니다. 매출의 절반이 사라질 수 있다는 위기감이 주가를 압박하고 있습니다.',
    outlook: '핵심은 특허 만료에 따른 매출 공백을 어떻게 메울 것인가에 대한 시장의 의구심입니다.',
    outlookColor: 'rose',
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 25,
    ticker: 'BMY',
    title: '생존 전략: 공격적 M&A와 파이프라인',
    points: [
      '막대한 현금흐름을 활용한 공격적 M&A 추진',
      'Karuna, RayzeBio 등 유망 바이오테크 기업 인수',
      '차세대 파이프라인 구축으로 성장 동력 확보 시도',
      'M&A 과정에서 부채가 급증, 재무 안정성 우려',
    ],
    description: 'BMY는 특허 절벽이라는 위기를 극복하기 위해 M&A에 사활을 걸고 있습니다. 하지만 이는 신약 개발 실패 시 더 큰 위기를 초래할 수 있는 양날의 검입니다.',
    outlook: '새로운 성장 동력 확보와 재무 리스크 관리 사이의 아슬아슬한 줄타기가 진행 중입니다.',
    outlookColor: 'amber',
  },
  {
    id: 12,
    type: 'comparison',
    turnId: 29,
    title: 'BMY의 미래: 기회 vs 위협',
    description: 'BMY의 미래는 인수한 신약 파이프라인의 성공 여부에 달려있습니다. 시장은 엄청난 잠재력과 높은 불확실성 사이에서 가치를 평가하고 있습니다.',
    items: [
      {
        label: '성장 잠재력 (기회)',
        value: '낙관론',
        description: '조현병 치료제 \'코벤피\', 방사성 의약품 등 게임 체인저급 신약 후보 보유. 성공 시 매출 공백 상쇄 가능',
        highlight: true,
      },
      {
        label: '현실적 리스크 (위협)',
        value: '비관론',
        description: '매출 절벽은 확정된 현실, 신약 성공은 불확실한 희망. 높은 신약 개발 실패 확률과 부채 부담',
        highlight: false,
      },
    ],
  },
  {
    id: 13,
    type: 'headline',
    turnId: 31,
    icon: 'trending-up',
    title: '강한 경제의 역설',
    subtitle: '견조한 경제 지표가 증시의 발목을 잡다',
    description: '예상보다 강력한 ADP 민간 고용과 ISM 서비스업 지수가 발표되면서, 오히려 연준의 금리 인하 기대감이 후퇴했습니다. 이는 국채 금리 상승과 증시 하락으로 이어졌습니다.',
    bullets: [
      'ADP 민간 고용, 시장 예상치 상회',
      'ISM 서비스업 지수, 확장 국면 지속',
      '강한 경제 → 금리 인하 지연 신호로 해석',
      '주요 3대 지수 이틀 연속 하락 마감',
    ],
    theme: 'blue',
  },
  {
    id: 14,
    type: 'events',
    turnId: 33,
    title: '이번 주 시장의 향방을 가를 핵심 이벤트',
    description: '시장의 모든 관심은 현지 시간 금요일 오전에 발표될 3월 고용보고서에 집중되고 있습니다. 이 보고서의 세부 내용이 연준의 다음 행보를 결정할 중요한 단서가 될 것입니다.',
    events: [
      {
        date: '금요일',
        label: '3월 비농업 신규 고용자 수',
        description: '노동 시장의 강도를 확인할 핵심 지표',
      },
      {
        date: '금요일',
        label: '3월 실업률',
        description: '완전 고용 수준을 유지하는지 여부',
      },
      {
        date: '금요일',
        label: '3월 시간당 평균 임금',
        description: '임금 상승률이 인플레이션에 미치는 영향 주시',
      },
      {
        date: '다음 주',
        label: '소비자물가지수(CPI)',
        description: '고용보고서와 함께 6월 금리 결정을 좌우할 데이터',
      },
    ],
  },
  {
    id: 15,
    type: 'closing',
    turnId: 37,
    headline: '변동성 장세, 핵심은 고용보고서',
    tagline: '데이터에 기반한 신중한 접근이 필요한 시점입니다.',
    description: '지정학적 리스크와 거시 경제 지표가 혼재하며 시장의 변동성이 커지고 있습니다. 금요일 발표될 고용보고서가 단기적인 시장의 방향성을 결정할 분수령이 될 전망입니다.',
  },
];