import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-04-17',
    nutshell: '지정학적 리스크 완화 속 기술주 선별 강세',
    description:
      '중동의 지정학적 긴장 완화 기대감에 유가가 하락하며 시장에 안도감을 주었고, TSMC의 강력한 AI 수요 전망에 힘입어 반도체 주식이 랠리를 펼치며 기술주 중심의 선별적 강세를 이끌었습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description:
      '중동 긴장 완화 기대감에 유가와 금 가격이 하락하며 인플레이션 우려를 덜어냈고, AI 테마가 기술주 상승을 견인하며 주요 지수는 소폭 상승 마감했습니다.',
    indices: [
      { name: 'S&P 500', value: 7041.28, change: 18.33, changePercent: 0.26 },
      { name: 'NASDAQ', value: 24102.70, change: 86.68, changePercent: 0.36 },
      { name: 'DOW', value: 48578.72, change: 115.00, changePercent: 0.24 },
      { name: 'Russell 2000', value: 2719.60, change: 5.94, changePercent: 0.22 },
    ],
    commodities: [
      { name: 'WTI Crude', value: 89.65, change: -1.64, changePercent: -1.80 },
      { name: 'Gold Futures', value: 4810.90, change: 10.90, changePercent: 0.23 },
      { name: 'Dollar Index', value: 98.22, change: 0.16, changePercent: 0.16 },
    ],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
      { ticker: 'TVC:RUT' },
      { ticker: 'CL=F' },
      { ticker: 'COMEX:GC1!' },
      { ticker: 'TVC:DXY' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 7,
    icon: 'globe',
    title: '지정학적 리스크 완화',
    subtitle: '유가 하락, 시장에 안도감',
    description:
      '미국과 이란 간의 평화 협상 재개 가능성 등 중동의 긴장 완화 기대감이 부상하며 국제 유가가 하락, 인플레이션 우려를 완화시키며 증시에 긍정적으로 작용했습니다.',
    bullets: [
      '미-이란, 파키스탄 중재로 2차 평화 협상 재개 가능성',
      '이란, 호르무즈 해협 통행 일부 허용 가능성 시사',
      '트럼프 대통령, 이스라엘-레바논 10일 임시 휴전 합의 발표',
      'WTI 유가 배럴당 $90선 하회, 브렌트유 $95선 하회',
    ],
    theme: 'green',
    charts: [{ ticker: 'CL=F' }, { ticker: 'BZ=F' }],
  },
  {
    id: 3,
    type: 'comparison',
    turnId: 9,
    title: '유가 시장: 기대와 현실의 괴리',
    description:
      '시장은 외교적 해법에 대한 기대감을 선반영하며 유가가 하락했지만, 실제 물리적 공급망은 여전히 심각한 차질을 빚고 있어 괴리가 존재한다는 지적입니다.',
    items: [
      {
        label: '시장의 기대',
        value: '긴장 완화',
        description: '유가 선물 시장은 평화 협상 타결 가능성을 과도하게 반영하며 하락',
        highlight: false,
      },
      {
        label: '물리적 현실',
        value: '공급 차질',
        description: '미 해군의 항구 봉쇄 지속, 호르무즈 해협 통행은 거의 중단된 상태',
        highlight: true,
      },
      {
        label: '전문가 경고',
        value: '장기 영향',
        description: '훼손된 글로벌 에너지 공급망 복구에 수개월 이상 소요될 것으로 전망',
        highlight: false,
      },
    ],
  },
  {
    id: 4,
    type: 'stats',
    turnId: 11,
    title: '미국 원유 재고 현황',
    description:
      '지정학적 리스크 완화 기대감에도 불구하고, 타이트한 미국의 재고 상황과 견조한 수출 수요가 유가의 하단을 지지하고 있습니다.',
    stats: [
      { label: '주간 원유 재고', value: '-91만 배럴', subtext: '시장 예상(증가) 하회', trend: 'down' },
      { label: '총 원유/석유제품 수출', value: '사상 최고', subtext: '해외 수요자 구매 급증', trend: 'up' },
      { label: '수급 상황', value: '타이트', subtext: '견조한 수요가 유가 하단 지지', trend: 'neutral' },
    ],
    note: '협상에 진전이 없을 경우, 유가는 언제든 다시 상승 압력을 받을 수 있는 구조적 위험을 내포하고 있습니다.',
    theme: 'amber',
  },
  {
    id: 5,
    type: 'headline',
    turnId: 13,
    icon: 'cpu',
    title: 'AI 모멘텀 재점화',
    subtitle: 'TSMC발 훈풍, 반도체 섹터 견인',
    description:
      'TSMC가 AI 칩 수요에 대한 강력한 자신감을 내비치자, 필라델피아 반도체 지수가 급등하며 기술주 시장의 차별화된 강세를 이끌었습니다.',
    bullets: [
      'TSMC, AI 관련 수요 폭발적 언급하며 투자 심리 자극',
      '필라델피아 반도체 지수, 주요 지수 대비 월등한 강세',
      '엔비디아 등 대표 AI 주식 동반 상승',
      '유가 및 국채 금리 안정, 성장주에 우호적 환경 조성',
    ],
    theme: 'blue',
    charts: [{ ticker: 'NASDAQ:SOX' }, { ticker: 'NVDA' }],
  },
  {
    id: 6,
    type: 'stats',
    turnId: 15,
    title: 'TSMC 실적 하이라이트',
    description:
      'TSMC는 AI 메가트렌드에 대한 확신을 바탕으로 시장 예상을 뛰어넘는 실적과 함께 연간 전망치를 상향 조정하며 시장에 강력한 신호를 보냈습니다.',
    stats: [
      { label: '1분기 순이익', value: '+58% YoY', subtext: '$181억 기록', trend: 'up' },
      { label: '1분기 매출', value: '+35% YoY', trend: 'up' },
      { label: '연간 매출 성장률 전망', value: '30% 이상', subtext: '기존 전망치 상향 조정', trend: 'up' },
    ],
    note: '시장은 ASML의 단기 지표 부진보다 TSMC가 확인한 최종 칩 수요라는 더 큰 그림에 집중했습니다.',
    theme: 'blue',
    charts: [{ ticker: 'TSM' }, { ticker: 'ASML' }],
  },
  {
    id: 7,
    type: 'headline',
    turnId: 17,
    icon: 'share-nodes',
    title: 'AI 생태계 전반의 온기 확산',
    subtitle: '칩 설계부터 메모리, 서버까지 동반 강세',
    description:
      'TSMC의 발표는 AI 반도체 수요가 칩 설계, 제조, 메모리, 최종 서버 단에 이르기까지 생태계 전체의 성장을 이끌고 있다는 종합적인 신호로 해석되었습니다.',
    bullets: [
      '칩 설계 (경쟁사): AMD, 엔비디아 경쟁자로 동반 강세',
      '메모리 (HBM): 마이크론, AI 서버 필수 부품 공급사로 부각',
      '서버: 슈퍼 마이크로 컴퓨터, AI 서버 구축 핵심 기업으로 강세',
      '종합: 필라델피아 반도체 지수 급등, 광범위한 온기 반영',
    ],
    theme: 'blue',
    charts: [{ ticker: 'AMD' }, { ticker: 'MU' }],
  },
  {
    id: 8,
    type: 'ticker-intro',
    turnId: 20,
    ticker: 'DELL',
    companyName: 'Dell Technologies',
    currentPrice: 193.09,
    dayChange: 15.81,
    dayChangePercent: 8.92,
    description:
      '델 테크놀로지스가 AI 최적화 서버 매출의 폭발적인 성장에 힘입어 7.5% 이상 급등했습니다. 시장은 델을 단순 PC 제조사가 아닌 AI 인프라의 핵심 공급자로 재평가하고 있습니다.',
    charts: [{ ticker: 'DELL' }],
  },
  {
    id: 9,
    type: 'ticker-analysis',
    turnId: 21,
    ticker: 'DELL',
    title: '성장 서사: AI 인프라의 핵심 공급자',
    points: [
      'AI 최적화 서버 매출 전년 대비 166% 폭증 ($247억)',
      '인프라 솔루션 그룹(ISG)이 전통적 PC 사업부 성장을 압도',
      '시장은 델을 AI 시대의 가장 중요한 플레이어 중 하나로 재평가',
      '강력한 AI 인프라 수요에 대한 시장의 믿음이 주가 급등 견인',
    ],
    outlook: 'AI 성장 스토리에 대한 시장의 기대감은 매우 높은 상황입니다.',
    outlookColor: 'emerald',
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 23,
    ticker: 'DELL',
    title: '이면의 리스크: 수익성 악화',
    points: [
      '화려한 매출 성장에도 불구, 회사 전체 총이익률은 하락 (22.2% → 20.0%)',
      '성장을 이끈 인프라 그룹의 영업이익률마저 하락 (12.8% → 11.7%)',
      '저마진 AI 서버 제품 비중 증가가 수익성 악화의 원인',
      '이익을 희생하며 매출을 늘리는 ‘속 빈 강정’ 성장 우려 제기',
    ],
    outlook: '외형 성장 이면에 수익성 악화라는 구조적 문제가 존재합니다.',
    outlookColor: 'rose',
  },
  {
    id: 11,
    type: 'stats',
    turnId: 25,
    title: 'Dell 재무 구조의 경고 신호',
    description:
      '델의 재무 구조는 자본잠식 상태, 높은 고객 집중도, 급증한 매출채권 등 심각한 경고 신호를 보내고 있어 유동성 리스크에 대한 우려가 커지고 있습니다.',
    stats: [
      { label: '주주자본', value: '-$25억', subtext: '사실상 자본잠식 상태', trend: 'down' },
      { label: '매출채권', value: '+71% YoY', subtext: '$176억, 유동성 리스크 시사', trend: 'up' },
      { label: '고객 집중도', value: '12%', subtext: '단일 고객이 전체 매출 차지', trend: 'neutral' },
    ],
    note: '핵심 고객의 주문 감소 또는 대금 지급 지연 시, 기업 전체가 유동성 위기에 빠질 수 있는 취약한 구조입니다.',
    theme: 'red',
  },
  {
    id: 12,
    type: 'ticker-analysis',
    turnId: 27,
    ticker: 'DELL',
    title: '종합 분석: 기대와 현실의 괴리',
    points: [
      '현재 주가는 AI 서사가 펀더멘털 악화를 완전히 압도하는 상황',
      '시장은 인상적인 매출 성장에만 주목',
      '수익성 하락, 재무 건전성 훼손, 고객 의존도 리스크는 미반영',
      '향후 실적 발표에서 작은 균열에도 변동성 확대 가능성',
    ],
    outlook: '현재 주가는 장밋빛 기대감에 크게 의존하고 있어, 펀더멘털 리스크에 대한 주의가 필요합니다.',
    outlookColor: 'amber',
  },
  {
    id: 13,
    type: 'headline',
    turnId: 29,
    icon: 'landmark',
    title: '시장의 시선, 연준으로',
    subtitle: '금리 인하 기대 후퇴, 경제 지표 주목',
    description:
      '파월 의장의 매파적 발언으로 조기 금리 인하 기대감이 후퇴하면서, 시장의 모든 관심은 연준의 다음 행보를 가늠할 수 있는 경제 지표로 집중되고 있습니다.',
    bullets: [
      '파월 의장 매파적 발언, 시장에 하방 압력으로 작용',
      '금리 민감 기술주 중심의 나스닥 지수 타격',
      '국채 금리 상승세 지속',
      '향후 발표될 경제 지표에 따라 시장 변동성 확대 국면 진입',
    ],
    theme: 'purple',
    charts: [{ ticker: 'TVC:US10Y' }, { ticker: 'NASDAQ:IXIC' }],
  },
  {
    id: 14,
    type: 'events',
    turnId: 31,
    title: '주요 경제 이벤트 캘린더',
    description:
      '다음 주부터 월말까지 고용, 성장, 물가 관련 핵심 지표와 FOMC 회의가 연이어 예정되어 있어 시장의 방향성을 결정할 중요한 분수령이 될 전망입니다.',
    events: [
      { date: '4/23', label: '주간 신규 실업수당 청구건수', description: '고용 시장 온도 가늠' },
      { date: '4/23', label: 'S&P 글로벌 종합 PMI 예비치', description: '제조업/서비스업 경기 동향 파악' },
      { date: '4/29', label: 'FOMC 금리 결정', description: '성명서 및 파월 의장 발언 주목' },
      { date: '4/30', label: '개인소비지출(PCE) 가격지수', description: '연준이 가장 중시하는 물가 지표' },
    ],
  },
  {
    id: 15,
    type: 'closing',
    turnId: 35,
    headline: '데이터를 확인하며 긴 호흡으로',
    tagline: '변동성 국면, 섣부른 예단보다 자산 배분 점검이 필요한 시점',
    description:
      '금리 인하 시점이 불투명해진 만큼, 단기적 방향성을 예단하기보다 핵심 지표들을 차분히 확인하며 시장의 반응을 살피고 긴 호흡으로 포트폴리오를 점검해야 할 때입니다.',
  },
];