import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '20260129',
    nutshell: '빅테크 실적 발표 이후 엇갈린 희비에 따른 시장 혼조세',
    description: '빅테크 기업들의 실적이 극명하게 엇갈리며 시장이 혼조세를 보였습니다. 마이크로소프트는 비용 우려로 급락한 반면, 메타는 수익성을 증명하며 급등했습니다. 시장의 관심이 막연한 기대감에서 구체적인 숫자로 옮겨가고 있음을 보여준 하루였습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '주요 빅테크 기업들의 실적이 엇갈리면서 주요 지수도 방향성을 달리했습니다. 다우존스는 소폭 상승했으나, 마이크로소프트의 급락 여파로 기술주 중심의 나스닥과 S&P 500은 하락 마감했습니다.',
    indices: [
      { name: 'DOW', value: 49071.55, change: 49.02, changePercent: 0.10 },
      { name: 'NASDAQ', value: 23685.12, change: -172.02, changePercent: -0.72 },
      { name: 'S&P 500', value: 5992.21, change: -7.80, changePercent: -0.13 },
    ],
    commodities: [],
    charts: [
      { ticker: 'DJ:DJI' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'SP:SPX' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 7,
    icon: 'zap',
    title: '빅테크, AI 실적 희비 교차',
    subtitle: '시장은 이제 \'수익성\'을 묻는다',
    description: '연준의 금리 동결 이후, 시장의 초점은 개별 기업의 펀더멘털로 이동했습니다. 특히 AI 테마 안에서 실제 수익 창출 능력을 증명했는지에 따라 빅테크 기업들의 주가가 극명하게 갈렸습니다.',
    bullets: [
      '메타(META): 광고 실적 호조로 10% 이상 급등',
      '마이크로소프트(MSFT): 과도한 투자 비용 우려로 10% 가까이 급락',
      '테슬라(TSLA): 사상 첫 연간 매출 감소로 3% 이상 하락',
      '투자 심리: 막연한 AI 기대감에서 구체적인 수익성 검증으로 전환',
    ],
    theme: 'purple',
    charts: [
      { ticker: 'MSFT' },
      { ticker: 'META' },
      { ticker: 'TSLA' },
    ],
  },
  {
    id: 3,
    type: 'stats',
    turnId: 9,
    title: 'Microsoft: 높아진 AI 투자의 허들',
    description: '매출과 이익이 예상을 상회했음에도 불구하고, AI 인프라 구축을 위한 막대한 비용 지출과 클라우드 성장세 둔화가 투자자들의 우려를 자극했습니다.',
    stats: [
      { label: '분기 자본적 지출(Capex)', value: '$375억', subtext: '시장 예상 상회', trend: 'up' },
      { label: 'Azure 매출 성장률', value: '39%', subtext: '직전 분기 40% 대비 소폭 둔화', trend: 'down' },
      { label: '일일 시가총액 변동', value: '약 $3,570억 감소', subtext: '주가 약 10% 급락', trend: 'down' },
    ],
    note: '시장은 AI 투자의 규모뿐만 아니라, 투자 대비 수익 창출의 효율성을 요구하기 시작했습니다.',
    theme: 'red',
    charts: [{ ticker: 'MSFT' }],
  },
  {
    id: 4,
    type: 'stats',
    turnId: 11,
    title: 'Meta: AI를 수익으로 증명하다',
    description: '메타는 AI 투자가 핵심 사업인 광고의 효율성 증대로 직접 이어진다는 것을 실적으로 보여주며 시장의 신뢰를 얻었습니다. 주주환원 정책도 긍정적으로 작용했습니다.',
    stats: [
      { label: '4분기 매출', value: '$599억', subtext: '시장 예상 상회', trend: 'up' },
      { label: '핵심 동력', value: 'AI 기반 광고 효율 증대', subtext: '사용자 참여도 상승', trend: 'up' },
      { label: '주주환원 정책', value: '사상 첫 배당 실시', subtext: '대규모 자사주 매입 발표', trend: 'up' },
    ],
    theme: 'green',
    charts: [{ ticker: 'META' }],
  },
  {
    id: 5,
    type: 'comparison',
    turnId: 11,
    title: 'AI 투자, 무엇이 달랐나?',
    description: '동일하게 AI에 막대한 투자를 집행했지만, 시장은 그 투자가 현재의 수익성에 얼마나 기여하는지에 따라 두 기업을 다르게 평가했습니다.',
    items: [
      {
        label: 'Microsoft',
        value: '비용 우려 부각',
        description: '막대한 투자 비용 대비 성장세 둔화에 대한 의구심 발생. 미래 가치에 대한 불확실성.',
        highlight: false,
      },
      {
        label: 'Meta',
        value: '수익성 증명',
        description: 'AI 투자가 광고 효율 증대 등 현재 이익으로 직결됨을 입증. 주주환원 정책으로 신뢰 확보.',
        highlight: true,
      },
    ],
  },
  {
    id: 6,
    type: 'headline',
    turnId: 13,
    icon: 'trending-down',
    title: 'Tesla: 미래 비전의 시험대',
    subtitle: '사상 첫 연간 매출 감소 기록',
    description: '핵심 사업인 전기차 부문의 성장세가 둔화되면서, 아직 가시적 성과가 없는 로보택시 등 미래 사업에 대한 시장의 평가가 냉담해졌습니다.',
    bullets: [
      '주력 사업(전기차)의 성장 둔화 현실화',
      'AI 기반 미래 사업(로보택시, 옵티머스)의 불확실성 부각',
      '수익화 능력이 증명되지 않은 기술 투자의 리스크로 평가됨',
    ],
    theme: 'red',
    charts: [{ ticker: 'TSLA' }],
  },
  {
    id: 7,
    type: 'ticker-intro',
    turnId: 14,
    ticker: 'LMT',
    companyName: 'Lockheed Martin',
    currentPrice: 490.08,
    dayChange: 10.08,
    dayChangePercent: 2.10,
    description: '방산업체 록히드마틴은 긍정적인 미래 전망을 발표하며 장중 급등했으나, 실적 자체는 예상을 하회하며 기대와 현실 사이의 괴리를 보여주었습니다.',
    charts: [{ ticker: 'LMT' }],
  },
  {
    id: 8,
    type: 'ticker-analysis',
    turnId: 15,
    ticker: 'LMT',
    title: '핵심 기회: 견고한 수주와 생산 확대',
    points: [
      '기록적인 수주 잔고($1,936억) 달성으로 향후 수년간의 매출 가시성 확보',
      'THAAD 요격미사일 생산량 4배 증설 계획으로 성장 기대감 증폭',
      '지정학적 리스크 고조에 따른 방산 수요 증가의 수혜주로 부각',
    ],
    description: '시장은 현재의 실적보다 미래의 성장 가능성에 더 큰 비중을 두고 주가를 끌어올린 것으로 관찰됩니다.',
  },
  {
    id: 9,
    type: 'ticker-analysis',
    turnId: 17,
    ticker: 'LMT',
    title: '주요 리스크: 펀더멘털과 기대감의 괴리',
    points: [
      '4분기 주당순이익(EPS)이 시장 예상치를 하회하며 실적 자체는 부진',
      '주가 급등은 실적이 아닌 미래 기대감에만 의존하고 있어 과열 가능성 존재',
      '미국 정부의 국방 예산 및 정치적 결정에 전적으로 의존하는 사업 구조적 취약성',
    ],
    description: '만약 향후 국방 예산이 기대에 미치지 못할 경우, 현재의 높은 밸류에이션은 급격한 조정을 받을 수 있습니다.',
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 21,
    ticker: 'LMT',
    title: '종합 분석 요약',
    points: [
      '극초음속, 우주 등 첨단 기술 분야의 장기 성장 잠재력은 유효한 것으로 평가됩니다.',
      '그러나 실적 부진에도 불구하고 주가가 급등한 현상은 투자 심리 과열 신호일 수 있습니다.',
      '정치적 리스크와 높은 밸류에이션을 고려할 때, 현재 가격 수준에서의 신중한 접근이 요구됩니다.',
    ],
    outlook: 'High Expectations',
    outlookColor: 'amber',
  },
  {
    id: 11,
    type: 'headline',
    turnId: 23,
    icon: 'calendar',
    title: '시장의 초점: 경제지표로 이동',
    subtitle: '고용 및 경기 데이터에 쏠린 눈',
    description: '연준의 통화정책 발표 이후, 시장의 관심은 연준의 다음 행보를 가늠할 수 있는 실제 경제 데이터로 완전히 넘어왔습니다. 지표 결과에 따라 시장 변동성이 커질 수 있습니다.',
    theme: 'blue',
  },
  {
    id: 12,
    type: 'events',
    turnId: 25,
    title: '다음 주 주요 경제지표 발표 일정',
    description: '특히 고용 시장의 건전성과 제조업/서비스업의 경기 상황을 보여주는 지표들이 연준의 금리 인하 시점에 대한 단서를 제공할 것입니다.',
    events: [
      { date: '2026-02-02', label: 'ISM 제조업 구매관리자지수 (PMI)' },
      { date: '2026-02-03', label: 'JOLTs (구인·이직 보고서)' },
      { date: '2026-02-04', label: 'ADP 민간 고용 보고서' },
      { date: '2026-02-04', label: 'ISM 서비스업 구매관리자지수 (PMI)' },
      { date: '2026-02-06', label: '비농업 고용지표 및 실업률' },
    ],
  },
  {
    id: 13,
    type: 'closing',
    turnId: 29,
    headline: '섣부른 예측보다 확인과 대응',
    tagline: '데이터가 말해주는 시장의 방향성',
    description: '큰 이벤트를 지난 시장은 이제 데이터 하나하나에 민감하게 반응하는 국면에 접어들었습니다. 발표되는 지표들이 시장의 기대를 어떻게 바꾸는지 차분히 관찰하며 투자 전략을 세워야 할 시점입니다.',
  },
];