import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-01-23',
    nutshell: '인텔 실적 충격과 지정학적 안도감이 엇갈린 혼조 장세',
    description: '인텔의 부진한 실적 전망이 다우 지수를 압박했지만, 트럼프의 관세 위협 철회와 빅테크 실적 기대감이 나스닥의 상승을 이끌며 시장의 방향성이 엇갈렸습니다. 오늘 브리핑에서는 시장을 움직인 핵심 테마와 TSMC에 대한 심층 분석을 다룹니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '인텔의 실적 충격으로 다우 지수는 하락했지만, 기술주에 대한 기대감과 지정학적 리스크 완화로 나스닥은 상승하며 주요 지수가 혼조세로 마감했습니다.',
    indices: [
      { name: 'S&P 500', value: 6915.61, change: 2.07, changePercent: 0.03 },
      { name: 'NASDAQ', value: 23501.24, change: 65.8, changePercent: 0.28 },
      { name: 'DOW', value: 49098.71, change: -286.73, changePercent: -0.58 },
    ],
    commodities: [
      { name: 'Gold', value: 4995.0, change: 69.0, changePercent: 1.4 },
      { name: 'Dollar Index', value: 102.5, change: -0.82, changePercent: -0.8 },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 6,
    icon: 'cpu',
    title: '인텔 쇼크, 다우를 강타하다',
    subtitle: '부진한 1분기 가이던스에 주가 17% 폭락',
    description: '인텔이 시장 예상을 크게 밑도는 1분기 실적 전망을 발표하며 주가가 17% 넘게 폭락했습니다. 이는 다우 지수에 직접적인 부담으로 작용했지만, 견조한 경제 지표 덕분에 시장 전반의 투매로 번지는 것은 막았습니다.',
    bullets: [
      '인텔 주가, 실망스러운 가이던스에 17% 이상 폭락',
      '다우 존스 산업평균지수 하락 주도',
      'S&P 글로벌 서비스 PMI는 확장 국면 유지하며 시장 방어',
      '10년물 국채금리 안정, 투자 심리 급랭 방지',
    ],
    theme: 'red',
  },
  {
    id: 3,
    type: 'stats',
    turnId: 9,
    title: '인텔 1분기 실적 가이던스 쇼크',
    description: '인텔이 제시한 1분기 매출 및 이익 전망치는 월스트리트의 컨센서스를 크게 하회하며 시장에 충격을 주었습니다. 이는 단순한 업황 둔화를 넘어 AI 시대의 기술 경쟁력에 대한 우려를 증폭시켰습니다.',
    stats: [
      { label: '1분기 매출 전망', value: '$117억 ~ $127억', subtext: '컨센서스($130억 후반) 하회', trend: 'down' },
      { label: '조정 주당순이익', value: '기대치 50% 미만', subtext: '수익성 악화 우려', trend: 'down' },
      { label: '주가 변동', value: '-17%', subtext: '2026년 1월 23일', trend: 'down' },
    ],
    note: '데이터센터 부진 및 모빌아이 등 성장 동력 약화가 확인되며 구조적 문제로 인식되었습니다.',
    theme: 'red',
    charts: [{ ticker: 'INTC', title: 'Intel Corp.' }],
  },
  {
    id: 4,
    type: 'comparison',
    turnId: 11,
    title: '엇갈린 반도체 주가: 인텔 vs 경쟁사',
    description: '시장은 인텔의 부진을 반도체 산업 전체가 아닌 개별 기업의 문제로 판단했습니다. 오히려 경쟁사들은 반사 이익 기대감에 주가가 상승하는 모습을 보였습니다.',
    items: [
      {
        label: 'Intel (INTC)',
        value: '-17.0%',
        description: '경쟁 심화 및 기술력 우려로 폭락',
        highlight: false,
      },
      {
        label: 'AMD (AMD)',
        value: '+2.3%',
        description: '데이터센터 점유율 확대 기대로 신고가 경신',
        highlight: true,
      },
      {
        label: 'NVIDIA (NVDA)',
        value: '강보합',
        description: 'AI 칩 시장의 절대 강자로서 견고한 모습 유지',
        highlight: false,
      },
    ],
  },
  {
    id: 5,
    type: 'headline',
    turnId: 14,
    icon: 'shield-check',
    title: '지정학적 리스크 완화',
    subtitle: '트럼프, 유럽 관세 위협 철회로 시장 안도',
    description: '트럼프 대통령이 그린란드 문제와 연계했던 유럽 관세 부과 위협을 철회하면서 시장의 불확실성이 크게 해소되었습니다. 이 소식은 인텔 쇼크의 충격을 일부 상쇄하며 시장의 추가 하락을 막는 버팀목 역할을 했습니다.',
    bullets: [
      '트럼프, 유럽 8개국 대상 10% 관세 위협 철회',
      '무역전쟁 확전 우려 해소, 글로벌 증시 안도',
      '달러화 가치 하락, 유로화 강세 등 위험 선호 심리 회복',
      '월가에서는 "타코 트레이드" 전략이 다시 주목받음',
    ],
    theme: 'green',
  },
  {
    id: 6,
    type: 'stats',
    turnId: 19,
    title: '관세 위협 철회에 따른 시장 반응',
    description: '대통령의 관세 위협 철회 소식에 위험자산 선호 심리가 빠르게 회복되었습니다. 하지만 금 가격이 상승세를 이어가는 등 정책 불확실성에 대한 경계감은 여전히 남아있습니다.',
    stats: [
      { label: '유로/달러 환율', value: '+0.7%', subtext: '위험 선호 심리 회복', trend: 'up' },
      { label: '달러 인덱스', value: '-0.8%', subtext: '지정학적 프리미엄 해소', trend: 'down' },
      { label: '금 선물 가격', value: '+1.4%', subtext: '근본적인 불확실성 우려 잔존', trend: 'up' },
    ],
    note: 'PMI, 소비자심리지수 등 경제 지표는 성장 둔화를 시사하며 관망세를 더했습니다.',
    theme: 'green',
    charts: [{ ticker: 'TVC:DXY' }, { ticker: 'FX:EURUSD' }, { ticker: 'COMEX:GC1!' }],
  },
  {
    id: 7,
    type: 'headline',
    turnId: 22,
    icon: 'brain-circuit',
    title: '나스닥의 차별적 강세',
    subtitle: 'AI 기대감, 빅테크 희비를 가르다',
    description: '인텔 쇼크에도 불구하고 나스닥 지수는 상승 마감했습니다. 시장은 인텔의 문제를 개별 기업의 이슈로 선을 긋고, 다음 주 실적 발표를 앞둔 마이크로소프트 등 AI 선도 기업에 대한 기대감을 키웠습니다.',
    bullets: [
      '나스닥 지수, 빅테크 기대감에 홀로 0.28% 상승',
      '마이크로소프트, AI 기대감으로 3.27% 급등하며 사상 최고치 경신',
      '시장의 관심은 다음 주 MS, 애플, 아마존 실적 발표로 이동',
      'AI가 기업의 운명을 가르는 핵심 키워드로 부상',
    ],
    theme: 'blue',
  },
  {
    id: 8,
    type: 'comparison',
    turnId: 27,
    title: '다음 주 빅테크 실적 관전 포인트',
    description: '다음 주 실적을 발표하는 빅테크 기업들은 각기 다른 과제를 안고 있습니다. AI, 스마트폰, 전기차 등 각자의 핵심 사업 영역에 따라 시장의 평가가 엇갈릴 전망입니다.',
    items: [
      {
        label: 'Microsoft (MSFT)',
        value: 'AI 성장성',
        description: '애저(Azure) 클라우드 성장률과 코파일럿 서비스의 초기 성과가 핵심',
        highlight: true,
      },
      {
        label: 'Apple (AAPL)',
        value: '중국 리스크',
        description: '중국 시장에서의 아이폰 판매 둔화 우려를 서비스 부문 성장으로 만회할 수 있을지 주목',
        highlight: false,
      },
      {
        label: 'Tesla (TSLA)',
        value: '수익성 방어',
        description: '전기차 경쟁 심화 속에서 향후 생산량 가이던스와 마진율 방어 전략이 관건',
        highlight: false,
      },
    ],
  },
  {
    id: 9,
    type: 'ticker-intro',
    turnId: 30,
    ticker: 'TSM',
    companyName: 'Taiwan Semiconductor Manufacturing Co.',
    currentPrice: 153.0,
    dayChange: 3.15,
    dayChangePercent: 2.1,
    description: 'TSMC 주가는 애리조나 신규 공장 투자 관련 긍정적 소식에 힘입어 시장의 혼조세 속에서도 2% 넘는 강세를 보였습니다. 대만 총통의 발언이 지정학적 리스크 해소 기대감을 자극했습니다.',
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 33,
    ticker: 'TSM',
    title: '애리조나 투자: 기회인가, 함정인가?',
    points: [
      '기회(Pros): 지정학적 리스크(대만 집중화) 해소, 미국과의 기술 동맹 강화, 국방/항공우주 등 신규 고수익 시장 개척 기대',
      '함정(Cons): 높은 운영 비용(대만 대비 30-50%↑)으로 인한 구조적인 수익성 악화, 정부 보조금의 한계, 재무적 부담 가중',
    ],
    description: '시장은 지정학적 리스크 해소라는 긍정적 서사에 환호하고 있지만, 그 이면에는 수익성 악화라는 거의 확정된 재무적 부담이 존재합니다. "안보 프리미엄"이 높은 비용을 상쇄할 수 있을지가 논쟁의 핵심입니다.',
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 37,
    ticker: 'TSM',
    title: '최종 투자 의견: 매도 (SELL)',
    points: [
      '현재 주가는 긍정적 시나리오만 과도하게 반영한 고평가 상태로 판단됩니다.',
      '장기적인 이익률 하락이라는 명백한 위험은 제대로 평가되지 않았습니다.',
      '시장의 열기가 식고 숫자의 냉정한 현실이 재무제표에 드러날 때, 주가는 본질 가치를 찾아 하락할 위험이 더 큽니다.',
    ],
    action: 'SELL',
    description: '신뢰도 0.8의 매도 의견을 제시합니다. 지금은 시장의 탐욕적인 분위기에 편승하기보다, 확정된 비용 증가라는 펀더멘털의 변화를 냉정하게 바라봐야 할 때입니다.',
  },
  {
    id: 12,
    type: 'events',
    turnId: 39,
    title: '향후 주요 경제 이벤트',
    description: '개별 기업 실적 장세가 이어지는 가운데, 시장의 초점은 다시 연준의 통화정책 경로를 확인할 수 있는 거시 경제 지표로 옮겨갈 전망입니다.',
    events: [
      {
        date: '2026-01-28',
        label: 'FOMC 회의',
        description: '파월 의장 기자회견에서 3월 금리 인하에 대한 힌트를 얻을 수 있을지 주목됩니다.',
      },
      {
        date: '2026-01-29',
        label: '주간 신규 실업수당 청구 건수',
        description: '노동 시장의 온도를 가늠하고 연준의 금리 인하 시점에 대한 단서를 제공할 수 있습니다.',
      },
      {
        date: '2026-02-20',
        label: '근원 PCE 가격지수',
        description: '연준이 가장 신뢰하는 물가 지표로, 향후 통화정책 경로를 결정할 핵심 데이터입니다.',
      },
    ],
  },
  {
    id: 13,
    type: 'closing',
    turnId: 45,
    headline: '실적 장세 속, 다시 거시 지표로 향하는 시선',
    tagline: '데이터에 기반한 신중한 투자가 필요한 시점입니다.',
    description: '시장은 연준의 빠른 금리 인하를 기대하고 있지만, 연준은 데이터에 기반한 신중한 결정을 강조하고 있습니다. 향후 발표될 고용 및 물가 지표를 통해 시장의 기대와 현실의 간극을 확인하며, 실적이 뒷받침되는 견고한 기업에 집중하는 전략이 유효합니다.',
  },
];