import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-01-23',
    nutshell: '인텔 실적 충격과 지정학적 안도감이 엇갈린 혼조 장세',
    description: '인텔의 부진한 실적 전망이 다우 지수를 압박했지만, 지정학적 리스크 완화와 다른 빅테크에 대한 기대감이 나스닥의 상승을 이끌며 시장이 혼조세로 마감했습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description: '인텔의 실적 충격이 다우 지수를 끌어내렸으나, 기술주 중심의 나스닥은 빅테크 실적 기대감에 상승하며 지수별로 등락이 엇갈렸습니다.',
    indices: [
      { name: 'S&P 500', value: 6915.61, change: 2.07, changePercent: 0.03 },
      { name: 'NASDAQ', value: 23501.24, change: 65.80, changePercent: 0.28 },
      { name: 'DOW', value: 49098.71, change: -284.77, changePercent: -0.58 },
    ],
    commodities: [
      { name: '금 선물', value: 4990.00, change: 69.00, changePercent: 1.40 },
      { name: '달러 인덱스', value: 102.50, change: -0.82, changePercent: -0.80 },
    ],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 6,
    icon: 'trending-down',
    title: '인텔 실적 쇼크',
    subtitle: '다우 지수를 짓누른 반도체 거인의 부진',
    description: '인텔이 시장 예상을 크게 밑도는 1분기 가이던스를 발표하며 주가가 17% 넘게 폭락했습니다. 이는 다우 지수 하락의 주요 원인이었으나, 시장은 이를 인텔의 개별 문제로 해석하며 충격을 제한적으로 소화했습니다.',
    bullets: [
      '1분기 매출 가이던스, 월가 컨센서스 하회',
      '데이터센터 등 핵심 사업부 부진 확인',
      '주가 17% 폭락하며 다우 지수 하락 주도',
      '견조한 경제 지표가 시장 전반의 투매 방어',
    ],
    theme: 'red',
  },
  {
    id: 3,
    type: 'stats',
    turnId: 9,
    title: '인텔 1분기 가이던스 상세',
    description: '인텔이 제시한 1분기 전망은 매출과 이익 모든 면에서 시장의 기대를 크게 밑돌며 투자자들에게 실망감을 안겼습니다.',
    stats: [
      { label: '1분기 매출 전망', value: '$117억 ~ $127억', subtext: '시장 예상치($130억 후반) 하회', trend: 'down' },
      { label: '조정 주당순이익(EPS) 전망', value: '기대치 절반 미만', subtext: '수익성 악화 우려', trend: 'down' },
      { label: '주가 반응', value: '-17%', subtext: '실적 발표 후 폭락', trend: 'down' },
    ],
    note: '시장은 이를 단순 업황 둔화를 넘어 AI 시대 기술 경쟁력에 대한 구조적 문제로 인식하는 분위기입니다.',
    theme: 'red',
    charts: [{ ticker: 'INTC' }],
  },
  {
    id: 4,
    type: 'comparison',
    turnId: 11,
    title: '반도체 섹터 내 엇갈린 희비',
    description: '시장은 인텔의 부진을 반도체 산업 전체의 위기가 아닌 개별 기업의 문제로 판단했으며, 경쟁사들은 오히려 반사 이익 기대감에 강세를 보였습니다.',
    items: [
      {
        label: 'Intel (INTC)',
        value: '-17%',
        description: '경쟁 심화 및 구조적 문제 우려',
        highlight: false,
      },
      {
        label: 'AMD (AMD)',
        value: '+2.3%',
        description: '반사 이익 기대감 속 신고가 경신',
        highlight: true,
      },
      {
        label: 'Nvidia (NVDA)',
        value: '강보합',
        description: 'AI 칩 시장 지배력 재확인',
        highlight: true,
      },
    ],
    charts: [{ ticker: 'INTC' }, { ticker: 'AMD' }, { ticker: 'NVDA' }],
  },
  {
    id: 5,
    type: 'headline',
    turnId: 14,
    icon: 'shield-check',
    title: '지정학적 리스크 완화',
    subtitle: '트럼프, 유럽 관세 위협 철회',
    description: '트럼프 대통령이 그린란드 매입 거절에 대한 보복 조치로 위협했던 유럽 관세를 철회하면서, 시장을 짓누르던 무역전쟁 확전 우려가 해소되었습니다. 이는 인텔 쇼크를 상쇄하는 버팀목 역할을 했습니다.',
    bullets: [
      '그린란드 관련 유럽 8개국 관세 부과 위협',
      '위협 철회로 글로벌 시장 안도감 확산',
      '달러화 가치 하락, 유로화 강세',
      '인텔 쇼크가 시장 전체 투매로 번지는 것을 방어',
    ],
    theme: 'green',
  },
  {
    id: 6,
    type: 'headline',
    turnId: 22,
    icon: 'sparkles',
    title: '기술주 옥석 가리기',
    subtitle: 'AI 모멘텀이 가른 나스닥의 차별화',
    description: '인텔의 추락에도 불구하고 나스닥 지수는 상승 마감했습니다. 시장의 관심이 AI와 같은 명확한 성장 동력을 가진 기업으로 집중되면서, 기술주 내에서도 극명한 차별화가 나타났습니다.',
    bullets: [
      '인텔의 부진은 개별 문제로 국한',
      '마이크로소프트, AI 기대감에 3.27% 급등하며 사상 최고치',
      '시장의 시선은 다음 주 빅테크 실적 발표로 이동',
      'AI가 기업 가치를 가르는 핵심 키워드로 부상',
    ],
    theme: 'purple',
  },
  {
    id: 7,
    type: 'comparison',
    turnId: 23,
    title: '명암이 엇갈린 두 기술 거인',
    description: 'AI에 대한 전망이 인텔과 마이크로소프트의 주가 방향을 정반대로 갈라놓았습니다.',
    items: [
      {
        label: 'Intel (INTC)',
        value: '-17.0%',
        description: '부진한 가이던스와 AI 경쟁력 우려로 급락',
        highlight: false,
      },
      {
        label: 'Microsoft (MSFT)',
        value: '+3.27%',
        description: 'AI 기반 실적 기대감으로 사상 최고치 경신',
        highlight: true,
      },
    ],
    charts: [{ ticker: 'INTC' }, { ticker: 'MSFT' }],
  },
  {
    id: 8,
    type: 'comparison',
    turnId: 27,
    title: '다음 주 빅테크 실적 관전 포인트',
    description: '다음 주 실적을 발표하는 다른 빅테크 기업들 역시 각기 다른 과제를 안고 있어, 시장의 관심이 집중되고 있습니다.',
    items: [
      {
        label: 'Microsoft',
        value: 'AI 기대감',
        description: 'AI 기반 클라우드(Azure) 성장률 가속 여부',
      },
      {
        label: 'Apple',
        value: '중국 리스크',
        description: '중국 시장 아이폰 판매 둔화 우려와 서비스 부문 성장성',
      },
      {
        label: 'Tesla',
        value: '수익성 문제',
        description: '전기차 시장 경쟁 심화에 따른 마진율 방어 전략',
      },
    ],
  },
  {
    id: 9,
    type: 'ticker-intro',
    turnId: 30,
    ticker: 'TSM',
    companyName: 'Taiwan Semiconductor Manufacturing',
    currentPrice: 142.80,
    dayChange: 2.80,
    dayChangePercent: 2.00,
    description: 'TSMC 주가는 애리조나 신규 공장 투자 관련 긍정적 소식에 힘입어 시장의 혼조세 속에서도 2% 넘는 강세를 보였습니다.',
    charts: [{ ticker: 'TSM' }],
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 31,
    ticker: 'TSM',
    title: '핵심 기회: 지정학적 리스크 완화',
    points: [
      '대만 총통, 애리조나 추가 투자 및 미국과의 관계 강화 언급',
      '시장은 이를 대만 집중화 리스크를 해소하는 긍정적 신호로 해석',
      '미국의 핵심 기술 동맹으로 격상되어 장기적 안정성 확보 기대',
    ],
    description: '투자자들은 애리조나 투자가 TSMC의 지정학적 약점을 보완하고 장기적인 성장 기반을 다지는 계기가 될 것으로 기대하고 있습니다.',
    outlook: '지정학적 안정성',
    outlookColor: 'emerald',
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 33,
    ticker: 'TSM',
    title: '주요 리스크: 구조적 비용 증가',
    points: [
      '애리조나 공장의 운영 비용은 대만 대비 30~50% 높을 것으로 추정',
      '이는 TSMC의 높은 매출 총이익률을 구조적으로 훼손시킬 수 있는 요인',
      '지정학적 리스크가 재무적 부담으로 전환될 수 있다는 우려가 제기됩니다.',
    ],
    description: '미국 내 높은 운영 비용은 TSMC의 핵심 경쟁력인 수익성을 장기적으로 약화시킬 수 있는 현실적인 위협으로 평가됩니다.',
    outlook: '수익성 압박 우려',
    outlookColor: 'rose',
  },
  {
    id: 12,
    type: 'ticker-analysis',
    turnId: 37,
    ticker: 'TSM',
    title: '종합 분석 요약',
    points: [
      '현재 주가는 애리조나 투자의 긍정적 시나리오를 상당 부분 반영한 것으로 관찰됩니다.',
      '장기적인 이익률 하락 가능성은 주가에 충분히 반영되지 않았을 수 있습니다.',
      '시장의 기대감과 비용 증가라는 현실 사이의 균형을 신중히 관찰할 필요가 있습니다.',
    ],
    description: '지정학적 리스크 해소라는 긍정적 서사 이면에 있는 수익성 악화 가능성을 냉정하게 평가해야 할 시점으로 보입니다.',
    outlook: '고평가 주의',
    outlookColor: 'amber',
  },
  {
    id: 13,
    type: 'events',
    turnId: 39,
    title: '향후 시장 주요 이벤트',
    description: '개별 기업 실적 발표 이후, 시장의 관심은 다시 연준의 통화정책 향방을 가늠할 수 있는 거시 경제 지표로 이동할 전망입니다.',
    events: [
      {
        date: '2026-01-28',
        label: 'FOMC 회의',
        description: '제롬 파월 의장의 기자회견에서 3월 금리 인하 힌트 여부 주목',
      },
      {
        date: '2026-01-29',
        label: '주간 신규 실업수당 청구 건수',
        description: '노동 시장 온도를 통해 연준의 정책 경로 예측',
      },
      {
        date: '2026-02-20',
        label: '근원 PCE 가격지수',
        description: '연준이 가장 신뢰하는 물가 지표로, 통화정책의 핵심 변수',
      },
    ],
  },
  {
    id: 14,
    type: 'closing',
    turnId: 45,
    headline: '실적 장세 속, 다시 연준을 향하는 시선',
    tagline: '거시 경제 불확실성 속, 펀더멘털 기반의 신중한 접근이 유효한 시점입니다.',
    description: '시장은 연준의 빠른 금리 인하를 기대하고 있지만, 연준은 데이터에 기반한 신중한 결정을 강조하고 있습니다. 향후 발표될 고용 및 물가 지표를 통해 시장의 기대와 현실의 간극을 확인하는 과정이 필요합니다.',
  },
];