import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-03-31',
    nutshell: '이란 리스크 고조에 유가 급등, 기술주 하락',
    description:
      '3월 마지막 거래일, 시장은 중동의 지정학적 긴장으로 인한 유가 급등과 기술주 약세가 맞물리며 혼조세로 마감했습니다. 오늘 브리핑에서는 시장을 움직인 핵심 테마와 함께 팔로알토 네트웍스(PANW)를 심층 분석합니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '오늘의 시장 요약',
    description:
      '중동의 지정학적 긴장이 유가 급등을 촉발하며 시장에 부담으로 작용했습니다. 다우 지수는 에너지주의 강세에 힘입어 소폭 상승했지만, 기술주 중심의 나스닥은 큰 폭으로 하락하며 지수별 혼조세를 보였습니다.',
    indices: [
      { name: 'S&P 500', value: 6343.72, change: -25.13, changePercent: -0.39 },
      { name: 'NASDAQ', value: 20794.64, change: -153.72, changePercent: -0.73 },
      { name: 'DOW', value: 45216.14, change: 49.50, changePercent: 0.11 },
      { name: 'Russell 2000', value: 2414.01, change: -35.69, changePercent: -1.46 },
    ],
    commodities: [
      { name: 'WTI Crude', value: 105.01, change: 5.37, changePercent: 5.39 },
      { name: 'Gold Futures', value: 4540.40, change: 48.40, changePercent: 1.08 },
      { name: 'Dollar Index', value: 100.47, change: 0.32, changePercent: 0.32 },
      { name: '10-Yr Yield', value: 4.25, change: -0.02, changePercent: -0.51 },
    ],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
      { ticker: 'TVC:RUT' },
      { ticker: 'NYMEX:CL1!' },
      { ticker: 'TVC:DXY' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 7,
    icon: 'trending-up',
    title: '유가 쇼크, 시장을 덮치다',
    subtitle: '이란 리스크 고조에 WTI 유가 102달러 돌파',
    bullets: [
      '이란-미국 갈등 5주차, 후티 반군 분쟁 개입으로 격화',
      '서부 텍사스산 원유(WTI) 배럴당 102달러 돌파 (2022년 이후 최고)',
      '브렌트유, 배럴당 112달러 선까지 치솟으며 공급망 우려 증폭',
      '유가 급등이 인플레이션 우려를 자극하며 기술주 중심의 나스닥 하락 주도',
    ],
    theme: 'amber',
    charts: [
      { ticker: 'NYMEX:CL1!', title: 'WTI Crude Oil Futures' },
      { ticker: 'ICEEUR:BRN1!', title: 'Brent Crude Oil Futures' },
    ],
  },
  {
    id: 3,
    type: 'comparison',
    turnId: 8,
    title: '세계 원유 공급의 동맥, 이중 압박 상황',
    description:
      '기존 호르무즈 해협 리스크에 더해, 사우디의 우회 수출로인 바브엘만데브 해협까지 위협받으며 전 세계 원유 공급망에 대한 우려가 최고조에 달했습니다.',
    items: [
      {
        label: '호르무즈 해협',
        value: '1,500만 배럴/일',
        description: '기존 봉쇄 위협으로 공급 차질 발생',
        highlight: false,
      },
      {
        label: '바브엘만데브 해협',
        value: '700만 배럴/일',
        description: '후티 반군 사정권 진입으로 신규 위협 부상',
        highlight: true,
      },
      {
        label: '종합적 영향',
        value: '공급 충격 심화',
        description: '두 핵심 수송로 동시 위협으로 유가 변동성 극대화',
        highlight: false,
      },
    ],
  },
  {
    id: 4,
    type: 'stats',
    turnId: 9,
    title: '엇갈린 업종별 명암',
    description:
      '유가 급등은 에너지 섹터에는 호재로, 기술주 섹터에는 직격탄으로 작용하며 시장의 극명한 온도차를 만들었습니다.',
    stats: [
      { label: '에너지 섹터 (XLE)', value: '강세', subtext: '시장 유일의 승자', trend: 'up' },
      { label: '기술주 섹터 (XLK)', value: '약세', subtext: '인플레이션 우려에 직격탄', trend: 'down' },
      { label: '엑손모빌 (XOM)', value: '상승', subtext: '유가 급등 수혜', trend: 'up' },
      { label: '셰브론 (CVX)', value: '상승', subtext: '다우 지수 방어', trend: 'up' },
    ],
    theme: 'blue',
    charts: [
      { ticker: 'XLE', title: 'Energy Select Sector SPDR Fund' },
      { ticker: 'XLK', title: 'Technology Select Sector SPDR Fund' },
    ],
  },
  {
    id: 5,
    type: 'headline',
    turnId: 11,
    icon: 'alert-triangle',
    title: '인플레이션 vs. 경기 침체',
    subtitle: '시장의 딜레마와 연준의 스탠스',
    bullets: [
      '3월 소비자신뢰지수 88로 예상 하회, 소비 심리 위축 확인',
      '파월 의장, "에너지 가격 충격은 일시적, 투과해서 볼 것" 언급',
      '인플레이션 공포에도 불구, 10년물 국채 금리는 오히려 하락',
      '시장, 당장의 인플레이션보다 유가 충격이 초래할 경기 침체 가능성 주시',
    ],
    theme: 'purple',
    charts: [{ ticker: 'TVC:US10Y', title: 'U.S. 10-Year Treasury Yield' }],
  },
  {
    id: 6,
    type: 'headline',
    turnId: 17,
    icon: 'cpu',
    title: '이중고 겪는 반도체 섹터',
    subtitle: '거시 경제 불확실성과 내부 악재가 겹치며 동반 하락',
    bullets: [
      '유가 급등으로 인한 인플레이션 및 금리 상승 우려 부담',
      '구글의 AI 메모리 사용량 절감 알고리즘 발표 여파 지속',
      '마이크론(MU) 주가 9% 가까이 급락하며 섹터 하락 주도',
      '인텔(INTC), 엔비디아(NVDA), AMD 등 주요 반도체주 일제히 하락',
    ],
    theme: 'red',
    charts: [
      { ticker: 'MU', title: 'Micron Technology' },
      { ticker: 'NVDA', title: 'NVIDIA Corp' },
    ],
  },
  {
    id: 7,
    type: 'stats',
    turnId: 19,
    title: '리스크 확산: 유가 넘어 원자재 시장으로',
    description:
      '중동의 지정학적 긴장은 원유 시장을 넘어 다른 원자재 시장으로도 번졌습니다. 이란의 알루미늄 공장 공격 소식에 관련 선물 가격과 기업 주가가 동반 강세를 보였습니다.',
    stats: [
      { label: '알루미늄 선물', value: '+4.2%', subtext: '공급망 타격 우려', trend: 'up' },
      { label: '알코아 (AA)', value: '강세', subtext: '원자재 가격 급등 수혜', trend: 'up' },
      { label: '에너지 섹터 (XLE)', value: '강세', subtext: '유가 급등의 최대 수혜', trend: 'up' },
    ],
    theme: 'green',
    charts: [
      { ticker: 'COMEX:ALI1!', title: 'Aluminum Futures' },
      { ticker: 'AA', title: 'Alcoa Corp' },
    ],
  },
  {
    id: 8,
    type: 'ticker-intro',
    turnId: 22,
    ticker: 'PANW',
    companyName: 'Palo Alto Networks',
    currentPrice: 154.35,
    dayChange: 7.33,
    dayChangePercent: 4.99,
    description:
      '사이버 보안 선도 기업 팔로알토 네트웍스는 AI 시대의 보안 플랫폼 기업으로의 전환 기대감에 상승했으나, 장중 상승분을 일부 반납하며 마감했습니다.',
  },
  {
    id: 9,
    type: 'ticker-analysis',
    turnId: 23,
    ticker: 'PANW',
    title: '성장 스토리: 사이버 보안의 OS가 되는가?',
    points: [
      '단순 보안 회사를 넘어 AI 시대의 ‘사이버 보안 운영체제’로 진화 중',
      '최근 인수를 통해 네트워크, 클라우드, 신원까지 아우르는 통합 플랫폼 완성',
      '총매출의 81% 이상이 안정적인 구독 및 지원 서비스에서 발생',
      '차세대 보안 연간 반복 매출(ARR)이 63억 달러에 달하며 플랫폼 전략 성공 시사',
    ],
    outlook: '긍정적',
    outlookColor: 'emerald',
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 25,
    ticker: 'PANW',
    title: '잠재된 리스크: 경쟁 심화와 재무적 부담',
    points: [
      '마이크로소프트 등 거대 기술 기업의 ‘번들링’ 전략이 가격 결정력 위협',
      '약 68억 달러에 달하는 비취소성 구매 약정은 막대한 고정 비용 부담',
      '경기 둔화 시 고정비 부담이 이익률을 급격히 악화시키는 도화선 될 수도',
      '성장 내러티브 이면에 숨겨진 경쟁 및 재무 리스크에 대한 검토 필요',
    ],
    outlook: '신중',
    outlookColor: 'amber',
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 27,
    ticker: 'PANW',
    title: '재무 건전성 톺아보기: 이익의 질은?',
    points: [
      '상반기 영업이익의 95%가 주식 기반 보상 비용(SBC)으로 발생',
      '이익의 대부분이 기존 주주가치를 희석시키는 방식으로 임직원에게 지급',
      '상반기에만 기업 인수에 26억 달러 현금 사용, 영업 현금 흐름 초과',
      '유기적 성장보다 M&A를 통해 성장을 ‘사는’ 전략은 통합 실패 리스크 내포',
    ],
    outlook: '경계',
    outlookColor: 'rose',
  },
  {
    id: 12,
    type: 'stats',
    turnId: 29,
    title: '팔로알토 네트웍스 투자포인트 요약',
    description:
      '시장은 ‘사이버 보안의 OS’라는 미래 비전에 열광하고 있지만, 그 비전을 실현하기 위해 회사가 감수하는 리스크의 규모 또한 상당합니다.',
    stats: [
      { label: '성장 동력', value: '플랫폼 전환', subtext: '통합 보안 솔루션', trend: 'up' },
      { label: '주요 위협', value: '빅테크 경쟁', subtext: 'MS의 번들링 전략', trend: 'down' },
      { label: '재무 리스크', value: '높은 고정비', subtext: '$68억 구매 약정', trend: 'down' },
      { label: '주주가치', value: 'SBC 부담', subtext: '이익의 95% 차지', trend: 'neutral' },
    ],
    note: '화려한 성장 내러티브 이면에 숨겨진 구체적인 위험들을 면밀히 검토하며 신중하게 접근해야 할 시점입니다.',
    theme: 'gold',
  },
  {
    id: 13,
    type: 'headline',
    turnId: 31,
    icon: 'pause-circle',
    title: '1분기 마감, 숨 고르기 장세',
    subtitle: '차익 실현과 관망 심리가 교차하며 방향성 탐색',
    bullets: [
      '1분기 동안 강하게 달려온 시장, 분기 말을 맞아 차익 실현 움직임',
      '연준의 금리 인하 경로에 대한 불확실성 여전히 상존',
      '투자자들, 섣부른 움직임보다 경제 지표 확인하려는 신중한 태도',
      '시장은 다음 주 발표될 고용 보고서를 기다리며 관망세 돌입',
    ],
  },
  {
    id: 14,
    type: 'events',
    turnId: 33,
    title: '2분기를 여는 경제 이벤트',
    description:
      '새로운 분기가 시작되는 다음 주, 연준의 정책 방향에 대한 단서를 제공할 핵심 고용 지표들이 연이어 발표될 예정입니다.',
    events: [
      {
        date: '4/1 (수)',
        label: 'ADP 민간고용 보고서',
        description: '공식 고용보고서의 예고편으로 노동시장 온도를 가늠',
      },
      {
        date: '4/1 (수)',
        label: 'ISM 제조업 구매관리자지수',
        description: '미국 제조업 경기의 확장 혹은 둔화 여부 판단',
      },
      {
        date: '4/3 (금)',
        label: '3월 비농업 고용지표',
        description: '연준이 가장 중요하게 보는 고용 데이터',
      },
      {
        date: '4/3 (금)',
        label: '3월 실업률 및 임금 상승률',
        description: '인플레이션 압력과 직결되는 세부 항목',
      },
    ],
  },
  {
    id: 15,
    type: 'closing',
    turnId: 37,
    headline: '변동성에 대비하는 2분기',
    tagline: '지표를 통해 경제의 큰 흐름을 읽는 지혜가 필요한 시점입니다.',
    description:
      '1분기 시장은 예상보다 강한 모습을 보였지만, 높아진 기대치만큼 변동성 확대 가능성도 염두에 두어야 합니다. 이번 주 발표될 고용 지표 결과에 일희일비하기보다, 큰 흐름 속에서 신중한 투자 전략을 세우는 것이 중요합니다.',
  },
];