import type { Slide } from '@/types/slide';

export const slides: Slide[] = [
  {
    id: 0,
    type: 'title',
    turnId: 0,
    date: '2026-03-20',
    nutshell: '중동 지정학적 긴장 고조 속 시장 혼조 마감',
    description:
      '중동의 지정학적 갈등이 유가 급등을 초래하며 시장 전반에 인플레이션 우려를 자극했습니다. 주요 지수는 하락했으나 에너지 섹터는 강세를 보였고, 중소형주는 상승하는 등 섹터별 차별화가 뚜렷한 하루였습니다.',
  },
  {
    id: 1,
    type: 'market-summary',
    turnId: 1,
    title: '주요 지수 및 원자재 동향',
    description:
      '이스라엘과 이란의 갈등 격화로 국제 유가가 급등하며 시장이 혼조세를 보였습니다. 대형주 중심의 주요 지수는 하락했으나, 에너지주 강세에 힘입어 중소형주 지수는 상승 마감했습니다.',
    indices: [
      { name: 'S&P 500', value: 6606.49, change: -18.21, changePercent: -0.27 },
      { name: 'NASDAQ', value: 22090.69, change: -61.73, changePercent: -0.28 },
      { name: 'DOW', value: 46021.43, change: -203.72, changePercent: -0.44 },
      { name: 'Russell 2000', value: 2494.71, change: 16.07, changePercent: 0.65 },
    ],
    commodities: [
      { name: 'WTI Crude', value: 94.59, change: -1.73, changePercent: -1.80 },
      { name: 'Gold Futures', value: 4651.90, change: -238.00, changePercent: -4.87 },
      { name: 'Dollar Index', value: 99.19, change: -0.90, changePercent: -0.90 },
      { name: '美 10년물 금리', value: 4.28, change: 0.02, changePercent: 0.52 },
    ],
    charts: [
      { ticker: 'SP:SPX' },
      { ticker: 'NASDAQ:IXIC' },
      { ticker: 'DJ:DJI' },
      { ticker: 'TVC:RUT' },
      { ticker: 'NYMEX:CL1!' },
      { ticker: 'COMEX:GC1!' },
      { ticker: 'TVC:DXY' },
    ],
  },
  {
    id: 2,
    type: 'headline',
    turnId: 6,
    icon: 'flame',
    title: '중동 지정학적 리스크',
    subtitle: '에너지 공급망 직접 타격과 시장 충격',
    description:
      '이스라엘과 이란이 서로의 핵심 에너지 시설을 공격하는 전면전 양상으로 치달으면서, 세계 에너지 공급망에 대한 우려가 최고조에 달했습니다. 이는 유가 급등과 인플레이션 공포로 이어졌습니다.',
    bullets: [
      '이스라엘-이란, 상호 에너지 시설 보복 공격',
      '카타르 LNG 터미널 등 핵심 인프라 피격',
      '브렌트유, 장중 배럴당 $112 돌파하며 급등',
      '인플레이션 공포 재점화, 국채 금리 상승 압력',
    ],
    theme: 'red',
  },
  {
    id: 3,
    type: 'stats',
    turnId: 7,
    title: '지정학적 리스크의 시장 파급 효과',
    description:
      '중동발 공급망 충격은 원자재부터 채권, 주식 시장까지 연쇄 반응을 일으키며 변동성을 극대화했습니다.',
    stats: [
      { label: '브렌트유 (BRN1!)', value: '$112+', subtext: '장중 최고가', trend: 'up' },
      { label: '美 10년물 국채금리', value: '4.32%', subtext: '장중 최고치', trend: 'up' },
      { label: '변동성 지수 (VIX)', value: '+10%', subtext: '장중 27.5 기록', trend: 'up' },
    ],
    note: '유가 급등이 인플레이션 우려를 자극하며 연준의 긴축 장기화 가능성을 높였습니다.',
    theme: 'red',
    charts: [{ ticker: 'ICEEUR:BRN1!' }, { ticker: 'TVC:US10Y' }, { ticker: 'TVC:VIX' }],
  },
  {
    id: 4,
    type: 'headline',
    turnId: 9,
    icon: 'landmark',
    title: '연준의 딜레마: 스태그플레이션 공포',
    subtitle: '통제 불가능한 변수와 통화정책의 향방',
    description:
      '이번 유가 상승은 수요가 아닌 공급망 충격에서 비롯된 비용 인상 인플레이션으로, 연준을 매우 곤혹스러운 상황에 빠뜨렸습니다. 시장은 경기 둔화를 감수하는 긴축 장기화 시나리오를 우려하고 있습니다.',
    bullets: [
      '공급 충격발 ‘비용 인상 인플레이션’ 우려',
      '경기 둔화 감수하고 긴축 장기화 가능성 대두',
      '시장, 금리 인하 지연 또는 추가 인상 가능성 반영',
      '맥쿼리, "2027년 상반기 금리 인상" 전망 제시',
    ],
    theme: 'amber',
    charts: [{ ticker: 'TVC:US10Y' }],
  },
  {
    id: 5,
    type: 'comparison',
    turnId: 11,
    title: '에너지 vs. 시장: 극명한 디커플링',
    description:
      '유가 급등은 에너지 섹터에는 호재, 시장 전반에는 악재로 작용하며 섹터별 차별화 장세를 연출했습니다. 에너지 섹터의 나 홀로 강세만으로는 시장 전체를 이끌기에 역부족이었습니다.',
    items: [
      {
        label: '에너지 섹터 (XLE)',
        value: '강세',
        description: '유가 급등으로 인한 수익성 개선 기대감. 엑손모빌(XOM), 셰브론(CVX) 등 동반 상승.',
        highlight: true,
      },
      {
        label: '기술주 섹터 (XLK)',
        value: '약세',
        description: '비용 증가 및 긴축 우려로 하락 압력. 시장 전체를 끌어내리는 주요 요인으로 작용.',
        highlight: false,
      },
      {
        label: 'S&P 500 지수',
        value: '하락',
        description: '에너지 섹터의 상승분만으로는 기술주 등 다른 섹터의 하락을 상쇄하기에 역부족.',
        highlight: false,
      },
    ],
    charts: [{ ticker: 'AMEX:XLE' }, { ticker: 'AMEX:XLK' }, { ticker: 'SP:SPX' }],
  },
  {
    id: 6,
    type: 'stats',
    turnId: 15,
    title: '에너지 섹터, 나 홀로 질주',
    description:
      '유가 급등은 시장 전반에 악재였지만, 에너지 관련주에는 강력한 호재로 작용하며 뚜렷한 주가 상승을 이끌었습니다.',
    stats: [
      { label: '에너지 ETF (XLE)', value: '+0.8%', subtext: 'S&P 500 유일 상승 섹터', trend: 'up' },
      { label: '엑손모빌 (XOM)', value: '+1.2%', subtext: '유가 상승 수혜', trend: 'up' },
      { label: '셰브론 (CVX)', value: '+1.5%', subtext: '동반 강세', trend: 'up' },
    ],
    theme: 'green',
    charts: [{ ticker: 'AMEX:XLE' }, { ticker: 'NYSE:XOM' }, { ticker: 'NYSE:CVX' }],
  },
  {
    id: 7,
    type: 'headline',
    turnId: 19,
    icon: 'bar-chart-2',
    title: '고유가 시대의 서막?',
    subtitle: '장기화되는 지정학적 리스크와 시장 전망',
    description:
      '일부 분석가들은 호르무즈 해협의 불안정성이 지속될 경우, 유가가 장기간 높은 수준을 유지할 수 있다고 전망하며 에너지 섹터의 독주가 이어질 가능성을 제기합니다.',
    bullets: [
      '호르무즈 해협 불안정성 지속 우려',
      '유가, 2026년까지 배럴당 $90 이상 유지 전망',
      '에너지 기업 실적 기대감 지속 가능성',
      '타 섹터 리더십 부재 시 시장 발목 잡을 우려',
    ],
    theme: 'gold',
  },
  {
    id: 8,
    type: 'ticker-intro',
    turnId: 20,
    ticker: 'NEM',
    companyName: 'Newmont Corporation',
    currentPrice: 99.20,
    dayChange: -7.34,
    dayChangePercent: -6.89,
    description:
      '대표적인 금광 기업 뉴몬트는 장 초반 급락 후 강한 매수세가 유입되며 낙폭을 대부분 만회했습니다. 이는 뉴몬트를 둘러싼 성장주와 전통 원자재주라는 극명한 시각차를 보여줍니다.',
    charts: [{ ticker: 'NYSE:NEM' }],
  },
  {
    id: 9,
    type: 'ticker-analysis',
    turnId: 23,
    ticker: 'NEM',
    title: '뉴몬트 재평가 (Bull): ‘자원 테크’ 기업으로의 도약',
    points: [
      '기술 혁신: 자율주행 채굴 트럭, AI 기반 탐사로 비용 구조 혁신',
      'M&A 시너지: 뉴크레스트 인수로 연간 5억 달러 이상 시너지 기대',
      '강력한 현금흐름: 2025년 잉여현금흐름 $73억 예상',
      '주주 환원: $23억 규모의 자사주 매입 계획으로 자신감 표현',
    ],
    outlook: '기술적 해자를 통해 지속 가능한 성장이 가능하다는 긍정적 시각이 부각되고 있습니다.',
    outlookColor: 'emerald',
  },
  {
    id: 10,
    type: 'ticker-analysis',
    turnId: 25,
    ticker: 'NEM',
    title: '뉴몬트 재평가 (Bear): 극복하기 어려운 본질적 리스크',
    points: [
      '금 가격 의존도: 금 가격 20% 하락 시 현금 창출 능력 30% 이상 감소 가능',
      '지정학적 리스크: 멕시코 광산 노사 문제로 4개월 운영 중단 사례',
      '규제 리스크: 호주 광산 환경 규제로 인한 생산 차질 등 변수 상존',
      '기술의 한계: 기술 혁신만으로 정치적, 사회적 리스크를 완전히 통제하기는 어려움',
    ],
    outlook: '외부 변수에 취약한 광산업의 본질적인 리스크가 여전히 크다는 비관론도 팽팽합니다.',
    outlookColor: 'rose',
  },
  {
    id: 11,
    type: 'ticker-analysis',
    turnId: 27,
    ticker: 'NEM',
    title: '뉴몬트 투자 판단: 잠재력과 리스크의 균형',
    points: [
      '입증 필요: 기술 혁신의 성과가 재무제표에 구체적으로 반영되는지 확인 필요',
      '양날의 검: 높은 금 가격은 현금 흐름을 지지하지만, 하락 시 충격도 큼',
      '통제 불가능한 위협: 멕시코 파업 사례처럼 실제 위협의 무게가 가볍지 않음',
      '신중한 접근: 지정학적 불확실성 완화 확인 전까지 신중한 접근이 유효',
    ],
    outlook: '성장 잠재력은 유효하나, 산업 고유의 리스크가 완전히 해소되지 않아 확인이 필요한 시점입니다.',
    outlookColor: 'amber',
  },
  {
    id: 12,
    type: 'headline',
    turnId: 28,
    icon: 'trending-up',
    title: '비둘기파적 FOMC에 시장 환호',
    subtitle: '3대 지수, 사상 최고치 경신',
    description:
      '연준이 올해 세 차례 금리 인하 전망을 유지하며 시장의 불확실성을 해소했습니다. 파월 의장의 완화적 발언에 힘입어 3대 지수 모두 종가 기준 사상 최고치를 기록했습니다.',
    bullets: [
      '연준, 올해 3차례 금리 인하 전망 유지',
      '파월 의장, 최근 물가 지표를 ‘계절적 요인’으로 해석',
      '강력한 고용이 금리 인하의 장애물이 아님을 시사',
      '불확실성 해소에 강력한 매수세 유입',
    ],
    theme: 'blue',
    charts: [{ ticker: 'SP:SPX' }, { ticker: 'NASDAQ:IXIC' }, { ticker: 'DJ:DJI' }],
  },
  {
    id: 13,
    type: 'events',
    turnId: 31,
    title: '향후 주목할 주요 경제 지표',
    description:
      'FOMC 이후, 시장의 관심은 연준의 정책 기대를 뒷받침할 실물 경제 데이터로 이동하고 있습니다. 특히 경기와 인플레이션 관련 지표가 중요합니다.',
    events: [
      {
        date: '3/21 (목)',
        label: 'S&P 글로벌 PMI 예비치',
        description: '제조업 및 서비스업 경기를 보여주는 핵심 선행 지표.',
      },
      {
        date: '3/21 (목)',
        label: '주간 신규 실업수당 청구건수',
        description: '고용 시장의 최신 동향 파악.',
      },
      {
        date: '3/29 (금)',
        label: '2월 개인소비지출(PCE) 물가지수',
        description: '연준이 가장 중요하게 참고하는 인플레이션 지표.',
      },
    ],
  },
  {
    id: 14,
    type: 'headline',
    turnId: 35,
    icon: 'dollar-sign',
    title: '시장의 향방을 가를 PCE 물가',
    subtitle: '6월 금리 인하의 정당성 확보 여부',
    description:
      '연준이 통화정책 결정 시 가장 중요하게 참고하는 2월 PCE 물가지수 발표가 예정되어 있습니다. 이 지표의 결과에 따라 6월 금리 인하에 대한 시장의 기대가 유지될지 결정될 수 있습니다.',
    bullets: [
      'PCE는 연준이 CPI보다 더 중요하게 참고하는 지표',
      '1월에 예상보다 높았던 만큼 2월 둔화 여부가 관건',
      '인플레이션 둔화 확신을 줘야 6월 금리 인하 기대 유지 가능',
      '결과에 따라 다음 FOMC까지 시장 방향성 결정될 수 있음',
    ],
    theme: 'purple',
  },
  {
    id: 15,
    type: 'closing',
    turnId: 36,
    headline: '지정학적 리스크와 통화정책 기대의 공존',
    tagline: '변동성 속 기회를 탐색하는 시장',
    description:
      '오늘은 중동의 지정학적 긴장이 유가를 급등시키며 시장에 부담을 준 한편, 연준의 완화적 정책 기대감이 하단을 지지하는 복합적인 장세가 펼쳐졌습니다. 향후 발표될 인플레이션 지표가 시장의 방향성을 결정할 중요한 분수령이 될 것입니다.',
  },
];